# Generated by Django 3.1.7 on 2022-05-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubjectscreening',
            name='nationality',
            field=models.CharField(default='Tz', max_length=60, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='subjectscreening',
            name='nationality',
            field=models.CharField(default='Tz', max_length=60, verbose_name='Nationality'),
        ),
    ]
