# Generated by Django 3.1.7 on 2022-02-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_screening', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='patient_category',
            field=models.CharField(choices=[('lung_cancer_suspect', 'Lung cancer suspect'), ('other_cancers', 'Other cancers'), ('cancer_free', 'Cancer free')], max_length=45, verbose_name='Patient Category?'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='patient_category',
            field=models.CharField(choices=[('lung_cancer_suspect', 'Lung cancer suspect'), ('other_cancers', 'Other cancers'), ('cancer_free', 'Cancer free')], max_length=45, verbose_name='Patient Category?'),
        ),
    ]
