# Generated by Django 3.1.7 on 2021-11-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edcs_screening", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsubjectscreening",
            name="clinic",
            field=models.CharField(
                choices=[
                    ("lung_cancer", "Lung cancer clinic/institute"),
                    ("pathology", "Pathology"),
                    ("other_clinic", "Other ward/clinic other than cancer"),
                ],
                max_length=50,
                null=True,
                verbose_name="Clinic patient is from?:",
            ),
        ),
        migrations.AddField(
            model_name="historicalsubjectscreening",
            name="patient_category",
            field=models.CharField(
                choices=[
                    ("lung_cancer_suspect", "Lung cancer suspect"),
                    ("other_cancers", "Other cancers"),
                    ("cancer_free", "Cancer free"),
                ],
                max_length=50,
                null=True,
                verbose_name="Patient Category?:",
            ),
        ),
        migrations.AddField(
            model_name="subjectscreening",
            name="clinic",
            field=models.CharField(
                choices=[
                    ("lung_cancer", "Lung cancer clinic/institute"),
                    ("pathology", "Pathology"),
                    ("other_clinic", "Other ward/clinic other than cancer"),
                ],
                max_length=50,
                null=True,
                verbose_name="Clinic patient is from?:",
            ),
        ),
        migrations.AddField(
            model_name="subjectscreening",
            name="patient_category",
            field=models.CharField(
                choices=[
                    ("lung_cancer_suspect", "Lung cancer suspect"),
                    ("other_cancers", "Other cancers"),
                    ("cancer_free", "Cancer free"),
                ],
                max_length=50,
                null=True,
                verbose_name="Patient Category?:",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="district",
            field=models.CharField(max_length=50, verbose_name="District:"),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="patient_know_dob",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=50,
                verbose_name="Does the patient know his/her date of birth?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsubjectscreening",
            name="region",
            field=models.CharField(max_length=50, verbose_name="Region:"),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="district",
            field=models.CharField(max_length=50, verbose_name="District:"),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="patient_know_dob",
            field=models.CharField(
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=50,
                verbose_name="Does the patient know his/her date of birth?",
            ),
        ),
        migrations.AlterField(
            model_name="subjectscreening",
            name="region",
            field=models.CharField(max_length=50, verbose_name="Region:"),
        ),
    ]
