# Generated by Django 3.1.7 on 2024-03-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_screening', '0002_auto_20220505_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubjectscreening',
            name='ct_findings_report',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True, verbose_name='Did the CT scan findings report suggest lung malignancy? '),
        ),
        migrations.AddField(
            model_name='historicalsubjectscreening',
            name='dx_tb_clinical_criteria',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True, verbose_name='Diagnosed with TB on clinical criteria / sputum negative, no clinical improvement 2 months or more after starting TB treatment and Viral Load below 200copies/ml.'),
        ),
        migrations.AddField(
            model_name='historicalsubjectscreening',
            name='tb_pleurisy',
            field=models.CharField(choices=[('Yes', 'Yes (Tap the pleural fluid do cytology and CT scan)'), ('No', 'No')], max_length=25, null=True, verbose_name='TB pleurisy (a pleural effusion and pleuritis secondary to Mycobacterium infection)'),
        ),
        migrations.AddField(
            model_name='subjectscreening',
            name='ct_findings_report',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True, verbose_name='Did the CT scan findings report suggest lung malignancy? '),
        ),
        migrations.AddField(
            model_name='subjectscreening',
            name='dx_tb_clinical_criteria',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=25, null=True, verbose_name='Diagnosed with TB on clinical criteria / sputum negative, no clinical improvement 2 months or more after starting TB treatment and Viral Load below 200copies/ml.'),
        ),
        migrations.AddField(
            model_name='subjectscreening',
            name='tb_pleurisy',
            field=models.CharField(choices=[('Yes', 'Yes (Tap the pleural fluid do cytology and CT scan)'), ('No', 'No')], max_length=25, null=True, verbose_name='TB pleurisy (a pleural effusion and pleuritis secondary to Mycobacterium infection)'),
        ),
    ]
