# Generated by Django 3.1.7 on 2024-03-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_screening', '0003_auto_20240305_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubjectscreening',
            name='other_cancer',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('cervical_cancer', 'Cervical cancer'), ('kaposi_sarcoma', 'Kaposi sarcoma'), ('non_hodgkins_lymphoma', 'Non Hodgkin’s lymphoma')], max_length=45, null=True, verbose_name='For other cancers (Please clarify)'),
        ),
        migrations.AddField(
            model_name='subjectscreening',
            name='other_cancer',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('cervical_cancer', 'Cervical cancer'), ('kaposi_sarcoma', 'Kaposi sarcoma'), ('non_hodgkins_lymphoma', 'Non Hodgkin’s lymphoma')], max_length=45, null=True, verbose_name='For other cancers (Please clarify)'),
        ),
    ]
