# Generated by Django 3.1.7 on 2022-01-04 11:53

from django.db import migrations
import edcs_model.fields.identity_type_field
import edcs_model.models.fields.date_estimated


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregisteredsubject',
            name='identity_type',
            field=edcs_model.fields.identity_type_field.IdentityTypeField(blank=True, choices=[('OMANG', 'Omang'), ('DRIVERS', "Driver's License"), ('PASSPORT', 'Passport'), ('OMANG_RCPT', 'Omang Receipt'), ('OTHER', 'Other')], max_length=15, null=True, verbose_name='What type of identity number is this?'),
        ),
        migrations.AddField(
            model_name='historicalregisteredsubject',
            name='is_dob_estimated',
            field=edcs_model.models.fields.date_estimated.IsDateEstimatedField(choices=[('-', 'No'), ('D', 'Yes, estimated the Day'), ('MD', 'Yes, estimated Month and Day'), ('YMD', 'Yes, estimated Year, Month and Day')], help_text='If the exact date is not known, please indicate which part of the date is estimated.', max_length=25, null=True, verbose_name='Is date of birth estimated?'),
        ),
        migrations.AddField(
            model_name='registeredsubject',
            name='identity_type',
            field=edcs_model.fields.identity_type_field.IdentityTypeField(blank=True, choices=[('OMANG', 'Omang'), ('DRIVERS', "Driver's License"), ('PASSPORT', 'Passport'), ('OMANG_RCPT', 'Omang Receipt'), ('OTHER', 'Other')], max_length=15, null=True, verbose_name='What type of identity number is this?'),
        ),
        migrations.AddField(
            model_name='registeredsubject',
            name='is_dob_estimated',
            field=edcs_model.models.fields.date_estimated.IsDateEstimatedField(choices=[('-', 'No'), ('D', 'Yes, estimated the Day'), ('MD', 'Yes, estimated Month and Day'), ('YMD', 'Yes, estimated Year, Month and Day')], help_text='If the exact date is not known, please indicate which part of the date is estimated.', max_length=25, null=True, verbose_name='Is date of birth estimated?'),
        ),
    ]
