# Generated by Django 3.1.7 on 2021-04-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_notification', '0001_initial'),
        ('edcs_auth', '0003_auto_20210420_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.ManyToManyField(blank=True, limit_choices_to={'enabled': True}, related_name='email_notifications', to='edcs_notification.Notification'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sms_notifications',
            field=models.ManyToManyField(blank=True, limit_choices_to={'enabled': True}, related_name='sms_notifications', to='edcs_notification.Notification'),
        ),
    ]
