# Generated by Django 3.1.7 on 2021-04-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_auth', '0004_auto_20210421_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='export_format',
            field=models.CharField(blank=True, choices=[('CSV', 'CSV')], default='CSV', help_text='Note: requires export permissions', max_length=25, null=True, verbose_name='Export format'),
        ),
    ]
