# Generated by Django 3.1.7 on 2021-04-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_auth', '0005_userprofile_export_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='export_format',
            field=models.CharField(blank=True, choices=[('CSV', 'CSV')], help_text='Note: requires export permissions', max_length=25, null=True, verbose_name='Export format'),
        ),
    ]
