# Generated by Django 3.1.7 on 2021-04-29 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_auth', '0006_auto_20210421_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='export_format',
            field=models.CharField(blank=True, choices=[('CSV', 'CSV')], default='CSV', help_text='Note: requires export permissions', max_length=25, null=True, verbose_name='Export format'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, help_text='e.g. +0123456789', max_length=25, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+\\d+')]),
        ),
    ]
