# Generated by Django 3.1.7 on 2021-09-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_auth', '0007_auto_20210510_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import'), 'get_latest_by': 'modified', 'ordering': ['display_index', 'display_name']},
        ),
    ]
