# Generated by Django 3.1.7 on 2022-01-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimepointLookupModelMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='timepoint_closed_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='timepoint_opened_datetime',
            field=models.DateTimeField(editable=False, help_text="the original calculated model's datetime, updated in the signal", null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='timepoint_status',
            field=models.CharField(choices=[('new', 'New'), ('start', 'Start'), ('open', 'Open'), ('incomplete', 'Incomplete'), ('closed', 'Closed')], default='new', max_length=15),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='timepoint_closed_datetime',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='timepoint_opened_datetime',
            field=models.DateTimeField(editable=False, help_text="the original calculated model's datetime, updated in the signal", null=True),
        ),
        migrations.AddField(
            model_name='historicalappointment',
            name='timepoint_status',
            field=models.CharField(choices=[('new', 'New'), ('start', 'Start'), ('open', 'Open'), ('incomplete', 'Incomplete'), ('closed', 'Closed')], default='new', max_length=15),
        ),
    ]
