# Generated by Django 3.1.7 on 2022-01-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_appointment', '0002_auto_20220120_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appt_reason',
            field=models.CharField(choices=[('scheduled', 'Routine / Scheduled'), ('unscheduled', 'Unscheduled')], default='scheduled', help_text="The visit report's `reason for visit` will be validated against this. Refer to the protocol's documentation for the definition of a `scheduled` visit.", max_length=25, verbose_name='Reason for appointment'),
        ),
        migrations.AlterField(
            model_name='historicalappointment',
            name='appt_reason',
            field=models.CharField(choices=[('scheduled', 'Routine / Scheduled'), ('unscheduled', 'Unscheduled')], default='scheduled', help_text="The visit report's `reason for visit` will be validated against this. Refer to the protocol's documentation for the definition of a `scheduled` visit.", max_length=25, verbose_name='Reason for appointment'),
        ),
    ]
