# Generated by Django 3.1.7 on 2022-01-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_appointment', '0004_auto_20220121_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appt_status',
            field=models.CharField(choices=[('start', 'Start'), ('in_progress', 'In Progress'), ('incomplete', 'Incomplete'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='new', help_text="If the visit has already begun, only 'in progress', 'incomplete' or 'done' are valid options", max_length=25, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalappointment',
            name='appt_status',
            field=models.CharField(choices=[('start', 'Start'), ('in_progress', 'In Progress'), ('incomplete', 'Incomplete'), ('done', 'Done'), ('cancelled', 'Cancelled')], db_index=True, default='new', help_text="If the visit has already begun, only 'in progress', 'incomplete' or 'done' are valid options", max_length=25, verbose_name='Status'),
        ),
    ]
