# Generated by Django 3.1.7 on 2022-01-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_appointment', '0005_auto_20220121_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timepoint_status',
            field=models.CharField(choices=[('new', 'New'), ('start', 'Start'), ('open', 'Open'), ('incomplete', 'Incomplete'), ('closed', 'Closed')], default='new', max_length=15),
        ),
        migrations.AlterField(
            model_name='historicalappointment',
            name='timepoint_status',
            field=models.CharField(choices=[('new', 'New'), ('start', 'Start'), ('open', 'Open'), ('incomplete', 'Incomplete'), ('closed', 'Closed')], default='new', max_length=15),
        ),
    ]
