ACCOUNT_MANAGER_ROLE = "account_manager"
CLINIC_SUPER_ROLE = "clinic_super"
CLINIC_ROLE = "clinic"
CUSTOM_ROLE = "custom"
STAFF_ROLE = "staff"
LABORATORY_ROLE = "laboratory"
COMMUNITY_HEALTH_WORKER = "community_health_worker"
