# Generated by Django 3.1.7 on 2021-05-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_vac083', '0003_auto_20210501_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningtwo',
            name='additional',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No'), ('3', 'NA')], default='', editable=False, max_length=20, verbose_name='Were additional OR repeat tests requested at this visit?'),
        ),
        migrations.AddField(
            model_name='screeningtwo',
            name='additional_test',
            field=models.CharField(choices=[('1', 'Hematology'), ('2', 'Biochemistry'), ('3', 'Parasitology'), ('4', 'Urinalysis'), ('5', 'Pregnancy Test'), ('6', 'Serology'), ('7', 'Other')], default='', editable=False, max_length=1, verbose_name='If “yes’ specify which tests were requested below and complete unscheduled laboratory investigation form:'),
        ),
        migrations.AddField(
            model_name='screeningtwo',
            name='additional_test_other',
            field=models.TextField(default='', editable=False, verbose_name='Specify'),
        ),
        migrations.AddField(
            model_name='screeningtwo',
            name='bednet',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='', editable=False, max_length=20, verbose_name='Did the volunteer receive an insecticide treated bed net?'),
        ),
        migrations.AddField(
            model_name='screeningtwo',
            name='procedures',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='', editable=False, max_length=1, verbose_name='Did all procedures of SC2 been completed?'),
        ),
        migrations.AddField(
            model_name='screeningtwo',
            name='procedures_no',
            field=models.CharField(choices=[('1', 'Volunteer requires treatment before enrolment (update medical history section)'), ('2', 'Volunteer require repeat/additional sample analysis'), ('3', 'Other, please specify')], default='', editable=False, max_length=25, verbose_name='If No, Tick appropriate reason.'),
        ),
        migrations.AddField(
            model_name='screeningtwo',
            name='procedures_no_other',
            field=models.CharField(default='', editable=False, max_length=25, verbose_name='If No, Specify'),
        ),
        migrations.AddField(
            model_name='screeningtwo',
            name='reason',
            field=models.CharField(choices=[('1', 'Subject illness or injury'), ('2', 'Subject refusal'), ('3', 'Scheduling difficulties'), ('4', 'Unable to contact'), ('5', 'Transportation problems'), ('6', 'Temporarily out of study area'), ('7', 'Subject forgot'), ('8', 'Site decision/error, specify:'), ('9', 'Other, specify:')], default='', editable=False, max_length=1),
        ),
        migrations.AddField(
            model_name='screeningtwo',
            name='reason_other',
            field=models.CharField(default='', editable=False, max_length=25, verbose_name='Other, specify:'),
        ),
        migrations.AddField(
            model_name='screeningtwo',
            name='referral',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='', editable=False, max_length=1, verbose_name='Does volunteer require referral to another health facility for further medical care?'),
        ),
        migrations.AddField(
            model_name='screeningtwo',
            name='referral_yes',
            field=models.TextField(choices=[('1', 'Yes'), ('2', 'No')], default='', editable=False, verbose_name='If Yes, specify below and complete appropriate referral document'),
        ),
        migrations.AddField(
            model_name='screeningtwo',
            name='site_decision',
            field=models.TextField(default='', editable=False, verbose_name='Site decision/error, specify:'),
        ),
        migrations.AddField(
            model_name='screeningtwo',
            name='visit_code',
            field=models.CharField(choices=[('1', 'sc2')], default='', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='allergic',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1, verbose_name='History of allergic disease or reactions likely to be exacerbated by anycomponent of the vaccine (e.g. egg products)'),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='anaphylaxis',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1, verbose_name='Any history of anaphylaxis in reaction to vaccinations'),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='cancer',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1, verbose_name='History of cancer (except basal cell carcinoma of the skin and cervicalCarcinoma in situ).'),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='chronic',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1, verbose_name='Any other serious chronic illness requiring hospital specialist supervision'),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='clinically',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1, verbose_name='Any clinically significant abnormal finding on biochemistry or hematology blood tests,urinalysis or clinical examination. In the event of clinically significant abnormal test results, confirmatory repeat tests will be requested. Procedures for identifying laboratory values meeting exclusion criteria will be described in a study specific SOP.'),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='clinician_initials',
            field=models.CharField(max_length=3, verbose_name='Clinician Initials:'),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='concurrent',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1, verbose_name='Concurrent involvement in another clinical trial or planned involvement during the study period'),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='confirmed',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1, verbose_name='Any confirmed or suspected immunosuppressive or immunodeficient state,including HIV infection; asplenia; recurrent, severe infections and chronic (more than 14 days immunosuppressant medication within the past 6 months (inhaled and topical steroids are allowed).'),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='disease',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No'), ('3', 'NA')], max_length=1, verbose_name='Any other significant disease, disorder, or finding which may significantly increase the risk to the volunteer because of participation in the study, affect the ability of the volunteer to participate in the study or impair interpretation of the study data.'),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='enrolled',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1, verbose_name='Can the participant be enrolled in the study?'),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='injecting',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1, verbose_name='Suspected or known injecting drug abuse in the 5 years preceding enrolment'),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='interpretation',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No'), ('3', 'NA')], max_length=1, verbose_name='Prior receipt of an investigational vaccine likely to impact on interpretation of the trial data, as assessed by the Investigator'),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='pregnant',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1, verbose_name='Pregnancy, lactation or intention to become pregnant during the study'),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='products',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], help_text='(e.g., blood transfusion) at any time in the past', max_length=1, verbose_name='Use of immunoglobulins or blood products'),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='psychiatric',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1, verbose_name='History of serious psychiatric condition that may affect participation in the Study.'),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='reason',
            field=models.CharField(choices=[('1', 'Eligibility criteria not fulfilled'), ('2', 'Consent withdrawal / not willing to participate'), ('3', 'Migrated / moved from the study area'), ('4', 'Other (please specify):')], max_length=1, verbose_name='*If No, specify the reason for screening failure (Tick one box only)'),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='surface',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1, verbose_name='Seropositive for hepatitis B surface antigen (HBsAg) or hepatitis C (HCV IgG).'),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='vaccine14',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1, verbose_name='Receipt of any vaccine in the 14 days preceding enrolment, or planned receipt of any                                               other vaccine within 14 days following each vaccination'),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='vaccine30',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1, verbose_name='Receipt of an investigational product in the 30 days preceding                                                enrolment, or planned receipt during the study period'),
        ),
        migrations.AlterField(
            model_name='exclusioncriteria',
            name='volunteers',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1, verbose_name='Volunteers unable to be closely followed for social, geographic or psychological reasons.'),
        ),
        migrations.AlterField(
            model_name='screeningtwo',
            name='health',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1, verbose_name='Has there been change in participant’s health status since last visit?'),
        ),
        migrations.AlterField(
            model_name='screeningtwo',
            name='medication',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1, verbose_name='Is the participant currently taking new medications not previously noted?'),
        ),
        migrations.AlterField(
            model_name='screeningtwo',
            name='results',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], max_length=1, verbose_name='Did you inform the participant about their results?'),
        ),
        migrations.AlterField(
            model_name='screeningtwo',
            name='sample',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No'), ('3', 'NA')], max_length=1, verbose_name='Were all requested sample collected?'),
        ),
        migrations.AlterField(
            model_name='screeningtwo',
            name='sampleNumber',
            field=models.IntegerField(verbose_name='Sample Brady Number'),
        ),
    ]
