# Generated by Django 3.1.7 on 2021-05-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_vac083', '0004_auto_20210506_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographic',
            name='race_other',
            field=models.TextField(default='', verbose_name='Specify'),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='race',
            field=models.CharField(choices=[('1', 'Africa'), ('O', 'Others')], max_length=1),
        ),
        migrations.AlterField(
            model_name='screeningtwo',
            name='additional',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No'), ('3', 'NA')], default='', max_length=20, verbose_name='Were additional OR repeat tests requested at this visit?'),
        ),
        migrations.AlterField(
            model_name='screeningtwo',
            name='additional_test',
            field=models.CharField(choices=[('1', 'Hematology'), ('2', 'Biochemistry'), ('3', 'Parasitology'), ('4', 'Urinalysis'), ('5', 'Pregnancy Test'), ('6', 'Serology'), ('7', 'Other')], default='', max_length=1, verbose_name='If “yes’ specify which tests were requested below and complete unscheduled laboratory investigation form:'),
        ),
        migrations.AlterField(
            model_name='screeningtwo',
            name='additional_test_other',
            field=models.TextField(default='', verbose_name='Specify'),
        ),
        migrations.AlterField(
            model_name='screeningtwo',
            name='bednet',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='', max_length=20, verbose_name='Did the volunteer receive an insecticide treated bed net?'),
        ),
        migrations.AlterField(
            model_name='screeningtwo',
            name='procedures',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='', max_length=1, verbose_name='Did all procedures of SC2 been completed?'),
        ),
        migrations.AlterField(
            model_name='screeningtwo',
            name='procedures_no',
            field=models.CharField(choices=[('1', 'Volunteer requires treatment before enrolment (update medical history section)'), ('2', 'Volunteer require repeat/additional sample analysis'), ('3', 'Other, please specify')], default='', max_length=25, verbose_name='If No, Tick appropriate reason.'),
        ),
        migrations.AlterField(
            model_name='screeningtwo',
            name='procedures_no_other',
            field=models.CharField(default='', max_length=25, verbose_name='If No, Specify'),
        ),
        migrations.AlterField(
            model_name='screeningtwo',
            name='reason',
            field=models.CharField(choices=[('1', 'Subject illness or injury'), ('2', 'Subject refusal'), ('3', 'Scheduling difficulties'), ('4', 'Unable to contact'), ('5', 'Transportation problems'), ('6', 'Temporarily out of study area'), ('7', 'Subject forgot'), ('8', 'Site decision/error, specify:'), ('9', 'Other, specify:')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='screeningtwo',
            name='reason_other',
            field=models.CharField(default='', max_length=25, verbose_name='Other, specify:'),
        ),
        migrations.AlterField(
            model_name='screeningtwo',
            name='referral',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='', max_length=1, verbose_name='Does volunteer require referral to another health facility for further medical care?'),
        ),
        migrations.AlterField(
            model_name='screeningtwo',
            name='referral_yes',
            field=models.TextField(choices=[('1', 'Yes'), ('2', 'No')], default='', verbose_name='If Yes, specify below and complete appropriate referral document'),
        ),
        migrations.AlterField(
            model_name='screeningtwo',
            name='site_decision',
            field=models.TextField(default='', verbose_name='Site decision/error, specify:'),
        ),
        migrations.AlterField(
            model_name='screeningtwo',
            name='visit_code',
            field=models.CharField(choices=[('1', 'sc2')], default='', max_length=1),
        ),
    ]
