# Generated by Django 3.1.7 on 2021-11-21 06:21

from django.db import migrations, models
import edcs_utils.date


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airpollutionfollowup',
            name='report_datetime',
            field=models.DateTimeField(default=edcs_utils.date.get_utcnow, help_text='Date and time of report.', verbose_name='Report Date and Time'),
        ),
        migrations.AddField(
            model_name='alcoholtobaccouse',
            name='report_datetime',
            field=models.DateTimeField(default=edcs_utils.date.get_utcnow, help_text='Date and time of report.', verbose_name='Report Date and Time'),
        ),
        migrations.AddField(
            model_name='clinicalreview',
            name='report_datetime',
            field=models.DateTimeField(default=edcs_utils.date.get_utcnow, help_text='Date and time of report.', verbose_name='Report Date and Time'),
        ),
        migrations.AddField(
            model_name='contraceptiveusereproductivehistory',
            name='report_datetime',
            field=models.DateTimeField(default=edcs_utils.date.get_utcnow, help_text='Date and time of report.', verbose_name='Report Date and Time'),
        ),
        migrations.AddField(
            model_name='cookingfuel',
            name='report_datetime',
            field=models.DateTimeField(default=edcs_utils.date.get_utcnow, help_text='Date and time of report.', verbose_name='Report Date and Time'),
        ),
        migrations.AddField(
            model_name='covidinfectionhistory',
            name='report_datetime',
            field=models.DateTimeField(default=edcs_utils.date.get_utcnow, help_text='Date and time of report.', verbose_name='Report Date and Time'),
        ),
        migrations.AddField(
            model_name='demographiccharacteristic',
            name='report_datetime',
            field=models.DateTimeField(default=edcs_utils.date.get_utcnow, help_text='Date and time of report.', verbose_name='Report Date and Time'),
        ),
        migrations.AddField(
            model_name='effectairpollution',
            name='report_datetime',
            field=models.DateTimeField(default=edcs_utils.date.get_utcnow, help_text='Date and time of report.', verbose_name='Report Date and Time'),
        ),
        migrations.AddField(
            model_name='hivlabinvestigation',
            name='report_datetime',
            field=models.DateTimeField(default=edcs_utils.date.get_utcnow, help_text='Date and time of report.', verbose_name='Report Date and Time'),
        ),
        migrations.AddField(
            model_name='homelocatorform',
            name='report_datetime',
            field=models.DateTimeField(default=edcs_utils.date.get_utcnow, help_text='Date and time of report.', verbose_name='Report Date and Time'),
        ),
        migrations.AddField(
            model_name='lungcancerlabinvestigation',
            name='report_datetime',
            field=models.DateTimeField(default=edcs_utils.date.get_utcnow, help_text='Date and time of report.', verbose_name='Report Date and Time'),
        ),
        migrations.AddField(
            model_name='lungcancertreatment',
            name='report_datetime',
            field=models.DateTimeField(default=edcs_utils.date.get_utcnow, help_text='Date and time of report.', verbose_name='Report Date and Time'),
        ),
        migrations.AddField(
            model_name='occupationalhistory',
            name='report_datetime',
            field=models.DateTimeField(default=edcs_utils.date.get_utcnow, help_text='Date and time of report.', verbose_name='Report Date and Time'),
        ),
        migrations.AddField(
            model_name='signsymptomlungcancer',
            name='report_datetime',
            field=models.DateTimeField(default=edcs_utils.date.get_utcnow, help_text='Date and time of report.', verbose_name='Report Date and Time'),
        ),
    ]
