# Generated by Django 3.1.7 on 2022-02-18 03:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edcs_subject', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalHomeLocatorForm',
            new_name='HistoricalHomeLocator',
        ),
        migrations.RenameModel(
            old_name='HomeLocatorForm',
            new_name='HomeLocator',
        ),
    ]
