# Generated by Django 3.1.7 on 2022-02-07 13:14

from django.db import migrations, models
import edcs_model.models.fields.other_charfield


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalreview',
            name='lung_cancer_dx',
        ),
        migrations.RemoveField(
            model_name='historicalclinicalreview',
            name='lung_cancer_dx',
        ),
        migrations.RemoveField(
            model_name='historicalsignsymptomlungcancer',
            name='family_member_dx_cancer',
        ),
        migrations.RemoveField(
            model_name='signsymptomlungcancer',
            name='family_member_dx_cancer',
        ),
        migrations.AddField(
            model_name='covidinfectionhistory',
            name='other_vaccine_provider',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='historicalcovidinfectionhistory',
            name='other_vaccine_provider',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='historicalsignsymptomlungcancer',
            name='chest_radiation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('decline_to_answer', 'Decline to answer')], max_length=45, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='historicalsignsymptomlungcancer',
            name='lung_cancer_dx',
            field=models.CharField(choices=[('lung_cancer_confirmed', 'Lung cancer confirmed'), ('non_cancerous', 'Non-cancerous'), ('inconclusive_results', 'Inconclusive results')], default=None, max_length=45, verbose_name='What is the patient’s lung cancer diagnosis?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsignsymptomlungcancer',
            name='no_chest_radiation',
            field=models.IntegerField(default=None, verbose_name='If yes, how many times?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsignsymptomlungcancer',
            name='what_brought_hospital_other',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='signsymptomlungcancer',
            name='chest_radiation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('decline_to_answer', 'Decline to answer')], max_length=45, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='signsymptomlungcancer',
            name='lung_cancer_dx',
            field=models.CharField(choices=[('lung_cancer_confirmed', 'Lung cancer confirmed'), ('non_cancerous', 'Non-cancerous'), ('inconclusive_results', 'Inconclusive results')], default=None, max_length=45, verbose_name='What is the patient’s lung cancer diagnosis?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signsymptomlungcancer',
            name='no_chest_radiation',
            field=models.IntegerField(default=None, verbose_name='If yes, how many times?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signsymptomlungcancer',
            name='what_brought_hospital_other',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
    ]
