# Generated by Django 3.1.7 on 2022-02-18 04:01

from django.db import migrations, models
import edcs_model.models.fields.other_charfield


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_lists', '0001_initial'),
        ('edcs_subject', '0002_auto_20220218_0326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsignsymptomlungcancer',
            name='what_brought_hospital',
        ),
        migrations.AddField(
            model_name='historicalsignsymptomlungcancer',
            name='characterize_symptoms_other',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='historicalsignsymptomlungcancer',
            name='family_member_relationship_other',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='historicalsignsymptomlungcancer',
            name='investigations_ordered_other',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='historicalsignsymptomlungcancer',
            name='symptoms_greater_than_6months',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='If greater than 6 months, Please specify'),
        ),
        migrations.AddField(
            model_name='signsymptomlungcancer',
            name='characterize_symptoms_other',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='signsymptomlungcancer',
            name='family_member_relationship_other',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='signsymptomlungcancer',
            name='investigations_ordered_other',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='signsymptomlungcancer',
            name='symptoms_greater_than_6months',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='If greater than 6 months, Please specify'),
        ),
        migrations.AlterField(
            model_name='historicalsignsymptomlungcancer',
            name='investigations_ordered',
            field=models.DateField(choices=[('blood_tests', 'Blood tests'), ('chest_xray', 'Chest X-ray'), ('ct_scan', 'CT scan'), ('lung_cancer_biopsy', 'Lung cancer biopsy'), ('sputum_tb_dx', 'Sputum for TB diagnosis'), ('OTHER', 'Others'), ('none_of_above', 'None of the above')], max_length=45, verbose_name='While at cancer treatment facility, what investigations did the doctor(s) order?'),
        ),
        migrations.AlterField(
            model_name='signsymptomlungcancer',
            name='investigations_ordered',
            field=models.DateField(choices=[('blood_tests', 'Blood tests'), ('chest_xray', 'Chest X-ray'), ('ct_scan', 'CT scan'), ('lung_cancer_biopsy', 'Lung cancer biopsy'), ('sputum_tb_dx', 'Sputum for TB diagnosis'), ('OTHER', 'Others'), ('none_of_above', 'None of the above')], max_length=45, verbose_name='While at cancer treatment facility, what investigations did the doctor(s) order?'),
        ),
        migrations.RemoveField(
            model_name='signsymptomlungcancer',
            name='what_brought_hospital',
        ),
        migrations.AddField(
            model_name='signsymptomlungcancer',
            name='what_brought_hospital',
            field=models.ManyToManyField(related_name='lung_cancer_symptoms', to='edcs_lists.LungCancerSymptoms', verbose_name='What brought you to the hospital that made the doctors suspect/diagnose you to have lung cancer?'),
        ),
    ]
