# Generated by Django 3.1.7 on 2022-05-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0002_auto_20220225_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographiccharacteristic',
            name='martial_status',
            field=models.CharField(choices=[('married', 'Married'), ('cohabiting', 'Cohabiting'), ('single', 'Single'), ('divorced_separated', 'Divorced/Separated'), ('widow_widower', 'Widow/Widower')], max_length=45, verbose_name='Marital status?'),
        ),
        migrations.AlterField(
            model_name='historicaldemographiccharacteristic',
            name='martial_status',
            field=models.CharField(choices=[('married', 'Married'), ('cohabiting', 'Cohabiting'), ('single', 'Single'), ('divorced_separated', 'Divorced/Separated'), ('widow_widower', 'Widow/Widower')], max_length=45, verbose_name='Marital status?'),
        ),
    ]
