# Generated by Django 3.1.7 on 2022-02-08 01:01

from django.db import migrations
import edcs_model.models.fields.other_charfield


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0002_auto_20220207_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaloccupationalhistory',
            old_name='industries_worked_on',
            new_name='industries_worked',
        ),
        migrations.RenameField(
            model_name='occupationalhistory',
            old_name='industries_worked_on',
            new_name='industries_worked',
        ),
        migrations.AddField(
            model_name='historicaloccupationalhistory',
            name='industries_worked_other',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='occupationalhistory',
            name='industries_worked_other',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
    ]
