# Generated by Django 3.1.7 on 2021-11-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0003_housekitchensurrounding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airpollutionfollowup',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import'), 'get_latest_by': 'modified', 'ordering': ('-modified', '-created'), 'verbose_name': 'Air Pollution Follow Up', 'verbose_name_plural': 'Air Pollution Follow Up'},
        ),
        migrations.AlterModelOptions(
            name='demographiccharacteristic',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import'), 'get_latest_by': 'modified', 'ordering': ('-modified', '-created'), 'verbose_name': 'Demographic and Socio-Economic Characteristics', 'verbose_name_plural': 'Demographic and Socio-Economic Characteristics'},
        ),
        migrations.AlterField(
            model_name='clinicalreview',
            name='arv',
            field=models.CharField(choices=[('POS', 'HIV Positive '), ('NEG', 'HIV Negative'), ('decline_to_answer', 'Decline to answer'), ('dont_know', 'I dont know')], default=None, max_length=45, verbose_name='If positive, are you taking ARVs?'),
        ),
        migrations.AlterField(
            model_name='clinicalreview',
            name='arv_regularly',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=15, verbose_name='Do you take your ARVs regularly? '),
        ),
        migrations.AlterField(
            model_name='clinicalreview',
            name='hiv_dx',
            field=models.CharField(choices=[('POS', 'HIV Positive '), ('NEG', 'HIV Negative'), ('decline_to_answer', 'Decline to answer'), ('dont_know', 'I dont know')], default=None, max_length=45, verbose_name='What was the result of your most recent HIV test?'),
        ),
        migrations.AlterField(
            model_name='clinicalreview',
            name='miss_taking_arv',
            field=models.CharField(choices=[('at_least_once_every_week', 'At least once every week'), ('at_least_once_a_month', 'At least once in a month'), ('at_least_once_3_months', 'At least once in 3 months'), ('at_least_once_a_year', 'At least once a year'), ('dont_remember', 'I Do not remember'), ('others', 'Other')], default=None, max_length=45, verbose_name='If no, how often do you miss taking ARVs?'),
        ),
        migrations.AlterField(
            model_name='clinicalreview',
            name='use_lung_diseases_medication',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('decline_to_answer', 'Decline to answer')], default=None, max_length=80, verbose_name='Are you using any medications?'),
        ),
    ]
