# Generated by Django 3.1.7 on 2022-02-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0003_auto_20220218_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsignsymptomlungcancer',
            name='characterize_symptoms',
            field=models.CharField(choices=[('sudden_onset', 'Sudden onset'), ('gradual_onset', 'Gradual onset'), ('progressive_severity', 'Progressive in severity'), ('intermittent_severity', 'Intermittent in severity'), ('OTHER', 'Others')], max_length=45, verbose_name='How would you characterize your symptoms?'),
        ),
        migrations.AlterField(
            model_name='historicalsignsymptomlungcancer',
            name='chest_radiation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('decline_to_answer', 'Decline to answer')], max_length=45, null=True, verbose_name='Do you have history of chest radiation in the past 5 years?'),
        ),
        migrations.AlterField(
            model_name='historicalsignsymptomlungcancer',
            name='no_chest_radiation',
            field=models.IntegerField(blank=True, null=True, verbose_name='If yes, how many times?'),
        ),
        migrations.AlterField(
            model_name='signsymptomlungcancer',
            name='characterize_symptoms',
            field=models.CharField(choices=[('sudden_onset', 'Sudden onset'), ('gradual_onset', 'Gradual onset'), ('progressive_severity', 'Progressive in severity'), ('intermittent_severity', 'Intermittent in severity'), ('OTHER', 'Others')], max_length=45, verbose_name='How would you characterize your symptoms?'),
        ),
        migrations.AlterField(
            model_name='signsymptomlungcancer',
            name='chest_radiation',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('decline_to_answer', 'Decline to answer')], max_length=45, null=True, verbose_name='Do you have history of chest radiation in the past 5 years?'),
        ),
        migrations.AlterField(
            model_name='signsymptomlungcancer',
            name='no_chest_radiation',
            field=models.IntegerField(blank=True, null=True, verbose_name='If yes, how many times?'),
        ),
    ]
