# Generated by Django 3.1.7 on 2022-05-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0003_auto_20220505_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographiccharacteristic',
            name='occupation',
            field=models.CharField(choices=[('civil_servant', 'Civil Servant'), ('house_wife', 'House wife'), ('peasant', 'Peasant'), ('petty_trader', 'Petty trader'), ('entrepreneur', 'Entrepreneur'), ('unemployed', 'Unemployed'), ('business_man', 'Business man/woman'), ('casual_laborers', 'Casual laborers'), ('OTHER', 'Other')], max_length=45, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='historicaldemographiccharacteristic',
            name='occupation',
            field=models.CharField(choices=[('civil_servant', 'Civil Servant'), ('house_wife', 'House wife'), ('peasant', 'Peasant'), ('petty_trader', 'Petty trader'), ('entrepreneur', 'Entrepreneur'), ('unemployed', 'Unemployed'), ('business_man', 'Business man/woman'), ('casual_laborers', 'Casual laborers'), ('OTHER', 'Other')], max_length=45, verbose_name='Occupation'),
        ),
    ]
