# Generated by Django 3.1.7 on 2022-02-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0003_auto_20220215_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalreview',
            name='arv',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If positive, are you taking ARVs?'),
        ),
        migrations.AlterField(
            model_name='historicalclinicalreview',
            name='arv',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If positive, are you taking ARVs?'),
        ),
    ]
