# Generated by Django 3.1.7 on 2022-02-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0004_auto_20220215_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalreview',
            name='hiv_dx',
            field=models.CharField(choices=[('POS', 'HIV Positive '), ('NEG', 'HIV Negative'), ('decline_to_answer', 'Decline to answer'), ('dont_know', 'I dont know'), ('N/A', 'Not applicable')], default=None, max_length=45, verbose_name='What was the result of your most recent HIV test?'),
        ),
        migrations.AlterField(
            model_name='historicalclinicalreview',
            name='hiv_dx',
            field=models.CharField(choices=[('POS', 'HIV Positive '), ('NEG', 'HIV Negative'), ('decline_to_answer', 'Decline to answer'), ('dont_know', 'I dont know'), ('N/A', 'Not applicable')], default=None, max_length=45, verbose_name='What was the result of your most recent HIV test?'),
        ),
    ]
