# Generated by Django 3.1.7 on 2021-11-30 13:26

import uuid

import _socket
import django.db.models.deletion
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_audit_fields.models.audit_model_mixin
import django_revision.revision_field
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import edcs_model.models.fields.other_charfield
import edcs_utils.date


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("edcs_subject", "0004_auto_20211129_1523"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalClinicalReview",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True,
                        default=django_audit_fields.models.audit_model_mixin.utcnow,
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True,
                        default=django_audit_fields.models.audit_model_mixin.utcnow,
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                    ),
                ),
                ("device_created", models.CharField(blank=True, max_length=10)),
                ("device_modified", models.CharField(blank=True, max_length=10)),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_datetime",
                    models.DateTimeField(
                        default=edcs_utils.date.get_utcnow,
                        help_text="Date and time of report.",
                        verbose_name="Report Date and Time",
                    ),
                ),
                (
                    "hiv_test",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("decline_to_answer", "Decline to answer"),
                            ("dont_know", "Do not know"),
                        ],
                        max_length=45,
                        verbose_name="Have you ever been tested for HIV?",
                    ),
                ),
                (
                    "hiv_test_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="If yes, when was your most recent HIV test?",
                    ),
                ),
                (
                    "hiv_dx",
                    models.CharField(
                        choices=[
                            ("POS", "HIV Positive "),
                            ("NEG", "HIV Negative"),
                            ("decline_to_answer", "Decline to answer"),
                            ("dont_know", "I dont know"),
                        ],
                        default=None,
                        max_length=45,
                        verbose_name="What was the result of your most recent HIV test?",
                    ),
                ),
                (
                    "arv",
                    models.CharField(
                        choices=[
                            ("POS", "HIV Positive "),
                            ("NEG", "HIV Negative"),
                            ("decline_to_answer", "Decline to answer"),
                            ("dont_know", "I dont know"),
                        ],
                        default=None,
                        max_length=45,
                        verbose_name="If positive, are you taking ARVs?",
                    ),
                ),
                (
                    "arv_start_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Month and year patient started taking ARVs?",
                    ),
                ),
                (
                    "arv_regularly",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        default=None,
                        max_length=15,
                        verbose_name="Do you take your ARVs regularly? ",
                    ),
                ),
                (
                    "miss_taking_arv",
                    models.CharField(
                        choices=[
                            ("at_least_once_every_week", "At least once every week"),
                            ("at_least_once_a_month", "At least once in a month"),
                            ("at_least_once_3_months", "At least once in 3 months"),
                            ("at_least_once_a_year", "At least once a year"),
                            ("dont_remember", "I Do not remember"),
                            ("others", "Other"),
                        ],
                        default=None,
                        max_length=45,
                        verbose_name="If no, how often do you miss taking ARVs?",
                    ),
                ),
                (
                    "miss_taking_arv_other",
                    edcs_model.models.fields.other_charfield.OtherCharField(
                        blank=True,
                        max_length=35,
                        null=True,
                        verbose_name="If other, please specify ...",
                    ),
                ),
                (
                    "lung_diseases_dx",
                    models.CharField(
                        choices=[
                            ("yes_copd", "Yes, COPD"),
                            ("yes_asthma", "Yes, Asthma"),
                            (
                                "yes_interstitial_lung_disease",
                                "Yes, Interstitial Lung Disease",
                            ),
                            ("No", "No"),
                            ("decline_to_answer", "Decline to answer"),
                            ("Dont_know", "Do not know"),
                        ],
                        max_length=45,
                        verbose_name="Have you ever been diagnosed with a chronic lung disease like Asthma, COPD, and Interstitial lung disease?",
                    ),
                ),
                (
                    "lung_diseases_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="If yes, when were you diagnosed?",
                    ),
                ),
                (
                    "use_lung_diseases_medication",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("decline_to_answer", "Decline to answer"),
                        ],
                        default=None,
                        max_length=80,
                        verbose_name="Are you using any medications?",
                    ),
                ),
                (
                    "lung_diseases_medication",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="If is yes, what medications are you using?",
                    ),
                ),
                (
                    "htn_dx",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=45,
                        verbose_name="Have you ever been diagnosed with Hypertension?",
                    ),
                ),
                (
                    "htn_dx_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="If yes, when were you diagnosed?",
                    ),
                ),
                (
                    "use_htn_medication",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("decline_to_answer", "Decline to answer"),
                        ],
                        max_length=45,
                        verbose_name="Have you ever been diagnosed with Hypertension?",
                    ),
                ),
                (
                    "htn_medication",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="If is yes, what medications are you using currently?",
                    ),
                ),
                (
                    "dm_dx",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=15,
                        verbose_name="Have you ever been diagnosed with have Diabetes Mellitus? ",
                    ),
                ),
                (
                    "dm_dx_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="If yes, when were you diagnosed?",
                    ),
                ),
                (
                    "use_dm_medication",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("decline_to_answer", "Decline to answer"),
                        ],
                        max_length=45,
                        verbose_name="Have you ever been diagnosed with Hypertension?",
                    ),
                ),
                (
                    "dm_medication",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="If is yes, what medications are you using currently?",
                    ),
                ),
                (
                    "malignancy",
                    models.CharField(
                        choices=[
                            ("Yes", "Yes"),
                            ("No", "No"),
                            ("decline_to_answer", "Decline to answer"),
                            ("dont_know", "Do not know"),
                        ],
                        max_length=45,
                        verbose_name="Have you ever had any other malignancy?",
                    ),
                ),
                (
                    "tb_test",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=45,
                        verbose_name="Were you tested for TB?",
                    ),
                ),
                (
                    "provide_sputum_tb_dx",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no_declined", "No, declined"),
                            ("no_sputum", "No sputum"),
                        ],
                        max_length=45,
                        verbose_name="If No, has the patient provided sputum for TB diagnosis?",
                    ),
                ),
                (
                    "tb_status",
                    models.CharField(
                        choices=[
                            ("tb_positive", "TB positive"),
                            ("tb_negative", "TB negative (No TB)"),
                            ("inconclusive_results", "Inconclusive results"),
                        ],
                        max_length=45,
                        verbose_name="What is the patients TB status?",
                    ),
                ),
                (
                    "lung_cancer_dx",
                    models.CharField(
                        choices=[
                            ("lung_cancer_confirmed", "Lung cancer confirmed"),
                            ("non_cancerous", "Non-cancerous"),
                            ("inconclusive_results", "Inconclusive results"),
                        ],
                        max_length=45,
                        verbose_name="What is the patient’s lung cancer diagnosis?",
                    ),
                ),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Clinical Review",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
