# Generated by Django 3.1.7 on 2022-02-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0004_auto_20220218_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsignsymptomlungcancer',
            name='family_member_relationship',
            field=models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('brother', 'Brother'), ('sister', 'Sister'), ('grandparent_mother_side', 'Grandparent from mother’s side'), ('grandparent_father_side', 'Grandparent from father’s side'), ('N/A', 'Not applicable'), ('OTHER', 'Others')], default='N/A', max_length=45, verbose_name='If yes, what is your relationship with the above-mentioned person?'),
        ),
        migrations.AlterField(
            model_name='signsymptomlungcancer',
            name='family_member_relationship',
            field=models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('brother', 'Brother'), ('sister', 'Sister'), ('grandparent_mother_side', 'Grandparent from mother’s side'), ('grandparent_father_side', 'Grandparent from father’s side'), ('N/A', 'Not applicable'), ('OTHER', 'Others')], default='N/A', max_length=45, verbose_name='If yes, what is your relationship with the above-mentioned person?'),
        ),
    ]
