# Generated by Django 3.1.7 on 2022-02-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_lists', '0002_auto_20220208_0341'),
        ('edcs_subject', '0004_auto_20220208_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcancerhistory',
            name='breast_cancer_family_member',
        ),
        migrations.RemoveField(
            model_name='historicalcancerhistory',
            name='colon_cancer_family_member',
        ),
        migrations.RemoveField(
            model_name='historicalcancerhistory',
            name='lung_cancer_family_member',
        ),
        migrations.RemoveField(
            model_name='historicalcancerhistory',
            name='ovarian_cancer_family_member',
        ),
        migrations.RemoveField(
            model_name='historicalcancerhistory',
            name='prostate_cancer_family_member',
        ),
        migrations.RemoveField(
            model_name='historicalcancerhistory',
            name='thyroid_cancer_family_member',
        ),
        migrations.RemoveField(
            model_name='historicalcancerhistory',
            name='uterine_cancer_family_member',
        ),
        migrations.RemoveField(
            model_name='cancerhistory',
            name='breast_cancer_family_member',
        ),
        migrations.AddField(
            model_name='cancerhistory',
            name='breast_cancer_family_member',
            field=models.ManyToManyField(related_name='breast_cancer_family_member', to='edcs_lists.FamilyMembers', verbose_name='What is your relationship?'),
        ),
        migrations.RemoveField(
            model_name='cancerhistory',
            name='colon_cancer_family_member',
        ),
        migrations.AddField(
            model_name='cancerhistory',
            name='colon_cancer_family_member',
            field=models.ManyToManyField(related_name='colon_cancer_family_member', to='edcs_lists.FamilyMembers', verbose_name='What is your relationship?'),
        ),
        migrations.RemoveField(
            model_name='cancerhistory',
            name='lung_cancer_family_member',
        ),
        migrations.AddField(
            model_name='cancerhistory',
            name='lung_cancer_family_member',
            field=models.ManyToManyField(related_name='lung_cancer_family_member', to='edcs_lists.FamilyMembers', verbose_name='What is your relationship?'),
        ),
        migrations.RemoveField(
            model_name='cancerhistory',
            name='ovarian_cancer_family_member',
        ),
        migrations.AddField(
            model_name='cancerhistory',
            name='ovarian_cancer_family_member',
            field=models.ManyToManyField(related_name='ovarian_cancer_family_member', to='edcs_lists.FamilyMembers', verbose_name='What is your relationship?'),
        ),
        migrations.RemoveField(
            model_name='cancerhistory',
            name='prostate_cancer_family_member',
        ),
        migrations.AddField(
            model_name='cancerhistory',
            name='prostate_cancer_family_member',
            field=models.ManyToManyField(related_name='prostate_cancer_family_member', to='edcs_lists.FamilyMembers', verbose_name='What is your relationship?'),
        ),
        migrations.RemoveField(
            model_name='cancerhistory',
            name='thyroid_cancer_family_member',
        ),
        migrations.AddField(
            model_name='cancerhistory',
            name='thyroid_cancer_family_member',
            field=models.ManyToManyField(related_name='thyroid_cancer_family_member', to='edcs_lists.FamilyMembers', verbose_name='What is your relationship?'),
        ),
        migrations.RemoveField(
            model_name='cancerhistory',
            name='uterine_cancer_family_member',
        ),
        migrations.AddField(
            model_name='cancerhistory',
            name='uterine_cancer_family_member',
            field=models.ManyToManyField(related_name='uterine_cancer_family_member', to='edcs_lists.FamilyMembers', verbose_name='What is your relationship?'),
        ),
    ]
