# Generated by Django 3.1.7 on 2022-05-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0004_auto_20220505_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographiccharacteristic',
            name='an_iron',
            field=models.CharField(choices=[('yes_electrical', 'Yes electrical'), ('yes_charcoal_iron', 'Yes charcoal iron'), ('no', 'No')], max_length=45, verbose_name='Do you have an Iron in your household?'),
        ),
        migrations.AlterField(
            model_name='historicaldemographiccharacteristic',
            name='an_iron',
            field=models.CharField(choices=[('yes_electrical', 'Yes electrical'), ('yes_charcoal_iron', 'Yes charcoal iron'), ('no', 'No')], max_length=45, verbose_name='Do you have an Iron in your household?'),
        ),
    ]
