# Generated by Django 3.1.7 on 2022-02-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_lists', '0002_auto_20220208_0341'),
        ('edcs_subject', '0005_auto_20220208_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcovidinfectionhistory',
            name='covid_symptoms',
        ),
        migrations.RemoveField(
            model_name='covidinfectionhistory',
            name='covid_symptoms',
        ),
        migrations.AddField(
            model_name='covidinfectionhistory',
            name='covid_symptoms',
            field=models.ManyToManyField(related_name='covid_symptoms', to='edcs_lists.CovidSymptoms', verbose_name='If yes, what symptoms did you have when you first had COVID-19?'),
        ),
    ]
