# Generated by Django 3.1.7 on 2022-05-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0005_auto_20220505_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographiccharacteristic',
            name='bank_account',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15, verbose_name='Does anyone in your household own a bank account/mobile money/microfinance?'),
        ),
        migrations.AlterField(
            model_name='historicaldemographiccharacteristic',
            name='bank_account',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15, verbose_name='Does anyone in your household own a bank account/mobile money/microfinance?'),
        ),
    ]
