# Generated by Django 3.1.7 on 2022-05-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0006_auto_20220505_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographiccharacteristic',
            name='main_power_source',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('battery_torch', 'Battery/ torch '), ('solar_energy', 'Solar energy'), ('kerosene', 'Kerosene'), ('OTHER', 'Others')], max_length=15, verbose_name='What is the main source of power lighting in your household?'),
        ),
        migrations.AlterField(
            model_name='historicaldemographiccharacteristic',
            name='main_power_source',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('battery_torch', 'Battery/ torch '), ('solar_energy', 'Solar energy'), ('kerosene', 'Kerosene'), ('OTHER', 'Others')], max_length=15, verbose_name='What is the main source of power lighting in your household?'),
        ),
    ]
