# Generated by Django 3.1.7 on 2022-02-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0006_auto_20220215_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalreview',
            name='arv_regularly',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=15, verbose_name='Do you take your ARVs regularly? '),
        ),
        migrations.AlterField(
            model_name='clinicalreview',
            name='miss_taking_arv',
            field=models.CharField(choices=[('at_least_once_every_week', 'At least once every week'), ('at_least_once_a_month', 'At least once in a month'), ('at_least_once_3_months', 'At least once in 3 months'), ('at_least_once_a_year', 'At least once a year'), ('dont_remember', 'I Do not remember'), ('OTHER', 'Other'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If no, how often do you miss taking ARVs?'),
        ),
        migrations.AlterField(
            model_name='historicalclinicalreview',
            name='arv_regularly',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=15, verbose_name='Do you take your ARVs regularly? '),
        ),
        migrations.AlterField(
            model_name='historicalclinicalreview',
            name='miss_taking_arv',
            field=models.CharField(choices=[('at_least_once_every_week', 'At least once every week'), ('at_least_once_a_month', 'At least once in a month'), ('at_least_once_3_months', 'At least once in 3 months'), ('at_least_once_a_year', 'At least once a year'), ('dont_remember', 'I Do not remember'), ('OTHER', 'Other'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If no, how often do you miss taking ARVs?'),
        ),
    ]
