# Generated by Django 3.1.7 on 2022-02-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0007_auto_20220218_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloccupationalhistory',
            name='how_long_work_mine',
            field=models.CharField(choices=[('less_than_5yrs', '≤ 5 years'), ('greater_than_5yrs', '≥ 5 years'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If yes, for how long have worked in the mines?'),
        ),
        migrations.AlterField(
            model_name='historicaloccupationalhistory',
            name='industries_worked',
            field=models.CharField(choices=[('textile_industry', 'Textile industry'), ('chemical_production_industry', 'Chemical production industry'), ('food_processing_industry', 'Food processing industry'), ('drug_industry', 'Drug industry'), ('milling_industry', 'Milling industry'), ('construction_industry', 'Construction industry'), ('N/A', 'Not applicable'), ('OTHER', 'Other')], default='N/A', max_length=45, verbose_name='If yes, what kind of industry did you work?'),
        ),
        migrations.AlterField(
            model_name='occupationalhistory',
            name='how_long_work_mine',
            field=models.CharField(choices=[('less_than_5yrs', '≤ 5 years'), ('greater_than_5yrs', '≥ 5 years'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If yes, for how long have worked in the mines?'),
        ),
        migrations.AlterField(
            model_name='occupationalhistory',
            name='industries_worked',
            field=models.CharField(choices=[('textile_industry', 'Textile industry'), ('chemical_production_industry', 'Chemical production industry'), ('food_processing_industry', 'Food processing industry'), ('drug_industry', 'Drug industry'), ('milling_industry', 'Milling industry'), ('construction_industry', 'Construction industry'), ('N/A', 'Not applicable'), ('OTHER', 'Other')], default='N/A', max_length=45, verbose_name='If yes, what kind of industry did you work?'),
        ),
    ]
