# Generated by Django 3.1.7 on 2022-02-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0007_auto_20220215_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airpollutionfollowup',
            name='fuel_before_changing',
            field=models.CharField(choices=[('kerosene_stove', 'Kerosene stove'), ('gas_stove', 'Gas stove'), ('open_fire', 'Open fire'), ('open_fire_stove', 'Open fire or stove with chimney or hood'), ('close_stove', 'Closed stove with chimney'), ('electric_heaters', 'Electric heaters'), ('OTHER', 'Other')], max_length=125, verbose_name='What type of stove did you use for cooking since we visited your home yesterday?'),
        ),
        migrations.AlterField(
            model_name='airpollutionfollowup',
            name='who_had_illness',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('lpg_natural_gas ', 'LPG/Natural gas '), ('biogas ', 'Biogas '), ('kerosene', 'Kerosene'), ('coal_lignite', 'Coal/lignite'), ('charcoal', 'Charcoal'), ('wood', 'Wood'), ('straw_shrubs_grass ', 'Straw/shrubs/grass '), ('agricultural_crop', 'Agricultural crop'), ('animal_dung', 'Animal dung'), ('OTHER', 'Other')], max_length=45, verbose_name='What type of fuel did you use for cooking since we visited your home yesterday'),
        ),
        migrations.AlterField(
            model_name='alcoholtobaccouse',
            name='alcohol_consumption_frequency',
            field=models.CharField(choices=[('daily', '1-Daily'), ('every_other_day', 'Every other day'), ('weekly', 'Weekly (Not daily )'), ('monthly', 'Monthly (Not weekly)'), ('OTHER', 'Others')], max_length=45, verbose_name='How frequently do you consume alcohol?'),
        ),
        migrations.AlterField(
            model_name='alcoholtobaccouse',
            name='smoke_inside_house',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('less_than_monthly', 'Less than monthly'), ('never', 'Never'), ('OTHER', 'Others')], max_length=45, verbose_name='How often does anyone smoke inside your house?'),
        ),
        migrations.AlterField(
            model_name='alcoholtobaccouse',
            name='smoking_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('every_other_day', 'Every other day'), ('weekly', 'Weekly (Not daily)'), ('monthly', 'Monthly(Not weekly)'), ('OTHER', 'Others')], max_length=45, verbose_name='How frequently do you smoke these products?'),
        ),
        migrations.AlterField(
            model_name='clinicalreview',
            name='lung_diseases_dx',
            field=models.CharField(choices=[('yes_copd', 'Yes, COPD'), ('yes_asthma', 'Yes, Asthma'), ('yes_interstitial_lung_disease', 'Yes, Interstitial Lung Disease'), ('No', 'No'), ('decline_to_answer', 'Decline to answer'), ('dont_know', 'Do not know')], max_length=45, verbose_name='Have you ever been diagnosed with a chronic lung disease like Asthma, COPD, and Interstitial lung disease?'),
        ),
        migrations.AlterField(
            model_name='clinicalreview',
            name='use_lung_diseases_medication',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('decline_to_answer', 'Decline to answer'), ('N/A', 'Not applicable')], default='N/A', max_length=80, verbose_name='Are you using any medications?'),
        ),
        migrations.AlterField(
            model_name='cookingfuel',
            name='cooking_done',
            field=models.CharField(choices=[('in_house', 'In the house'), ('separate_building', 'In a separate building'), ('outdoors', 'Outdoors'), ('OTHER', 'Other')], max_length=45, verbose_name='Where is the cooking usually done?'),
        ),
        migrations.AlterField(
            model_name='cookingfuel',
            name='main_use_cooking',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('lpg_natural_gas ', 'LPG/Natural gas '), ('biogas ', 'Biogas '), ('kerosene', 'Kerosene'), ('coal_lignite', 'Coal/lignite'), ('charcoal', 'Charcoal'), ('wood', 'Wood'), ('straw_shrubs_grass ', 'Straw/shrubs/grass '), ('agricultural_crop', 'Agricultural crop'), ('animal_dung', 'Animal dung'), ('OTHER', 'Other'), ('no_food_cooked', 'No food cooked in household')], max_length=45, verbose_name='What type of fuel does your household MAINLY use for cooking?'),
        ),
        migrations.AlterField(
            model_name='cookingfuel',
            name='neighbor_use_cooking',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('lpg_natural_gas ', 'LPG/Natural gas '), ('biogas ', 'Biogas '), ('kerosene', 'Kerosene'), ('coal_lignite', 'Coal/lignite'), ('charcoal', 'Charcoal'), ('wood', 'Wood'), ('straw_shrubs_grass ', 'Straw/shrubs/grass '), ('agricultural_crop', 'Agricultural crop'), ('animal_dung', 'Animal dung'), ('OTHER', 'Other'), ('dont_know', 'I dont know')], max_length=45, verbose_name='What is the MAIN type of fuel that most of your neighbors use?'),
        ),
        migrations.AlterField(
            model_name='covidinfectionhistory',
            name='vaccine_provider',
            field=models.CharField(choices=[('government_uganda', 'Government of Uganda'), ('research_study', 'Research study/trial '), ('OTHER', 'Others')], max_length=45, verbose_name='If Yes who provided the vaccine'),
        ),
        migrations.AlterField(
            model_name='demographiccharacteristic',
            name='education',
            field=models.DateField(choices=[('never_been_in_school', 'Never been in school'), ('primary_education', 'Completed Primary Education'), ('secondary_education', 'Completed Secondary Education (‘’O’’ or ‘’A’’ level)'), ('vocational_training', 'Vocational training'), ('tertiary_education', 'Tertiary Education'), ('OTHER', 'Other')], max_length=45, verbose_name='Education level?'),
        ),
        migrations.AlterField(
            model_name='demographiccharacteristic',
            name='main_power_source',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('battery_torch', 'Battery/ torch '), ('solar_energy', 'Solar energy'), ('OTHER', 'Others')], max_length=15, verbose_name='What is the main source of power in your household?'),
        ),
        migrations.AlterField(
            model_name='demographiccharacteristic',
            name='material_build_floor',
            field=models.CharField(choices=[('soil_sand_mud', 'Soil/ sand/ mud'), ('cement_concrete_tiles', 'Cement/ concrete/ tiles'), ('OTHER', 'Others')], max_length=45, verbose_name='Which materials were used to build the floor in your house?'),
        ),
        migrations.AlterField(
            model_name='demographiccharacteristic',
            name='material_build_walls',
            field=models.CharField(choices=[('soil_sand_mud', 'There is no wall'), ('cement_concrete_tiles', 'Grass'), ('other', 'Canes/ Palm'), ('trees_mud', 'Trees and mud'), ('stone_mud', 'Stones and mud'), ('wood_timber', 'Wood/timber'), ('cement_concrete_bricks', 'Cement/ concrete blocks/ burnt blocks/bricks.'), ('OTHER', 'Others')], max_length=45, verbose_name='Which materials were used to build the walls of your house?'),
        ),
        migrations.AlterField(
            model_name='demographiccharacteristic',
            name='occupation',
            field=models.CharField(choices=[('civil_servant', 'Civil Servant'), ('house_wife', 'House wife'), ('peasant', 'Peasant'), ('petty_trader', 'Petty trader'), ('entrepreneur', 'Entrepreneur'), ('unemployed', 'Unemployed'), ('business_man', 'Business man/woman'), ('OTHER', 'Other')], max_length=45, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='demographiccharacteristic',
            name='use_in_cooking',
            field=models.CharField(choices=[('electricity_stove', 'Electricity stove'), ('gas_stove', 'Gas stove'), ('kerosene_stove', 'Kerosene stove'), ('charcoal', 'Charcoal'), ('logs_woods', 'Logs/woods'), ('grass_leaves', 'Grass/leaves'), ('animal_waste', 'Animal waste'), ('plants_waste', 'Plants waste'), ('dont_cook', 'We do not cook'), ('OTHER', 'Others')], max_length=45, verbose_name='What does your household use in cooking regularly? '),
        ),
        migrations.AlterField(
            model_name='historicalairpollutionfollowup',
            name='fuel_before_changing',
            field=models.CharField(choices=[('kerosene_stove', 'Kerosene stove'), ('gas_stove', 'Gas stove'), ('open_fire', 'Open fire'), ('open_fire_stove', 'Open fire or stove with chimney or hood'), ('close_stove', 'Closed stove with chimney'), ('electric_heaters', 'Electric heaters'), ('OTHER', 'Other')], max_length=125, verbose_name='What type of stove did you use for cooking since we visited your home yesterday?'),
        ),
        migrations.AlterField(
            model_name='historicalairpollutionfollowup',
            name='who_had_illness',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('lpg_natural_gas ', 'LPG/Natural gas '), ('biogas ', 'Biogas '), ('kerosene', 'Kerosene'), ('coal_lignite', 'Coal/lignite'), ('charcoal', 'Charcoal'), ('wood', 'Wood'), ('straw_shrubs_grass ', 'Straw/shrubs/grass '), ('agricultural_crop', 'Agricultural crop'), ('animal_dung', 'Animal dung'), ('OTHER', 'Other')], max_length=45, verbose_name='What type of fuel did you use for cooking since we visited your home yesterday'),
        ),
        migrations.AlterField(
            model_name='historicalalcoholtobaccouse',
            name='alcohol_consumption_frequency',
            field=models.CharField(choices=[('daily', '1-Daily'), ('every_other_day', 'Every other day'), ('weekly', 'Weekly (Not daily )'), ('monthly', 'Monthly (Not weekly)'), ('OTHER', 'Others')], max_length=45, verbose_name='How frequently do you consume alcohol?'),
        ),
        migrations.AlterField(
            model_name='historicalalcoholtobaccouse',
            name='smoke_inside_house',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('less_than_monthly', 'Less than monthly'), ('never', 'Never'), ('OTHER', 'Others')], max_length=45, verbose_name='How often does anyone smoke inside your house?'),
        ),
        migrations.AlterField(
            model_name='historicalalcoholtobaccouse',
            name='smoking_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('every_other_day', 'Every other day'), ('weekly', 'Weekly (Not daily)'), ('monthly', 'Monthly(Not weekly)'), ('OTHER', 'Others')], max_length=45, verbose_name='How frequently do you smoke these products?'),
        ),
        migrations.AlterField(
            model_name='historicalclinicalreview',
            name='lung_diseases_dx',
            field=models.CharField(choices=[('yes_copd', 'Yes, COPD'), ('yes_asthma', 'Yes, Asthma'), ('yes_interstitial_lung_disease', 'Yes, Interstitial Lung Disease'), ('No', 'No'), ('decline_to_answer', 'Decline to answer'), ('dont_know', 'Do not know')], max_length=45, verbose_name='Have you ever been diagnosed with a chronic lung disease like Asthma, COPD, and Interstitial lung disease?'),
        ),
        migrations.AlterField(
            model_name='historicalclinicalreview',
            name='use_lung_diseases_medication',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('decline_to_answer', 'Decline to answer'), ('N/A', 'Not applicable')], default='N/A', max_length=80, verbose_name='Are you using any medications?'),
        ),
        migrations.AlterField(
            model_name='historicalcookingfuel',
            name='cooking_done',
            field=models.CharField(choices=[('in_house', 'In the house'), ('separate_building', 'In a separate building'), ('outdoors', 'Outdoors'), ('OTHER', 'Other')], max_length=45, verbose_name='Where is the cooking usually done?'),
        ),
        migrations.AlterField(
            model_name='historicalcookingfuel',
            name='main_use_cooking',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('lpg_natural_gas ', 'LPG/Natural gas '), ('biogas ', 'Biogas '), ('kerosene', 'Kerosene'), ('coal_lignite', 'Coal/lignite'), ('charcoal', 'Charcoal'), ('wood', 'Wood'), ('straw_shrubs_grass ', 'Straw/shrubs/grass '), ('agricultural_crop', 'Agricultural crop'), ('animal_dung', 'Animal dung'), ('OTHER', 'Other'), ('no_food_cooked', 'No food cooked in household')], max_length=45, verbose_name='What type of fuel does your household MAINLY use for cooking?'),
        ),
        migrations.AlterField(
            model_name='historicalcookingfuel',
            name='neighbor_use_cooking',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('lpg_natural_gas ', 'LPG/Natural gas '), ('biogas ', 'Biogas '), ('kerosene', 'Kerosene'), ('coal_lignite', 'Coal/lignite'), ('charcoal', 'Charcoal'), ('wood', 'Wood'), ('straw_shrubs_grass ', 'Straw/shrubs/grass '), ('agricultural_crop', 'Agricultural crop'), ('animal_dung', 'Animal dung'), ('OTHER', 'Other'), ('dont_know', 'I dont know')], max_length=45, verbose_name='What is the MAIN type of fuel that most of your neighbors use?'),
        ),
        migrations.AlterField(
            model_name='historicalcovidinfectionhistory',
            name='vaccine_provider',
            field=models.CharField(choices=[('government_uganda', 'Government of Uganda'), ('research_study', 'Research study/trial '), ('OTHER', 'Others')], max_length=45, verbose_name='If Yes who provided the vaccine'),
        ),
        migrations.AlterField(
            model_name='historicaldemographiccharacteristic',
            name='education',
            field=models.DateField(choices=[('never_been_in_school', 'Never been in school'), ('primary_education', 'Completed Primary Education'), ('secondary_education', 'Completed Secondary Education (‘’O’’ or ‘’A’’ level)'), ('vocational_training', 'Vocational training'), ('tertiary_education', 'Tertiary Education'), ('OTHER', 'Other')], max_length=45, verbose_name='Education level?'),
        ),
        migrations.AlterField(
            model_name='historicaldemographiccharacteristic',
            name='main_power_source',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('battery_torch', 'Battery/ torch '), ('solar_energy', 'Solar energy'), ('OTHER', 'Others')], max_length=15, verbose_name='What is the main source of power in your household?'),
        ),
        migrations.AlterField(
            model_name='historicaldemographiccharacteristic',
            name='material_build_floor',
            field=models.CharField(choices=[('soil_sand_mud', 'Soil/ sand/ mud'), ('cement_concrete_tiles', 'Cement/ concrete/ tiles'), ('OTHER', 'Others')], max_length=45, verbose_name='Which materials were used to build the floor in your house?'),
        ),
        migrations.AlterField(
            model_name='historicaldemographiccharacteristic',
            name='material_build_walls',
            field=models.CharField(choices=[('soil_sand_mud', 'There is no wall'), ('cement_concrete_tiles', 'Grass'), ('other', 'Canes/ Palm'), ('trees_mud', 'Trees and mud'), ('stone_mud', 'Stones and mud'), ('wood_timber', 'Wood/timber'), ('cement_concrete_bricks', 'Cement/ concrete blocks/ burnt blocks/bricks.'), ('OTHER', 'Others')], max_length=45, verbose_name='Which materials were used to build the walls of your house?'),
        ),
        migrations.AlterField(
            model_name='historicaldemographiccharacteristic',
            name='occupation',
            field=models.CharField(choices=[('civil_servant', 'Civil Servant'), ('house_wife', 'House wife'), ('peasant', 'Peasant'), ('petty_trader', 'Petty trader'), ('entrepreneur', 'Entrepreneur'), ('unemployed', 'Unemployed'), ('business_man', 'Business man/woman'), ('OTHER', 'Other')], max_length=45, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='historicaldemographiccharacteristic',
            name='use_in_cooking',
            field=models.CharField(choices=[('electricity_stove', 'Electricity stove'), ('gas_stove', 'Gas stove'), ('kerosene_stove', 'Kerosene stove'), ('charcoal', 'Charcoal'), ('logs_woods', 'Logs/woods'), ('grass_leaves', 'Grass/leaves'), ('animal_waste', 'Animal waste'), ('plants_waste', 'Plants waste'), ('dont_cook', 'We do not cook'), ('OTHER', 'Others')], max_length=45, verbose_name='What does your household use in cooking regularly? '),
        ),
        migrations.AlterField(
            model_name='historicalhousekitchensurrounding',
            name='material_exterior_wall',
            field=models.CharField(choices=[('no_walls', 'No walls'), ('mud', 'Mud'), ('wood', 'Wood'), ('cement_concrete', 'Cement/concrete'), ('stone', 'Stone'), ('metal', 'Metal'), ('OTHER', 'Others')], max_length=15, verbose_name='What is the main material of the exterior walls of the dwelling?'),
        ),
        migrations.AlterField(
            model_name='historicalhousekitchensurrounding',
            name='material_exterior_wall_kitchen',
            field=models.CharField(choices=[('no_walls', 'No walls'), ('mud', 'Mud'), ('wood', 'Wood'), ('cement_concrete', 'Cement/concrete'), ('stone', 'Stone'), ('metal', 'Metal'), ('OTHER', 'Others')], max_length=125, verbose_name='What is the main material of the exterior walls of your kitchen?'),
        ),
        migrations.AlterField(
            model_name='historicalhousekitchensurrounding',
            name='material_floor',
            field=models.CharField(choices=[('earth_sand_clay_mud_dung', 'Earth/sand/clay/mud/dung'), ('wood', 'Wood'), ('ceramic_tiles_vinyl', 'Ceramic tiles or vinyl'), ('cement_concrete', 'Cement/concrete'), ('OTHER', 'Other')], max_length=45, verbose_name='What is the main material of the floor of the dwelling?'),
        ),
        migrations.AlterField(
            model_name='historicalhousekitchensurrounding',
            name='material_interior_wall',
            field=models.CharField(choices=[('no_walls', 'No walls'), ('mud', 'Mud'), ('wood', 'Wood'), ('cement_concrete', 'Cement/concrete'), ('stone', 'Stone'), ('metal', 'Metal'), ('OTHER', 'Others')], max_length=125, verbose_name='What is the main material of the interior walls of the dwelling?'),
        ),
        migrations.AlterField(
            model_name='historicalhousekitchensurrounding',
            name='material_interior_wall_kitchen',
            field=models.CharField(choices=[('no_roof', 'No roof'), ('thatch_straw', 'Thatch/straw'), ('mud', 'Mud'), ('metal', 'Metal'), ('wood', 'Wood'), ('brick', 'Brick'), ('tiles', 'Tiles'), ('slate', 'Slate'), ('OTHER', 'Others')], max_length=125, verbose_name='What is the main material of the interior walls of your kitchen?'),
        ),
        migrations.AlterField(
            model_name='historicalhousekitchensurrounding',
            name='material_kitchen_floor',
            field=models.CharField(choices=[('earth_sand_clay_mud_dung', 'Earth/sand/clay/mud/dung'), ('wood', 'Wood'), ('ceramic_tiles_vinyl', 'Ceramic tiles or vinyl'), ('cement_concrete', 'Cement/concrete'), ('OTHER', 'Other')], max_length=125, verbose_name='What is the main material of the kitchen floor?'),
        ),
        migrations.AlterField(
            model_name='historicalhousekitchensurrounding',
            name='material_kitchen_roof',
            field=models.CharField(choices=[('no_roof', 'No roof'), ('thatch_straw', 'Thatch/straw'), ('mud', 'Mud'), ('metal', 'Metal'), ('wood', 'Wood'), ('brick', 'Brick'), ('tiles', 'Tiles'), ('slate', 'Slate'), ('OTHER', 'Other')], max_length=125, verbose_name='What is the main material of the kitchen roof?'),
        ),
        migrations.AlterField(
            model_name='historicalhousekitchensurrounding',
            name='material_roof',
            field=models.CharField(choices=[('no_roof', 'No roof'), ('thatch_straw', 'Thatch/straw'), ('mud', 'Mud'), ('metal', 'Metal'), ('wood', 'Wood'), ('brick', 'Brick'), ('tiles', 'Tiles'), ('slate', 'Slate'), ('OTHER', 'Others')], max_length=45, verbose_name='What is the main material of the roof of the dwelling?'),
        ),
        migrations.AlterField(
            model_name='historicallungcancertreatment',
            name='treatment',
            field=models.CharField(choices=[('chemotherapy', 'Chemotherapy'), ('radiation', 'Radiation'), ('surgical_resection', 'Surgical resection'), ('immunotherapy', 'Immunotherapy'), ('tyrosine_kinase_inhibitor', 'Tyrosine kinase inhibitor '), ('1_2above', '1 & 2 above'), ('OTHER', 'Others')], max_length=45, verbose_name='Type of treatment?'),
        ),
        migrations.AlterField(
            model_name='historicaloccupationalhistory',
            name='industries_worked',
            field=models.CharField(choices=[('textile_industry', 'Textile industry'), ('chemical_production_industry', 'Chemical production industry'), ('food_processing_industry', 'Food processing industry'), ('drug_industry', 'Drug industry'), ('milling_industry', 'Milling industry'), ('construction_industry', 'Construction industry'), ('OTHER', 'Other')], max_length=45, verbose_name='If yes, what kind of industry did you work?'),
        ),
        migrations.AlterField(
            model_name='historicalsignsymptomlungcancer',
            name='characterize_symptoms',
            field=models.CharField(choices=[('', 'Sudden onset'), ('', 'Gradual onset'), ('', 'Progressive in severity'), ('', 'Intermittent in severity'), ('OTHER', 'Others')], max_length=45, verbose_name='How would you characterize your symptoms?'),
        ),
        migrations.AlterField(
            model_name='historicalsignsymptomlungcancer',
            name='family_member_relationship',
            field=models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('brother', 'Brother'), ('sister', 'Sister'), ('grandparent_mother_side', 'Grandparent from mother’s side'), ('grandparent_father_side', 'Grandparent from father’s side'), ('OTHER', 'Others')], max_length=45, verbose_name='If yes, what is your relationship with the above-mentioned person?'),
        ),
        migrations.AlterField(
            model_name='historicalsignsymptomlungcancer',
            name='what_brought_hospital',
            field=models.CharField(choices=[('cough_dont_go_away', "A cough that doesn't go away after 2 or 3 weeks"), ('long_standing_cough', 'A long-standing cough that gets worse'), ('coughing_blood', 'Coughing up blood or rust-colored sputum (spit or phlegm)'), ('chest_infections', 'Chest infections that keep coming back such as bronchitis, pneumonia etc'), ('chest_pain', 'Chest pain that is often worsen when breathing or coughing'), ('persistent_breathlessness', 'Persistent breathlessness'), ('persistent_tiredness', 'Persistent tiredness or lack of energy'), ('wheezing', 'Wheezing'), ('shortness_of_breath', 'Shortness of breath'), ('unexplained_weight_loss', 'Unexplained weight loss'), ('OTHER', 'Others')], max_length=45, verbose_name='What brought you to the hospital that made the doctors suspect/diagnose you to have lung cancer?'),
        ),
        migrations.AlterField(
            model_name='housekitchensurrounding',
            name='material_exterior_wall',
            field=models.CharField(choices=[('no_walls', 'No walls'), ('mud', 'Mud'), ('wood', 'Wood'), ('cement_concrete', 'Cement/concrete'), ('stone', 'Stone'), ('metal', 'Metal'), ('OTHER', 'Others')], max_length=15, verbose_name='What is the main material of the exterior walls of the dwelling?'),
        ),
        migrations.AlterField(
            model_name='housekitchensurrounding',
            name='material_exterior_wall_kitchen',
            field=models.CharField(choices=[('no_walls', 'No walls'), ('mud', 'Mud'), ('wood', 'Wood'), ('cement_concrete', 'Cement/concrete'), ('stone', 'Stone'), ('metal', 'Metal'), ('OTHER', 'Others')], max_length=125, verbose_name='What is the main material of the exterior walls of your kitchen?'),
        ),
        migrations.AlterField(
            model_name='housekitchensurrounding',
            name='material_floor',
            field=models.CharField(choices=[('earth_sand_clay_mud_dung', 'Earth/sand/clay/mud/dung'), ('wood', 'Wood'), ('ceramic_tiles_vinyl', 'Ceramic tiles or vinyl'), ('cement_concrete', 'Cement/concrete'), ('OTHER', 'Other')], max_length=45, verbose_name='What is the main material of the floor of the dwelling?'),
        ),
        migrations.AlterField(
            model_name='housekitchensurrounding',
            name='material_interior_wall',
            field=models.CharField(choices=[('no_walls', 'No walls'), ('mud', 'Mud'), ('wood', 'Wood'), ('cement_concrete', 'Cement/concrete'), ('stone', 'Stone'), ('metal', 'Metal'), ('OTHER', 'Others')], max_length=125, verbose_name='What is the main material of the interior walls of the dwelling?'),
        ),
        migrations.AlterField(
            model_name='housekitchensurrounding',
            name='material_interior_wall_kitchen',
            field=models.CharField(choices=[('no_roof', 'No roof'), ('thatch_straw', 'Thatch/straw'), ('mud', 'Mud'), ('metal', 'Metal'), ('wood', 'Wood'), ('brick', 'Brick'), ('tiles', 'Tiles'), ('slate', 'Slate'), ('OTHER', 'Others')], max_length=125, verbose_name='What is the main material of the interior walls of your kitchen?'),
        ),
        migrations.AlterField(
            model_name='housekitchensurrounding',
            name='material_kitchen_floor',
            field=models.CharField(choices=[('earth_sand_clay_mud_dung', 'Earth/sand/clay/mud/dung'), ('wood', 'Wood'), ('ceramic_tiles_vinyl', 'Ceramic tiles or vinyl'), ('cement_concrete', 'Cement/concrete'), ('OTHER', 'Other')], max_length=125, verbose_name='What is the main material of the kitchen floor?'),
        ),
        migrations.AlterField(
            model_name='housekitchensurrounding',
            name='material_kitchen_roof',
            field=models.CharField(choices=[('no_roof', 'No roof'), ('thatch_straw', 'Thatch/straw'), ('mud', 'Mud'), ('metal', 'Metal'), ('wood', 'Wood'), ('brick', 'Brick'), ('tiles', 'Tiles'), ('slate', 'Slate'), ('OTHER', 'Other')], max_length=125, verbose_name='What is the main material of the kitchen roof?'),
        ),
        migrations.AlterField(
            model_name='housekitchensurrounding',
            name='material_roof',
            field=models.CharField(choices=[('no_roof', 'No roof'), ('thatch_straw', 'Thatch/straw'), ('mud', 'Mud'), ('metal', 'Metal'), ('wood', 'Wood'), ('brick', 'Brick'), ('tiles', 'Tiles'), ('slate', 'Slate'), ('OTHER', 'Others')], max_length=45, verbose_name='What is the main material of the roof of the dwelling?'),
        ),
        migrations.AlterField(
            model_name='lungcancertreatment',
            name='treatment',
            field=models.CharField(choices=[('chemotherapy', 'Chemotherapy'), ('radiation', 'Radiation'), ('surgical_resection', 'Surgical resection'), ('immunotherapy', 'Immunotherapy'), ('tyrosine_kinase_inhibitor', 'Tyrosine kinase inhibitor '), ('1_2above', '1 & 2 above'), ('OTHER', 'Others')], max_length=45, verbose_name='Type of treatment?'),
        ),
        migrations.AlterField(
            model_name='occupationalhistory',
            name='industries_worked',
            field=models.CharField(choices=[('textile_industry', 'Textile industry'), ('chemical_production_industry', 'Chemical production industry'), ('food_processing_industry', 'Food processing industry'), ('drug_industry', 'Drug industry'), ('milling_industry', 'Milling industry'), ('construction_industry', 'Construction industry'), ('OTHER', 'Other')], max_length=45, verbose_name='If yes, what kind of industry did you work?'),
        ),
        migrations.AlterField(
            model_name='signsymptomlungcancer',
            name='characterize_symptoms',
            field=models.CharField(choices=[('', 'Sudden onset'), ('', 'Gradual onset'), ('', 'Progressive in severity'), ('', 'Intermittent in severity'), ('OTHER', 'Others')], max_length=45, verbose_name='How would you characterize your symptoms?'),
        ),
        migrations.AlterField(
            model_name='signsymptomlungcancer',
            name='family_member_relationship',
            field=models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('brother', 'Brother'), ('sister', 'Sister'), ('grandparent_mother_side', 'Grandparent from mother’s side'), ('grandparent_father_side', 'Grandparent from father’s side'), ('OTHER', 'Others')], max_length=45, verbose_name='If yes, what is your relationship with the above-mentioned person?'),
        ),
        migrations.AlterField(
            model_name='signsymptomlungcancer',
            name='what_brought_hospital',
            field=models.CharField(choices=[('cough_dont_go_away', "A cough that doesn't go away after 2 or 3 weeks"), ('long_standing_cough', 'A long-standing cough that gets worse'), ('coughing_blood', 'Coughing up blood or rust-colored sputum (spit or phlegm)'), ('chest_infections', 'Chest infections that keep coming back such as bronchitis, pneumonia etc'), ('chest_pain', 'Chest pain that is often worsen when breathing or coughing'), ('persistent_breathlessness', 'Persistent breathlessness'), ('persistent_tiredness', 'Persistent tiredness or lack of energy'), ('wheezing', 'Wheezing'), ('shortness_of_breath', 'Shortness of breath'), ('unexplained_weight_loss', 'Unexplained weight loss'), ('OTHER', 'Others')], max_length=45, verbose_name='What brought you to the hospital that made the doctors suspect/diagnose you to have lung cancer?'),
        ),
    ]
