# Generated by Django 3.1.7 on 2022-01-27 10:05

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import edcs_visit_schedule.managers


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('edcs_subject', '0008_auto_20220121_1122'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='clinicalreview',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', edcs_visit_schedule.managers.CrfModelManager()),
            ],
        ),
        migrations.AddField(
            model_name='clinicalreview',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clinicalreview',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clinicalreview',
            name='crf_status',
            field=models.CharField(choices=[('INCOMPLETE', 'Incomplete (some data pending)'), ('COMPLETE', 'Complete')], default='INCOMPLETE', help_text='If some data is still pending, flag this CRF as incomplete', max_length=25, verbose_name='CRF status'),
        ),
        migrations.AddField(
            model_name='clinicalreview',
            name='crf_status_comments',
            field=models.TextField(blank=True, help_text='for example, why some data is still pending', null=True, verbose_name='Any comments related to status of this CRF'),
        ),
        migrations.AddField(
            model_name='clinicalreview',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='clinicalreview',
            name='subject_visit',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='edcs_subject.subjectvisit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalclinicalreview',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalclinicalreview',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalclinicalreview',
            name='crf_status',
            field=models.CharField(choices=[('INCOMPLETE', 'Incomplete (some data pending)'), ('COMPLETE', 'Complete')], default='INCOMPLETE', help_text='If some data is still pending, flag this CRF as incomplete', max_length=25, verbose_name='CRF status'),
        ),
        migrations.AddField(
            model_name='historicalclinicalreview',
            name='crf_status_comments',
            field=models.TextField(blank=True, help_text='for example, why some data is still pending', null=True, verbose_name='Any comments related to status of this CRF'),
        ),
        migrations.AddField(
            model_name='historicalclinicalreview',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='historicalclinicalreview',
            name='subject_visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edcs_subject.subjectvisit'),
        ),
    ]
