# Generated by Django 3.1.7 on 2022-01-28 06:26

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import edcs_visit_schedule.managers


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('edcs_subject', '0009_auto_20220127_1005'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='airpollutionfollowup',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', edcs_visit_schedule.managers.CrfModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='alcoholtobaccouse',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', edcs_visit_schedule.managers.CrfModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='contraceptiveusereproductivehistory',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', edcs_visit_schedule.managers.CrfModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='cookingfuel',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', edcs_visit_schedule.managers.CrfModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='covidinfectionhistory',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', edcs_visit_schedule.managers.CrfModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='demographiccharacteristic',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', edcs_visit_schedule.managers.CrfModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='effectairpollution',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', edcs_visit_schedule.managers.CrfModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='hivlabinvestigation',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', edcs_visit_schedule.managers.CrfModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='homelocatorform',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', edcs_visit_schedule.managers.CrfModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='housekitchensurrounding',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', edcs_visit_schedule.managers.CrfModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='lungcancerlabinvestigation',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', edcs_visit_schedule.managers.CrfModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='lungcancertreatment',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', edcs_visit_schedule.managers.CrfModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='occupationalhistory',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', edcs_visit_schedule.managers.CrfModelManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='signsymptomlungcancer',
            managers=[
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
                ('objects', edcs_visit_schedule.managers.CrfModelManager()),
            ],
        ),
        migrations.AddField(
            model_name='airpollutionfollowup',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='airpollutionfollowup',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='airpollutionfollowup',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='airpollutionfollowup',
            name='subject_visit',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='edcs_subject.subjectvisit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alcoholtobaccouse',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alcoholtobaccouse',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alcoholtobaccouse',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='alcoholtobaccouse',
            name='subject_visit',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='edcs_subject.subjectvisit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contraceptiveusereproductivehistory',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contraceptiveusereproductivehistory',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='contraceptiveusereproductivehistory',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='contraceptiveusereproductivehistory',
            name='subject_visit',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='edcs_subject.subjectvisit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cookingfuel',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cookingfuel',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cookingfuel',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='cookingfuel',
            name='subject_visit',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='edcs_subject.subjectvisit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='covidinfectionhistory',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='covidinfectionhistory',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='covidinfectionhistory',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='covidinfectionhistory',
            name='subject_visit',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='edcs_subject.subjectvisit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demographiccharacteristic',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='demographiccharacteristic',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='demographiccharacteristic',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='demographiccharacteristic',
            name='subject_visit',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='edcs_subject.subjectvisit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='effectairpollution',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='effectairpollution',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='effectairpollution',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='effectairpollution',
            name='subject_visit',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='edcs_subject.subjectvisit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalairpollutionfollowup',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalairpollutionfollowup',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalairpollutionfollowup',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='historicalairpollutionfollowup',
            name='subject_visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edcs_subject.subjectvisit'),
        ),
        migrations.AddField(
            model_name='historicalalcoholtobaccouse',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalalcoholtobaccouse',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalalcoholtobaccouse',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='historicalalcoholtobaccouse',
            name='subject_visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edcs_subject.subjectvisit'),
        ),
        migrations.AddField(
            model_name='historicalcontraceptiveusereproductivehistory',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontraceptiveusereproductivehistory',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontraceptiveusereproductivehistory',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='historicalcontraceptiveusereproductivehistory',
            name='subject_visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edcs_subject.subjectvisit'),
        ),
        migrations.AddField(
            model_name='historicalcookingfuel',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalcookingfuel',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalcookingfuel',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='historicalcookingfuel',
            name='subject_visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edcs_subject.subjectvisit'),
        ),
        migrations.AddField(
            model_name='historicalcovidinfectionhistory',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalcovidinfectionhistory',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalcovidinfectionhistory',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='historicalcovidinfectionhistory',
            name='subject_visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edcs_subject.subjectvisit'),
        ),
        migrations.AddField(
            model_name='historicaldemographiccharacteristic',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicaldemographiccharacteristic',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicaldemographiccharacteristic',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='historicaldemographiccharacteristic',
            name='subject_visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edcs_subject.subjectvisit'),
        ),
        migrations.AddField(
            model_name='historicaleffectairpollution',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicaleffectairpollution',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicaleffectairpollution',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='historicaleffectairpollution',
            name='subject_visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edcs_subject.subjectvisit'),
        ),
        migrations.AddField(
            model_name='historicalhivlabinvestigation',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalhivlabinvestigation',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalhivlabinvestigation',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='historicalhivlabinvestigation',
            name='subject_visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edcs_subject.subjectvisit'),
        ),
        migrations.AddField(
            model_name='historicalhomelocatorform',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalhomelocatorform',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalhomelocatorform',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='historicalhomelocatorform',
            name='subject_visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edcs_subject.subjectvisit'),
        ),
        migrations.AddField(
            model_name='historicalhousekitchensurrounding',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalhousekitchensurrounding',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalhousekitchensurrounding',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='historicalhousekitchensurrounding',
            name='subject_visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edcs_subject.subjectvisit'),
        ),
        migrations.AddField(
            model_name='historicallungcancerlabinvestigation',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicallungcancerlabinvestigation',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicallungcancerlabinvestigation',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='historicallungcancerlabinvestigation',
            name='subject_visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edcs_subject.subjectvisit'),
        ),
        migrations.AddField(
            model_name='historicallungcancertreatment',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicallungcancertreatment',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicallungcancertreatment',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='historicallungcancertreatment',
            name='subject_visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edcs_subject.subjectvisit'),
        ),
        migrations.AddField(
            model_name='historicaloccupationalhistory',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicaloccupationalhistory',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicaloccupationalhistory',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='historicaloccupationalhistory',
            name='subject_visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edcs_subject.subjectvisit'),
        ),
        migrations.AddField(
            model_name='historicalsignsymptomlungcancer',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalsignsymptomlungcancer',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalsignsymptomlungcancer',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='historicalsignsymptomlungcancer',
            name='subject_visit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edcs_subject.subjectvisit'),
        ),
        migrations.AddField(
            model_name='hivlabinvestigation',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hivlabinvestigation',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hivlabinvestigation',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='hivlabinvestigation',
            name='subject_visit',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='edcs_subject.subjectvisit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homelocatorform',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homelocatorform',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='homelocatorform',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='homelocatorform',
            name='subject_visit',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='edcs_subject.subjectvisit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housekitchensurrounding',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='housekitchensurrounding',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='housekitchensurrounding',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='housekitchensurrounding',
            name='subject_visit',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='edcs_subject.subjectvisit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lungcancerlabinvestigation',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lungcancerlabinvestigation',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lungcancerlabinvestigation',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='lungcancerlabinvestigation',
            name='subject_visit',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='edcs_subject.subjectvisit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lungcancertreatment',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lungcancertreatment',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='lungcancertreatment',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='lungcancertreatment',
            name='subject_visit',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='edcs_subject.subjectvisit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='occupationalhistory',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='occupationalhistory',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='occupationalhistory',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='occupationalhistory',
            name='subject_visit',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='edcs_subject.subjectvisit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signsymptomlungcancer',
            name='consent_model',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='signsymptomlungcancer',
            name='consent_version',
            field=models.CharField(editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='signsymptomlungcancer',
            name='site',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sites.site'),
        ),
        migrations.AddField(
            model_name='signsymptomlungcancer',
            name='subject_visit',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to='edcs_subject.subjectvisit'),
            preserve_default=False,
        ),
    ]
