# Generated by Django 3.1.7 on 2022-02-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0010_auto_20220216_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airpollutionfollowup',
            name='pollution_readings',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='What is the air pollution readings'),
        ),
        migrations.AlterField(
            model_name='historicalairpollutionfollowup',
            name='pollution_readings',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='What is the air pollution readings'),
        ),
    ]
