# Generated by Django 3.1.7 on 2022-05-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_lists', '0002_auto_20220506_0909'),
        ('edcs_subject', '0010_auto_20220505_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alcoholtobaccouse',
            name='smoke_tobacco',
        ),
        migrations.RemoveField(
            model_name='historicalalcoholtobaccouse',
            name='smoke_tobacco',
        ),
        migrations.AddField(
            model_name='alcoholtobaccouse',
            name='smoke_chew_tobacco',
            field=models.ManyToManyField(to='edcs_lists.SmokingTobaccoProducts', verbose_name='Do you smoke or chew tobacco products?'),
        ),
        migrations.AlterField(
            model_name='alcoholtobaccouse',
            name='tobacco_product',
            field=models.CharField(choices=[('yes_cigarettes', 'Yes, Cigarettes'), ('yes_cigars', 'Yes, Cigars'), ('yes_shisha', 'Yes, Shisha'), ('yes_pipes', 'Yes, pipes'), ('none_of_above', 'None of the above'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If currently/past smoker/chew, which tobacco products do you/ did you smoke/chew.'),
        ),
        migrations.AlterField(
            model_name='historicalalcoholtobaccouse',
            name='tobacco_product',
            field=models.CharField(choices=[('yes_cigarettes', 'Yes, Cigarettes'), ('yes_cigars', 'Yes, Cigars'), ('yes_shisha', 'Yes, Shisha'), ('yes_pipes', 'Yes, pipes'), ('none_of_above', 'None of the above'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If currently/past smoker/chew, which tobacco products do you/ did you smoke/chew.'),
        ),
    ]
