# Generated by Django 3.1.7 on 2022-02-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0011_auto_20220216_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airpollutionfollowup',
            name='distance_health_facility',
            field=models.DecimalField(decimal_places=2, help_text='(in km)', max_digits=4, verbose_name='Distance from patient’s home to the health facility'),
        ),
        migrations.AlterField(
            model_name='historicalairpollutionfollowup',
            name='distance_health_facility',
            field=models.DecimalField(decimal_places=2, help_text='(in km)', max_digits=4, verbose_name='Distance from patient’s home to the health facility'),
        ),
    ]
