# Generated by Django 3.1.7 on 2022-05-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_lists', '0002_auto_20220506_0909'),
        ('edcs_subject', '0011_auto_20220506_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alcoholtobaccouse',
            name='tobacco_product',
        ),
        migrations.RemoveField(
            model_name='historicalalcoholtobaccouse',
            name='tobacco_product',
        ),
        migrations.AddField(
            model_name='alcoholtobaccouse',
            name='tobacco_products',
            field=models.ManyToManyField(to='edcs_lists.TobaccoProducts', verbose_name='If currently/past smoker/chew, which tobacco products do you/ did you smoke/chew.'),
        ),
    ]
