# Generated by Django 3.1.7 on 2022-05-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_lists', '0003_auto_20220506_0933'),
        ('edcs_subject', '0012_auto_20220506_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contraceptiveusereproductivehistory',
            name='use_oral_contraceptives',
        ),
        migrations.RemoveField(
            model_name='historicalcontraceptiveusereproductivehistory',
            name='use_oral_contraceptives',
        ),
        migrations.AddField(
            model_name='contraceptiveusereproductivehistory',
            name='contraceptives',
            field=models.ManyToManyField(to='edcs_lists.Contraceptives', verbose_name='If the answer is yes, which type of contraceptives have you ever used?'),
        ),
        migrations.AddField(
            model_name='contraceptiveusereproductivehistory',
            name='use_contraceptives',
            field=models.CharField(choices=[('yes_current_user', 'Yes, Current user'), ('yes_past_user', 'Yes, Past user'), ('No', 'No'), ('decline_to_answer', 'Decline to answer'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='Have you ever used any contraceptives?'),
        ),
        migrations.AddField(
            model_name='historicalcontraceptiveusereproductivehistory',
            name='use_contraceptives',
            field=models.CharField(choices=[('yes_current_user', 'Yes, Current user'), ('yes_past_user', 'Yes, Past user'), ('No', 'No'), ('decline_to_answer', 'Decline to answer'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='Have you ever used any contraceptives?'),
        ),
        migrations.AlterField(
            model_name='contraceptiveusereproductivehistory',
            name='how_long_use_oral_contraceptives',
            field=models.CharField(choices=[('less_than_5yrs', '≤ 5 years'), ('greater_than_5yrs', '≥ 5 years'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If yes, how long have you been using the named above contraceptives?'),
        ),
        migrations.AlterField(
            model_name='historicalcontraceptiveusereproductivehistory',
            name='how_long_use_oral_contraceptives',
            field=models.CharField(choices=[('less_than_5yrs', '≤ 5 years'), ('greater_than_5yrs', '≥ 5 years'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If yes, how long have you been using the named above contraceptives?'),
        ),
    ]
