# Generated by Django 3.1.7 on 2022-02-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0012_auto_20220216_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoholtobaccouse',
            name='alcohol_consumption_frequency',
            field=models.CharField(choices=[('daily', '1-Daily'), ('every_other_day', 'Every other day'), ('weekly', 'Weekly (Not daily )'), ('monthly', 'Monthly (Not weekly)'), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='How frequently do you consume alcohol?'),
        ),
        migrations.AlterField(
            model_name='alcoholtobaccouse',
            name='smoke_inside_house',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('less_than_monthly', 'Less than monthly'), ('never', 'Never'), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='How often does anyone smoke inside your house?'),
        ),
        migrations.AlterField(
            model_name='alcoholtobaccouse',
            name='smoking_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('every_other_day', 'Every other day'), ('weekly', 'Weekly (Not daily)'), ('monthly', 'Monthly(Not weekly)'), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='How frequently do you smoke these products?'),
        ),
        migrations.AlterField(
            model_name='alcoholtobaccouse',
            name='tobacco_product',
            field=models.DateField(choices=[('yes_cigarettes', 'Yes, Cigarettes'), ('yes_cigars', 'Yes, Cigars'), ('yes_shisha', 'Yes, Shisha'), ('yes_pipes', 'Yes, pipes'), ('none_of_above', 'None of the above'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If currently/past smoker, which tobacco products do you/ did you smoke.'),
        ),
        migrations.AlterField(
            model_name='historicalalcoholtobaccouse',
            name='alcohol_consumption_frequency',
            field=models.CharField(choices=[('daily', '1-Daily'), ('every_other_day', 'Every other day'), ('weekly', 'Weekly (Not daily )'), ('monthly', 'Monthly (Not weekly)'), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='How frequently do you consume alcohol?'),
        ),
        migrations.AlterField(
            model_name='historicalalcoholtobaccouse',
            name='smoke_inside_house',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('less_than_monthly', 'Less than monthly'), ('never', 'Never'), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='How often does anyone smoke inside your house?'),
        ),
        migrations.AlterField(
            model_name='historicalalcoholtobaccouse',
            name='smoking_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('every_other_day', 'Every other day'), ('weekly', 'Weekly (Not daily)'), ('monthly', 'Monthly(Not weekly)'), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='How frequently do you smoke these products?'),
        ),
        migrations.AlterField(
            model_name='historicalalcoholtobaccouse',
            name='tobacco_product',
            field=models.DateField(choices=[('yes_cigarettes', 'Yes, Cigarettes'), ('yes_cigars', 'Yes, Cigars'), ('yes_shisha', 'Yes, Shisha'), ('yes_pipes', 'Yes, pipes'), ('none_of_above', 'None of the above'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If currently/past smoker, which tobacco products do you/ did you smoke.'),
        ),
    ]
