# Generated by Django 3.1.7 on 2022-02-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0013_auto_20220216_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoholtobaccouse',
            name='smoke_tobacco',
            field=models.CharField(choices=[('yes_current_smoker', 'Yes, Current smoker'), ('yes_past_smoker', 'Yes, past smoker'), ('NEVER', 'Never')], max_length=45, verbose_name='Do you smoke tobacco products?'),
        ),
        migrations.AlterField(
            model_name='historicalalcoholtobaccouse',
            name='smoke_tobacco',
            field=models.CharField(choices=[('yes_current_smoker', 'Yes, Current smoker'), ('yes_past_smoker', 'Yes, past smoker'), ('NEVER', 'Never')], max_length=45, verbose_name='Do you smoke tobacco products?'),
        ),
    ]
