# Generated by Django 3.1.7 on 2022-05-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_lists', '0004_auto_20220506_0956'),
        ('edcs_subject', '0014_auto_20220506_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcovidinfectionhistory',
            name='covid_vaccine',
        ),
        migrations.RemoveField(
            model_name='covidinfectionhistory',
            name='covid_vaccine',
        ),
        migrations.AddField(
            model_name='covidinfectionhistory',
            name='covid_vaccine',
            field=models.ManyToManyField(to='edcs_lists.CovidVaccine', verbose_name='If yes, what type of vaccination'),
        ),
    ]
