# Generated by Django 3.1.7 on 2022-02-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0017_auto_20220216_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoholtobaccouse',
            name='no_tobacco_product_smoked',
            field=models.IntegerField(blank=True, null=True, verbose_name='On average, how many of these products do you/did you smoke?'),
        ),
        migrations.AlterField(
            model_name='historicalalcoholtobaccouse',
            name='no_tobacco_product_smoked',
            field=models.IntegerField(blank=True, null=True, verbose_name='On average, how many of these products do you/did you smoke?'),
        ),
    ]
