# Generated by Django 3.1.7 on 2022-05-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0017_auto_20220506_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidinfectionhistory',
            name='vaccine_provider',
            field=models.CharField(choices=[('government_tz_ug', 'Government of Tanzania/Uganda'), ('research_study', 'Research study/trial '), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If Yes who provided the vaccine'),
        ),
        migrations.AlterField(
            model_name='historicalcovidinfectionhistory',
            name='vaccine_provider',
            field=models.CharField(choices=[('government_tz_ug', 'Government of Tanzania/Uganda'), ('research_study', 'Research study/trial '), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If Yes who provided the vaccine'),
        ),
    ]
