# Generated by Django 3.1.7 on 2022-05-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0018_auto_20220506_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contraceptiveusereproductivehistory',
            old_name='how_long_use_oral_contraceptives',
            new_name='how_long_use_contraceptives',
        ),
        migrations.RenameField(
            model_name='historicalcontraceptiveusereproductivehistory',
            old_name='how_long_use_oral_contraceptives',
            new_name='how_long_use_contraceptives',
        ),
    ]
