# Generated by Django 3.1.7 on 2022-02-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0018_auto_20220216_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoholtobaccouse',
            name='age_stop_smoking',
            field=models.IntegerField(blank=True, help_text='in years', null=True, verbose_name='If past smoker, at what age did you stop smoking?'),
        ),
        migrations.AlterField(
            model_name='historicalalcoholtobaccouse',
            name='age_stop_smoking',
            field=models.IntegerField(blank=True, help_text='in years', null=True, verbose_name='If past smoker, at what age did you stop smoking?'),
        ),
    ]
