# Generated by Django 3.1.7 on 2022-05-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_lists', '0004_auto_20220506_0956'),
        ('edcs_subject', '0019_auto_20220506_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidinfectionhistory',
            name='covid_symptoms',
            field=models.ManyToManyField(blank=True, related_name='covid_symptoms', to='edcs_lists.CovidSymptoms', verbose_name='If yes, what symptoms did you have when you first had COVID-19?'),
        ),
        migrations.AlterField(
            model_name='covidinfectionhistory',
            name='covid_vaccine',
            field=models.ManyToManyField(blank=True, to='edcs_lists.CovidVaccine', verbose_name='If yes, what type of vaccination'),
        ),
    ]
