# Generated by Django 3.1.7 on 2022-02-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0020_auto_20220216_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcoholtobaccouse',
            name='consume_alcohol',
            field=models.CharField(choices=[('yes_current_consumer', 'Yes, Current consumer'), ('yes_past_consumer', 'Yes, past consumer'), ('NEVER', 'Never')], max_length=45, verbose_name='Do you consume alcohol?'),
        ),
        migrations.AlterField(
            model_name='historicalalcoholtobaccouse',
            name='consume_alcohol',
            field=models.CharField(choices=[('yes_current_consumer', 'Yes, Current consumer'), ('yes_past_consumer', 'Yes, past consumer'), ('NEVER', 'Never')], max_length=45, verbose_name='Do you consume alcohol?'),
        ),
    ]
