# Generated by Django 3.1.7 on 2022-05-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0021_historicallabparta_labparta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallabparta',
            name='hiv_rapid_test',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('unknown', 'Unknown')], max_length=45, verbose_name='HIV rapid test'),
        ),
        migrations.AlterField(
            model_name='labparta',
            name='hiv_rapid_test',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('unknown', 'Unknown')], max_length=45, verbose_name='HIV rapid test'),
        ),
    ]
