# Generated by Django 3.1.7 on 2022-02-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0022_auto_20220216_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancerhistory',
            name='breast_cancer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name='Breast Cancer'),
        ),
        migrations.AlterField(
            model_name='cancerhistory',
            name='colon_cancer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name='Colon Cancer'),
        ),
        migrations.AlterField(
            model_name='cancerhistory',
            name='lung_cancer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name='Lung Cancer'),
        ),
        migrations.AlterField(
            model_name='cancerhistory',
            name='ovarian_cancer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name='Ovarian Cancer'),
        ),
        migrations.AlterField(
            model_name='cancerhistory',
            name='prostate_cancer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name='Prostate Cancer'),
        ),
        migrations.AlterField(
            model_name='cancerhistory',
            name='thyroid_cancer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name='Thyroid Cancer'),
        ),
        migrations.AlterField(
            model_name='cancerhistory',
            name='uterine_cancer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name='Uterine Cancer'),
        ),
        migrations.AlterField(
            model_name='historicalcancerhistory',
            name='breast_cancer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name='Breast Cancer'),
        ),
        migrations.AlterField(
            model_name='historicalcancerhistory',
            name='colon_cancer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name='Colon Cancer'),
        ),
        migrations.AlterField(
            model_name='historicalcancerhistory',
            name='lung_cancer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name='Lung Cancer'),
        ),
        migrations.AlterField(
            model_name='historicalcancerhistory',
            name='ovarian_cancer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name='Ovarian Cancer'),
        ),
        migrations.AlterField(
            model_name='historicalcancerhistory',
            name='prostate_cancer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name='Prostate Cancer'),
        ),
        migrations.AlterField(
            model_name='historicalcancerhistory',
            name='thyroid_cancer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name='Thyroid Cancer'),
        ),
        migrations.AlterField(
            model_name='historicalcancerhistory',
            name='uterine_cancer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=25, verbose_name='Uterine Cancer'),
        ),
    ]
