# Generated by Django 3.1.7 on 2022-02-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_lists', '0002_auto_20220208_0341'),
        ('edcs_subject', '0023_auto_20220216_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancerhistory',
            name='breast_cancer_age_dx',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indicate age of diagnosis'),
        ),
        migrations.AlterField(
            model_name='cancerhistory',
            name='breast_cancer_family_member',
            field=models.ManyToManyField(blank=True, related_name='breast_cancer_family_member', to='edcs_lists.FamilyMembers', verbose_name='What is your relationship?'),
        ),
        migrations.AlterField(
            model_name='cancerhistory',
            name='colon_cancer_age_dx',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indicate age of diagnosis'),
        ),
        migrations.AlterField(
            model_name='cancerhistory',
            name='colon_cancer_family_member',
            field=models.ManyToManyField(blank=True, related_name='colon_cancer_family_member', to='edcs_lists.FamilyMembers', verbose_name='What is your relationship?'),
        ),
        migrations.AlterField(
            model_name='cancerhistory',
            name='lung_cancer_age_dx',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indicate age of diagnosis'),
        ),
        migrations.AlterField(
            model_name='cancerhistory',
            name='lung_cancer_family_member',
            field=models.ManyToManyField(blank=True, related_name='lung_cancer_family_member', to='edcs_lists.FamilyMembers', verbose_name='What is your relationship?'),
        ),
        migrations.AlterField(
            model_name='cancerhistory',
            name='ovarian_cancer_age_dx',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indicate age of diagnosis'),
        ),
        migrations.AlterField(
            model_name='cancerhistory',
            name='ovarian_cancer_family_member',
            field=models.ManyToManyField(blank=True, related_name='ovarian_cancer_family_member', to='edcs_lists.FamilyMembers', verbose_name='What is your relationship?'),
        ),
        migrations.AlterField(
            model_name='cancerhistory',
            name='prostate_cancer_age_dx',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indicate age of diagnosis'),
        ),
        migrations.AlterField(
            model_name='cancerhistory',
            name='prostate_cancer_family_member',
            field=models.ManyToManyField(blank=True, related_name='prostate_cancer_family_member', to='edcs_lists.FamilyMembers', verbose_name='What is your relationship?'),
        ),
        migrations.AlterField(
            model_name='cancerhistory',
            name='thyroid_cancer_age_dx',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indicate age of diagnosis'),
        ),
        migrations.AlterField(
            model_name='cancerhistory',
            name='thyroid_cancer_family_member',
            field=models.ManyToManyField(blank=True, related_name='thyroid_cancer_family_member', to='edcs_lists.FamilyMembers', verbose_name='What is your relationship?'),
        ),
        migrations.AlterField(
            model_name='cancerhistory',
            name='uterine_cancer_age_dx',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indicate age of diagnosis'),
        ),
        migrations.AlterField(
            model_name='cancerhistory',
            name='uterine_cancer_family_member',
            field=models.ManyToManyField(blank=True, related_name='uterine_cancer_family_member', to='edcs_lists.FamilyMembers', verbose_name='What is your relationship?'),
        ),
        migrations.AlterField(
            model_name='historicalcancerhistory',
            name='breast_cancer_age_dx',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indicate age of diagnosis'),
        ),
        migrations.AlterField(
            model_name='historicalcancerhistory',
            name='colon_cancer_age_dx',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indicate age of diagnosis'),
        ),
        migrations.AlterField(
            model_name='historicalcancerhistory',
            name='lung_cancer_age_dx',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indicate age of diagnosis'),
        ),
        migrations.AlterField(
            model_name='historicalcancerhistory',
            name='ovarian_cancer_age_dx',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indicate age of diagnosis'),
        ),
        migrations.AlterField(
            model_name='historicalcancerhistory',
            name='prostate_cancer_age_dx',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indicate age of diagnosis'),
        ),
        migrations.AlterField(
            model_name='historicalcancerhistory',
            name='thyroid_cancer_age_dx',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indicate age of diagnosis'),
        ),
        migrations.AlterField(
            model_name='historicalcancerhistory',
            name='uterine_cancer_age_dx',
            field=models.IntegerField(blank=True, null=True, verbose_name='Indicate age of diagnosis'),
        ),
    ]
