# Generated by Django 3.1.7 on 2022-02-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0024_auto_20220216_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraceptiveusereproductivehistory',
            name='age_attain_menarche',
            field=models.CharField(choices=[('less_than_12yrs', '≤ 12 years'), ('12_13yrs', '12-13 years'), ('14_15yrs', '14-15 years'), ('greater_than_16yrs', '≥ 16 years'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='At what age did you attain your menarche?'),
        ),
        migrations.AlterField(
            model_name='contraceptiveusereproductivehistory',
            name='age_attain_menopause',
            field=models.CharField(choices=[('less_than_46yrs', '≤ 46 years'), ('46_50yrs', '46-50 years'), ('greater_than_51yrs', '≥ 51 years'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='For menopausal women, at what age did you attain menopause?'),
        ),
        migrations.AlterField(
            model_name='contraceptiveusereproductivehistory',
            name='age_have_first_child',
            field=models.CharField(choices=[('nulliparous', 'Nulliparous'), ('less_than_20yrs', '≤ 20years'), ('20_29yrs', '20-29 years'), ('30_39yrs', '30-39 years'), ('greater_than_39yrs', '≥ 39 years'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='At what age did you have your first child?'),
        ),
        migrations.AlterField(
            model_name='contraceptiveusereproductivehistory',
            name='age_have_last_child',
            field=models.CharField(choices=[('nulliparous', 'Nulliparous'), ('less_than_25yrs', '≤ 25years'), ('25_29_yrs', '25-29 years'), ('30_39yrs', '30-39 years'), ('greater_than_39yrs', '≥ 39 years'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='At what age did you have your last child?'),
        ),
        migrations.AlterField(
            model_name='contraceptiveusereproductivehistory',
            name='breast_feed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('decline_to_answer', 'Decline to answer'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='Have you ever breast fed?'),
        ),
        migrations.AlterField(
            model_name='contraceptiveusereproductivehistory',
            name='how_long_post_menopausal_hormone_therapy',
            field=models.CharField(choices=[('less_than_5yrs', '≤ 5 years'), ('greater_than_5yrs', '≥ 5 years'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If yes, how long have you been using/ have you used post-menopausal therapy? '),
        ),
        migrations.AlterField(
            model_name='contraceptiveusereproductivehistory',
            name='how_long_stop_post_menopausal_hormone_therapy',
            field=models.CharField(choices=[('less_than_5yrs_ago', '≤ 5 years ago'), ('greater_than_5yrs_ago', '≥ 5 years ago'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='For those who have stopped using post-menopausal hormone therapy, when did you stop using post-menopausal therapy?'),
        ),
        migrations.AlterField(
            model_name='contraceptiveusereproductivehistory',
            name='how_long_use_oral_contraceptives',
            field=models.CharField(choices=[('less_than_5yrs', '≤ 5 years'), ('greater_than_5yrs', '≥ 5 years'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If yes, how long have you been using oral contraceptives?'),
        ),
        migrations.AlterField(
            model_name='contraceptiveusereproductivehistory',
            name='post_menopausal_hormone_therapy',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('decline_to_answer', 'Decline to answer'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='Have you ever used post-menopausal hormone therapy?'),
        ),
        migrations.AlterField(
            model_name='contraceptiveusereproductivehistory',
            name='use_oral_contraceptives',
            field=models.CharField(choices=[('yes_current_user', 'Yes, Current user'), ('yes_past_user', 'Yes, Past user'), ('No', 'No'), ('decline_to_answer', 'Decline to answer'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='Have you ever used oral contraceptives?'),
        ),
        migrations.AlterField(
            model_name='contraceptiveusereproductivehistory',
            name='when_stop_use_contraceptives',
            field=models.CharField(choices=[('less_than_5yrs_ago', '≤ 5 years ago'), ('greater_than_5yrs_ago', '≥ 5 years ago'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='For those who have stopped using oral contraceptive, when did you stop?'),
        ),
        migrations.AlterField(
            model_name='historicalcontraceptiveusereproductivehistory',
            name='age_attain_menarche',
            field=models.CharField(choices=[('less_than_12yrs', '≤ 12 years'), ('12_13yrs', '12-13 years'), ('14_15yrs', '14-15 years'), ('greater_than_16yrs', '≥ 16 years'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='At what age did you attain your menarche?'),
        ),
        migrations.AlterField(
            model_name='historicalcontraceptiveusereproductivehistory',
            name='age_attain_menopause',
            field=models.CharField(choices=[('less_than_46yrs', '≤ 46 years'), ('46_50yrs', '46-50 years'), ('greater_than_51yrs', '≥ 51 years'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='For menopausal women, at what age did you attain menopause?'),
        ),
        migrations.AlterField(
            model_name='historicalcontraceptiveusereproductivehistory',
            name='age_have_first_child',
            field=models.CharField(choices=[('nulliparous', 'Nulliparous'), ('less_than_20yrs', '≤ 20years'), ('20_29yrs', '20-29 years'), ('30_39yrs', '30-39 years'), ('greater_than_39yrs', '≥ 39 years'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='At what age did you have your first child?'),
        ),
        migrations.AlterField(
            model_name='historicalcontraceptiveusereproductivehistory',
            name='age_have_last_child',
            field=models.CharField(choices=[('nulliparous', 'Nulliparous'), ('less_than_25yrs', '≤ 25years'), ('25_29_yrs', '25-29 years'), ('30_39yrs', '30-39 years'), ('greater_than_39yrs', '≥ 39 years'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='At what age did you have your last child?'),
        ),
        migrations.AlterField(
            model_name='historicalcontraceptiveusereproductivehistory',
            name='breast_feed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('decline_to_answer', 'Decline to answer'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='Have you ever breast fed?'),
        ),
        migrations.AlterField(
            model_name='historicalcontraceptiveusereproductivehistory',
            name='how_long_post_menopausal_hormone_therapy',
            field=models.CharField(choices=[('less_than_5yrs', '≤ 5 years'), ('greater_than_5yrs', '≥ 5 years'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If yes, how long have you been using/ have you used post-menopausal therapy? '),
        ),
        migrations.AlterField(
            model_name='historicalcontraceptiveusereproductivehistory',
            name='how_long_stop_post_menopausal_hormone_therapy',
            field=models.CharField(choices=[('less_than_5yrs_ago', '≤ 5 years ago'), ('greater_than_5yrs_ago', '≥ 5 years ago'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='For those who have stopped using post-menopausal hormone therapy, when did you stop using post-menopausal therapy?'),
        ),
        migrations.AlterField(
            model_name='historicalcontraceptiveusereproductivehistory',
            name='how_long_use_oral_contraceptives',
            field=models.CharField(choices=[('less_than_5yrs', '≤ 5 years'), ('greater_than_5yrs', '≥ 5 years'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If yes, how long have you been using oral contraceptives?'),
        ),
        migrations.AlterField(
            model_name='historicalcontraceptiveusereproductivehistory',
            name='post_menopausal_hormone_therapy',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('decline_to_answer', 'Decline to answer'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='Have you ever used post-menopausal hormone therapy?'),
        ),
        migrations.AlterField(
            model_name='historicalcontraceptiveusereproductivehistory',
            name='use_oral_contraceptives',
            field=models.CharField(choices=[('yes_current_user', 'Yes, Current user'), ('yes_past_user', 'Yes, Past user'), ('No', 'No'), ('decline_to_answer', 'Decline to answer'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='Have you ever used oral contraceptives?'),
        ),
        migrations.AlterField(
            model_name='historicalcontraceptiveusereproductivehistory',
            name='when_stop_use_contraceptives',
            field=models.CharField(choices=[('less_than_5yrs_ago', '≤ 5 years ago'), ('greater_than_5yrs_ago', '≥ 5 years ago'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='For those who have stopped using oral contraceptive, when did you stop?'),
        ),
        migrations.AlterField(
            model_name='historicaloccupationalhistory',
            name='how_long_work_mine',
            field=models.CharField(choices=[('less_than_5yrs', '≤ 5 years'), ('greater_than_5yrs', '≥ 5 years'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, for how long have worked in the mines?'),
        ),
        migrations.AlterField(
            model_name='occupationalhistory',
            name='how_long_work_mine',
            field=models.CharField(choices=[('less_than_5yrs', '≤ 5 years'), ('greater_than_5yrs', '≥ 5 years'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, for how long have worked in the mines?'),
        ),
    ]
