# Generated by Django 3.1.7 on 2022-05-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0025_historicallabpartd_labpartd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallabpartb',
            name='ct_findings',
            field=models.TextField(max_length=500, verbose_name='CT findings'),
        ),
        migrations.AlterField(
            model_name='historicallabpartb',
            name='nature_of_specimen',
            field=models.TextField(max_length=500, verbose_name='Nature of specimen (Tissue or Fluid)'),
        ),
        migrations.AlterField(
            model_name='historicallabpartb',
            name='xray_findings',
            field=models.TextField(max_length=500, verbose_name='X-ray findings'),
        ),
        migrations.AlterField(
            model_name='historicallabpartc',
            name='non_small_cell',
            field=models.CharField(choices=[('adenocarcinoma', 'Adenocarcinoma'), ('squamous_cell_carcinomas', 'Squamous cell carcinomas'), ('large_cell_carcinomas', 'Large cell carcinomas'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If non-small cell'),
        ),
        migrations.AlterField(
            model_name='labpartb',
            name='ct_findings',
            field=models.TextField(max_length=500, verbose_name='CT findings'),
        ),
        migrations.AlterField(
            model_name='labpartb',
            name='nature_of_specimen',
            field=models.TextField(max_length=500, verbose_name='Nature of specimen (Tissue or Fluid)'),
        ),
        migrations.AlterField(
            model_name='labpartb',
            name='xray_findings',
            field=models.TextField(max_length=500, verbose_name='X-ray findings'),
        ),
        migrations.AlterField(
            model_name='labpartc',
            name='non_small_cell',
            field=models.CharField(choices=[('adenocarcinoma', 'Adenocarcinoma'), ('squamous_cell_carcinomas', 'Squamous cell carcinomas'), ('large_cell_carcinomas', 'Large cell carcinomas'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If non-small cell'),
        ),
    ]
