# Generated by Django 3.1.7 on 2022-02-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0025_auto_20220216_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraceptiveusereproductivehistory',
            name='how_long_post_menopausal_hormone_therapy',
            field=models.CharField(choices=[('less_than_5yrs', '≤ 5 years'), ('greater_than_5yrs', '≥ 5 years'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If yes, how long have you been using/ have you used post-menopausal therapy?'),
        ),
        migrations.AlterField(
            model_name='historicalcontraceptiveusereproductivehistory',
            name='how_long_post_menopausal_hormone_therapy',
            field=models.CharField(choices=[('less_than_5yrs', '≤ 5 years'), ('greater_than_5yrs', '≥ 5 years'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If yes, how long have you been using/ have you used post-menopausal therapy?'),
        ),
    ]
