# Generated by Django 3.1.7 on 2022-05-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0026_auto_20220518_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallabpartc',
            name='microscopic_findings',
            field=models.TextField(max_length=500, verbose_name='Microscopic findings'),
        ),
        migrations.AlterField(
            model_name='labpartc',
            name='microscopic_findings',
            field=models.TextField(max_length=500, verbose_name='Microscopic findings'),
        ),
    ]
