# Generated by Django 3.1.7 on 2022-02-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0027_auto_20220217_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookingfuel',
            name='use_biogas_per_month',
            field=models.CharField(choices=[('25_days_month', 'At least 25% of the days in a month'), ('25_50_days_month', '25%-50% of the days in a month'), ('50_70_days_month', '50-75% of the days in a month'), ('75_100_days_month', '75%-100% of the days in a month'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, how many times do you use biogas per month?'),
        ),
        migrations.AlterField(
            model_name='cookingfuel',
            name='use_charcoal_per_month',
            field=models.CharField(choices=[('25_days_month', 'At least 25% of the days in a month'), ('25_50_days_month', '25%-50% of the days in a month'), ('50_70_days_month', '50-75% of the days in a month'), ('75_100_days_month', '75%-100% of the days in a month'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, how many times do you use charcoal per month?'),
        ),
        migrations.AlterField(
            model_name='cookingfuel',
            name='use_coal_per_month',
            field=models.CharField(choices=[('25_days_month', 'At least 25% of the days in a month'), ('25_50_days_month', '25%-50% of the days in a month'), ('50_70_days_month', '50-75% of the days in a month'), ('75_100_days_month', '75%-100% of the days in a month'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, how many times do you use coal/ignite per month?'),
        ),
        migrations.AlterField(
            model_name='cookingfuel',
            name='use_dung_per_month',
            field=models.CharField(choices=[('25_days_month', 'At least 25% of the days in a month'), ('25_50_days_month', '25%-50% of the days in a month'), ('50_70_days_month', '50-75% of the days in a month'), ('75_100_days_month', '75%-100% of the days in a month'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, how many times do you use animal dung per month?'),
        ),
        migrations.AlterField(
            model_name='cookingfuel',
            name='use_electricity_per_month',
            field=models.CharField(choices=[('25_days_month', 'At least 25% of the days in a month'), ('25_50_days_month', '25%-50% of the days in a month'), ('50_70_days_month', '50-75% of the days in a month'), ('75_100_days_month', '75%-100% of the days in a month'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, how many times do you use electricity per month?'),
        ),
        migrations.AlterField(
            model_name='cookingfuel',
            name='use_kerosene_per_month',
            field=models.CharField(choices=[('25_days_month', 'At least 25% of the days in a month'), ('25_50_days_month', '25%-50% of the days in a month'), ('50_70_days_month', '50-75% of the days in a month'), ('75_100_days_month', '75%-100% of the days in a month'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, how many times do you use kerosene per month?'),
        ),
        migrations.AlterField(
            model_name='cookingfuel',
            name='use_paper_per_month',
            field=models.CharField(choices=[('25_days_month', 'At least 25% of the days in a month'), ('25_50_days_month', '25%-50% of the days in a month'), ('50_70_days_month', '50-75% of the days in a month'), ('75_100_days_month', '75%-100% of the days in a month'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, how many times do you use paper per month?'),
        ),
        migrations.AlterField(
            model_name='cookingfuel',
            name='use_polythene_per_month',
            field=models.CharField(choices=[('25_days_month', 'At least 25% of the days in a month'), ('25_50_days_month', '25%-50% of the days in a month'), ('50_70_days_month', '50-75% of the days in a month'), ('75_100_days_month', '75%-100% of the days in a month'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, how many times do you use polythene per month?'),
        ),
        migrations.AlterField(
            model_name='cookingfuel',
            name='use_straw_per_month',
            field=models.CharField(choices=[('25_days_month', 'At least 25% of the days in a month'), ('25_50_days_month', '25%-50% of the days in a month'), ('50_70_days_month', '50-75% of the days in a month'), ('75_100_days_month', '75%-100% of the days in a month'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, how many times do you use straw/shrubs/grass per month?'),
        ),
        migrations.AlterField(
            model_name='cookingfuel',
            name='use_wood_per_month',
            field=models.CharField(choices=[('25_days_month', 'At least 25% of the days in a month'), ('25_50_days_month', '25%-50% of the days in a month'), ('50_70_days_month', '50-75% of the days in a month'), ('75_100_days_month', '75%-100% of the days in a month'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, how many times do you use wood per month?'),
        ),
        migrations.AlterField(
            model_name='historicalcookingfuel',
            name='use_biogas_per_month',
            field=models.CharField(choices=[('25_days_month', 'At least 25% of the days in a month'), ('25_50_days_month', '25%-50% of the days in a month'), ('50_70_days_month', '50-75% of the days in a month'), ('75_100_days_month', '75%-100% of the days in a month'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, how many times do you use biogas per month?'),
        ),
        migrations.AlterField(
            model_name='historicalcookingfuel',
            name='use_charcoal_per_month',
            field=models.CharField(choices=[('25_days_month', 'At least 25% of the days in a month'), ('25_50_days_month', '25%-50% of the days in a month'), ('50_70_days_month', '50-75% of the days in a month'), ('75_100_days_month', '75%-100% of the days in a month'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, how many times do you use charcoal per month?'),
        ),
        migrations.AlterField(
            model_name='historicalcookingfuel',
            name='use_coal_per_month',
            field=models.CharField(choices=[('25_days_month', 'At least 25% of the days in a month'), ('25_50_days_month', '25%-50% of the days in a month'), ('50_70_days_month', '50-75% of the days in a month'), ('75_100_days_month', '75%-100% of the days in a month'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, how many times do you use coal/ignite per month?'),
        ),
        migrations.AlterField(
            model_name='historicalcookingfuel',
            name='use_dung_per_month',
            field=models.CharField(choices=[('25_days_month', 'At least 25% of the days in a month'), ('25_50_days_month', '25%-50% of the days in a month'), ('50_70_days_month', '50-75% of the days in a month'), ('75_100_days_month', '75%-100% of the days in a month'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, how many times do you use animal dung per month?'),
        ),
        migrations.AlterField(
            model_name='historicalcookingfuel',
            name='use_electricity_per_month',
            field=models.CharField(choices=[('25_days_month', 'At least 25% of the days in a month'), ('25_50_days_month', '25%-50% of the days in a month'), ('50_70_days_month', '50-75% of the days in a month'), ('75_100_days_month', '75%-100% of the days in a month'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, how many times do you use electricity per month?'),
        ),
        migrations.AlterField(
            model_name='historicalcookingfuel',
            name='use_kerosene_per_month',
            field=models.CharField(choices=[('25_days_month', 'At least 25% of the days in a month'), ('25_50_days_month', '25%-50% of the days in a month'), ('50_70_days_month', '50-75% of the days in a month'), ('75_100_days_month', '75%-100% of the days in a month'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, how many times do you use kerosene per month?'),
        ),
        migrations.AlterField(
            model_name='historicalcookingfuel',
            name='use_paper_per_month',
            field=models.CharField(choices=[('25_days_month', 'At least 25% of the days in a month'), ('25_50_days_month', '25%-50% of the days in a month'), ('50_70_days_month', '50-75% of the days in a month'), ('75_100_days_month', '75%-100% of the days in a month'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, how many times do you use paper per month?'),
        ),
        migrations.AlterField(
            model_name='historicalcookingfuel',
            name='use_polythene_per_month',
            field=models.CharField(choices=[('25_days_month', 'At least 25% of the days in a month'), ('25_50_days_month', '25%-50% of the days in a month'), ('50_70_days_month', '50-75% of the days in a month'), ('75_100_days_month', '75%-100% of the days in a month'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, how many times do you use polythene per month?'),
        ),
        migrations.AlterField(
            model_name='historicalcookingfuel',
            name='use_straw_per_month',
            field=models.CharField(choices=[('25_days_month', 'At least 25% of the days in a month'), ('25_50_days_month', '25%-50% of the days in a month'), ('50_70_days_month', '50-75% of the days in a month'), ('75_100_days_month', '75%-100% of the days in a month'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, how many times do you use straw/shrubs/grass per month?'),
        ),
        migrations.AlterField(
            model_name='historicalcookingfuel',
            name='use_wood_per_month',
            field=models.CharField(choices=[('25_days_month', 'At least 25% of the days in a month'), ('25_50_days_month', '25%-50% of the days in a month'), ('50_70_days_month', '50-75% of the days in a month'), ('75_100_days_month', '75%-100% of the days in a month'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, how many times do you use wood per month?'),
        ),
    ]
