# Generated by Django 3.1.7 on 2022-02-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_lists', '0002_auto_20220208_0341'),
        ('edcs_subject', '0029_auto_20220217_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidinfectionhistory',
            name='covid_symptoms',
            field=models.ManyToManyField(blank=True, null=True, related_name='covid_symptoms', to='edcs_lists.CovidSymptoms', verbose_name='If yes, what symptoms did you have when you first had COVID-19?'),
        ),
        migrations.AlterField(
            model_name='covidinfectionhistory',
            name='covid_vaccine',
            field=models.CharField(choices=[('dont_know_type', 'Don’t know type'), ('pfizer_biontech_moderna', 'Pfizer/BioNTech Moderna'), ('oxford_astraZeneca', 'Oxford/AstraZeneca'), ('janssen_johnson_Johnson', 'Janssen\\Johnson&Johnson'), ('novavax', 'Novavax'), ('sinovac', 'Sinovac'), ('sputnik', 'Sputnik'), ('valneva', 'Valneva'), ('sinopharm', 'Sinopharm'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If yes, what type of vaccination'),
        ),
        migrations.AlterField(
            model_name='covidinfectionhistory',
            name='date_first_positive_test',
            field=models.DateField(blank=True, max_length=45, null=True, verbose_name='If any positive test: What was the date of first positive test you’ve had?'),
        ),
        migrations.AlterField(
            model_name='covidinfectionhistory',
            name='date_last_negative_test',
            field=models.DateField(blank=True, max_length=45, null=True, verbose_name='If all tests negative: What was the date of last negative test you’ve had?'),
        ),
        migrations.AlterField(
            model_name='covidinfectionhistory',
            name='date_recent_vaccination',
            field=models.DateField(blank=True, max_length=45, null=True, verbose_name='Date of most recent vaccination?'),
        ),
        migrations.AlterField(
            model_name='covidinfectionhistory',
            name='date_think_had_covid',
            field=models.DateField(blank=True, max_length=45, null=True, verbose_name='If yes, On what date did you first know or think you had COVID-19?'),
        ),
        migrations.AlterField(
            model_name='covidinfectionhistory',
            name='no_covid_vaccine',
            field=models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three_more', 'Three or More'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='How many doses have you received to date?'),
        ),
        migrations.AlterField(
            model_name='covidinfectionhistory',
            name='swab_test_results',
            field=models.CharField(choices=[('positive_test', 'One or more positive test(s) '), ('negative_more_positive', 'One or more negative tests, but none were positive'), ('all_test_failed', 'All tests failed'), ('waiting_results', 'Waiting for all results'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If yes, What was the result/were the results of all swab tests you’ve had?'),
        ),
        migrations.AlterField(
            model_name='covidinfectionhistory',
            name='vaccine_provider',
            field=models.CharField(choices=[('government_uganda', 'Government of Uganda'), ('research_study', 'Research study/trial '), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If Yes who provided the vaccine'),
        ),
        migrations.AlterField(
            model_name='historicalcovidinfectionhistory',
            name='covid_vaccine',
            field=models.CharField(choices=[('dont_know_type', 'Don’t know type'), ('pfizer_biontech_moderna', 'Pfizer/BioNTech Moderna'), ('oxford_astraZeneca', 'Oxford/AstraZeneca'), ('janssen_johnson_Johnson', 'Janssen\\Johnson&Johnson'), ('novavax', 'Novavax'), ('sinovac', 'Sinovac'), ('sputnik', 'Sputnik'), ('valneva', 'Valneva'), ('sinopharm', 'Sinopharm'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If yes, what type of vaccination'),
        ),
        migrations.AlterField(
            model_name='historicalcovidinfectionhistory',
            name='date_first_positive_test',
            field=models.DateField(blank=True, max_length=45, null=True, verbose_name='If any positive test: What was the date of first positive test you’ve had?'),
        ),
        migrations.AlterField(
            model_name='historicalcovidinfectionhistory',
            name='date_last_negative_test',
            field=models.DateField(blank=True, max_length=45, null=True, verbose_name='If all tests negative: What was the date of last negative test you’ve had?'),
        ),
        migrations.AlterField(
            model_name='historicalcovidinfectionhistory',
            name='date_recent_vaccination',
            field=models.DateField(blank=True, max_length=45, null=True, verbose_name='Date of most recent vaccination?'),
        ),
        migrations.AlterField(
            model_name='historicalcovidinfectionhistory',
            name='date_think_had_covid',
            field=models.DateField(blank=True, max_length=45, null=True, verbose_name='If yes, On what date did you first know or think you had COVID-19?'),
        ),
        migrations.AlterField(
            model_name='historicalcovidinfectionhistory',
            name='no_covid_vaccine',
            field=models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three_more', 'Three or More'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='How many doses have you received to date?'),
        ),
        migrations.AlterField(
            model_name='historicalcovidinfectionhistory',
            name='swab_test_results',
            field=models.CharField(choices=[('positive_test', 'One or more positive test(s) '), ('negative_more_positive', 'One or more negative tests, but none were positive'), ('all_test_failed', 'All tests failed'), ('waiting_results', 'Waiting for all results'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If yes, What was the result/were the results of all swab tests you’ve had?'),
        ),
        migrations.AlterField(
            model_name='historicalcovidinfectionhistory',
            name='vaccine_provider',
            field=models.CharField(choices=[('government_uganda', 'Government of Uganda'), ('research_study', 'Research study/trial '), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If Yes who provided the vaccine'),
        ),
    ]
