# Generated by Django 3.1.7 on 2022-05-27 07:20

from django.db import migrations
import edcs_model.models.fields.other_charfield


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0029_auto_20220527_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcoholtobaccouse',
            name='tobacco_products_other',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='historicalalcoholtobaccouse',
            name='tobacco_products_other',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
    ]
