# Generated by Django 3.1.7 on 2022-07-05 07:54

from django.db import migrations, models
import edcs_model.models.fields.other_charfield


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0030_auto_20220527_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallabpartd',
            name='hiv_drug_resistance_other',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='labpartd',
            name='hiv_drug_resistance_other',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AlterField(
            model_name='historicallabpartd',
            name='hiv_dna_pcr',
            field=models.TextField(choices=[('POS', 'Positive'), ('NEG', 'Negative'), ('N/A', 'Not applicable')], default='N/A', verbose_name='HIV DNA PCR'),
        ),
        migrations.AlterField(
            model_name='labpartd',
            name='hiv_dna_pcr',
            field=models.TextField(choices=[('POS', 'Positive'), ('NEG', 'Negative'), ('N/A', 'Not applicable')], default='N/A', verbose_name='HIV DNA PCR'),
        ),
    ]
