# Generated by Django 3.1.7 on 2022-02-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0031_auto_20220217_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidinfectionhistory',
            name='admitted_hospital',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='Were you admitted to hospital when you thought you had COVID-19? '),
        ),
        migrations.AlterField(
            model_name='historicalcovidinfectionhistory',
            name='admitted_hospital',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='Were you admitted to hospital when you thought you had COVID-19? '),
        ),
    ]
