# Generated by Django 3.1.7 on 2022-07-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0032_historicalpostairquality_historicalpreairquality_postairquality_preairquality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpostairquality',
            name='smoke_inside_duration',
            field=models.CharField(choices=[('1_times', 'Once/day'), ('2_4_times', '2-4 times/day'), ('5_10_times', '5-10 times/day'), ('more_10_times', '>10 times/day'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If yes, how many times did people smoke tobacco products in this house?'),
        ),
        migrations.AlterField(
            model_name='postairquality',
            name='smoke_inside_duration',
            field=models.CharField(choices=[('1_times', 'Once/day'), ('2_4_times', '2-4 times/day'), ('5_10_times', '5-10 times/day'), ('more_10_times', '>10 times/day'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='If yes, how many times did people smoke tobacco products in this house?'),
        ),
    ]
