# Generated by Django 3.1.7 on 2022-02-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0033_auto_20220217_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographiccharacteristic',
            name='material_build_roof',
            field=models.CharField(choices=[('soil_sand_mud', 'Iron sheet/roofing tiles'), ('grass_leaves_soil', 'Grass/ leaves/ palm leaves/ soil'), ('OTHER', 'Others')], max_length=45, verbose_name='Which materials were used for roofing your house?'),
        ),
        migrations.AlterField(
            model_name='historicaldemographiccharacteristic',
            name='material_build_roof',
            field=models.CharField(choices=[('soil_sand_mud', 'Iron sheet/roofing tiles'), ('grass_leaves_soil', 'Grass/ leaves/ palm leaves/ soil'), ('OTHER', 'Others')], max_length=45, verbose_name='Which materials were used for roofing your house?'),
        ),
    ]
