# Generated by Django 3.1.7 on 2022-07-05 16:56

from django.db import migrations
import edcs_model.models.fields.other_charfield


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0033_auto_20220705_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpostairquality',
            name='solid_fuel_other',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='postairquality',
            name='solid_fuel_other',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
    ]
