# Generated by Django 3.1.7 on 2022-02-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0034_auto_20220217_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographiccharacteristic',
            name='education',
            field=models.CharField(choices=[('never_been_in_school', 'Never been in school'), ('primary_education', 'Completed Primary Education'), ('secondary_education', 'Completed Secondary Education (‘’O’’ or ‘’A’’ level)'), ('vocational_training', 'Vocational training'), ('tertiary_education', 'Tertiary Education'), ('OTHER', 'Other')], max_length=45, verbose_name='Education level?'),
        ),
        migrations.AlterField(
            model_name='historicaldemographiccharacteristic',
            name='education',
            field=models.CharField(choices=[('never_been_in_school', 'Never been in school'), ('primary_education', 'Completed Primary Education'), ('secondary_education', 'Completed Secondary Education (‘’O’’ or ‘’A’’ level)'), ('vocational_training', 'Vocational training'), ('tertiary_education', 'Tertiary Education'), ('OTHER', 'Other')], max_length=45, verbose_name='Education level?'),
        ),
    ]
