# Generated by Django 3.1.7 on 2022-08-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0035_auto_20220803_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='patient_visit_status',
            field=models.CharField(choices=[('respond_treatment', 'Responding to treatment'), ('no_changes', 'No changes'), ('not_respond_treatment', 'Not responding to treatment'), ('lost_follow_up', 'Lost to follow up'), ('died', 'Died ')], max_length=45, verbose_name='What is the patient status at this visit?'),
        ),
        migrations.AlterField(
            model_name='historicalfollowup',
            name='patient_visit_status',
            field=models.CharField(choices=[('respond_treatment', 'Responding to treatment'), ('no_changes', 'No changes'), ('not_respond_treatment', 'Not responding to treatment'), ('lost_follow_up', 'Lost to follow up'), ('died', 'Died ')], max_length=45, verbose_name='What is the patient status at this visit?'),
        ),
    ]
