# Generated by Django 3.1.7 on 2022-02-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0035_auto_20220217_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effectairpollution',
            name='who_had_illness',
            field=models.CharField(choices=[('child', 'Child'), ('husband', 'Husband'), ('wife', 'Wife'), ('OTHER', 'Other member of the house hold'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, please state, who had the illness'),
        ),
        migrations.AlterField(
            model_name='historicaleffectairpollution',
            name='who_had_illness',
            field=models.CharField(choices=[('child', 'Child'), ('husband', 'Husband'), ('wife', 'Wife'), ('OTHER', 'Other member of the house hold'), ('N/A', 'Not applicable')], max_length=45, verbose_name='If yes, please state, who had the illness'),
        ),
    ]
