# Generated by Django 3.1.7 on 2022-08-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0036_auto_20220803_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='respond_treatment',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=15, verbose_name="If the patient is not responding to treatment, has the patient's treatment changed?"),
        ),
        migrations.AlterField(
            model_name='historicalfollowup',
            name='respond_treatment',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], default='N/A', max_length=15, verbose_name="If the patient is not responding to treatment, has the patient's treatment changed?"),
        ),
    ]
