# Generated by Django 3.1.7 on 2022-09-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_lists', '0007_auto_20220913_1726'),
        ('edcs_subject', '0037_auto_20220822_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='signsymptomlungcancer',
            name='investigations_ordered_nw',
            field=models.ManyToManyField(to='edcs_lists.CancerInvestigation', verbose_name='While at cancer treatment facility, what investigations did the doctor(s) order in relation to the illness?'),
        ),
        migrations.AlterField(
            model_name='historicalsignsymptomlungcancer',
            name='investigations_ordered',
            field=models.CharField(choices=[('blood_tests', 'Blood tests'), ('chest_xray', 'Chest X-ray'), ('ct_scan', 'CT scan'), ('lung_cancer_biopsy', 'Lung cancer biopsy'), ('sputum_tb_dx', 'Sputum for TB diagnosis'), ('OTHER', 'Others'), ('none_of_above', 'None of the above')], max_length=45, null=True, verbose_name='While at cancer treatment facility, what investigations did the doctor(s) order in relation to the illness?'),
        ),
        migrations.AlterField(
            model_name='signsymptomlungcancer',
            name='investigations_ordered',
            field=models.CharField(choices=[('blood_tests', 'Blood tests'), ('chest_xray', 'Chest X-ray'), ('ct_scan', 'CT scan'), ('lung_cancer_biopsy', 'Lung cancer biopsy'), ('sputum_tb_dx', 'Sputum for TB diagnosis'), ('OTHER', 'Others'), ('none_of_above', 'None of the above')], max_length=45, null=True, verbose_name='While at cancer treatment facility, what investigations did the doctor(s) order in relation to the illness?'),
        ),
    ]
