# Generated by Django 3.1.7 on 2022-09-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_lists', '0009_auto_20220915_0327'),
        ('edcs_subject', '0040_auto_20220915_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='test_ordered_nw',
            field=models.ManyToManyField(to='edcs_lists.FollowUpTest', verbose_name='Have any test been ordered at this visit'),
        ),
    ]
