# Generated by Django 3.1.7 on 2023-01-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0042_auto_20221102_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='CBC_done',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='(WBC count, platelets and HB)', max_length=6, null=True, verbose_name='Has the patient done a CBC?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='CBC_no_results',
            field=models.TextField(blank=True, null=True, verbose_name='If you did not get a copy of the CBC results, Specify the reasons why?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='CBC_results',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=6, null=True, verbose_name='If yes,Did you get a copy of the CBC results?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='CT_scan_done',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='(after 6th cycle which is between 4-6 months, or after 4 cycles depending on age)', max_length=6, null=True, verbose_name='Has the CT scan been done?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='CT_scan_no_results',
            field=models.TextField(blank=True, null=True, verbose_name='If you did not get a copy of the CT scan results and CD, Specify the reasons why?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='CT_scan_results',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=6, null=True, verbose_name='If yes,Did you get a copy of the CT scan results and CD?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='anorexia_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had anorexia (After)?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='anorexia_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had anorexia (Before)?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='breathlessness_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had persistent breathlessness (After)'),
        ),
        migrations.AddField(
            model_name='followup',
            name='breathlessness_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had persistent breathlessness (Before)'),
        ),
        migrations.AddField(
            model_name='followup',
            name='chest_infections_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had chest infections that keep coming back such as bronchitis, pneumonia (After)? '),
        ),
        migrations.AddField(
            model_name='followup',
            name='chest_infections_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had chest infections that keep coming back such as bronchitis, pneumonia (Before)? '),
        ),
        migrations.AddField(
            model_name='followup',
            name='chest_pain_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had chest pain that is often worsen when breathing or coughing (After)?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='chest_pain_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had chest pain that is often worsen when breathing or coughing (Before)?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='cough_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name="Has the patient had a cough that doesn't go away (After)"),
        ),
        migrations.AddField(
            model_name='followup',
            name='cough_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name="Has the patient had a cough that doesn't go away (Before)"),
        ),
        migrations.AddField(
            model_name='followup',
            name='cough_get_worse_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='as the patient had a long-standing cough that gets worse (After)'),
        ),
        migrations.AddField(
            model_name='followup',
            name='cough_get_worse_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='as the patient had a long-standing cough that gets worse (Before)'),
        ),
        migrations.AddField(
            model_name='followup',
            name='coughing_blood_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient been coughing up blood or rust-colored sputum (spit or phlegm) (After)? '),
        ),
        migrations.AddField(
            model_name='followup',
            name='coughing_blood_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient been coughing up blood or rust-colored sputum (spit or phlegm) (Before)? '),
        ),
        migrations.AddField(
            model_name='followup',
            name='daily_activities_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient been able to do activities of daily living (After)?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='daily_activities_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient been able to do activities of daily living (Before)?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='dia_blood_pressure',
            field=models.IntegerField(help_text='in mmHg', null=True, verbose_name='Blood pressure: diastolic'),
        ),
        migrations.AddField(
            model_name='followup',
            name='hospitalized_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Is patient hospitalized (After)?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='hospitalized_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Is patient hospitalized (Before)?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='liver_renal_test_done',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='(mainly to assess for toxicity)', max_length=6, null=True, verbose_name='Has the patient done Liver Function Tests, Renal function tests?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='liver_renal_test_no_results',
            field=models.TextField(blank=True, null=True, verbose_name='If you did not get a copy of the Liver Function and Renal function tests results, Specify the reasons why?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='liver_renal_test_results',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=6, null=True, verbose_name='If yes,Did you get a copy of the Liver Function and Renal function tests results?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='pain_assess_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had pain (assess on a scale of 1-10) (After)'),
        ),
        migrations.AddField(
            model_name='followup',
            name='pain_assess_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had pain (assess on a scale of 1-10) (Before)'),
        ),
        migrations.AddField(
            model_name='followup',
            name='pulse',
            field=models.IntegerField(help_text='beats/min', null=True, verbose_name='Pulse'),
        ),
        migrations.AddField(
            model_name='followup',
            name='respiratory_rate',
            field=models.IntegerField(help_text='in breaths/min', null=True, verbose_name='Respiratory rate'),
        ),
        migrations.AddField(
            model_name='followup',
            name='shortness_breath_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had shortness of breath (After)'),
        ),
        migrations.AddField(
            model_name='followup',
            name='shortness_breath_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had shortness of breath (Before)'),
        ),
        migrations.AddField(
            model_name='followup',
            name='sys_blood_pressure',
            field=models.IntegerField(help_text='in mmHg', null=True, verbose_name='Blood pressure: systolic'),
        ),
        migrations.AddField(
            model_name='followup',
            name='temperature',
            field=models.DecimalField(decimal_places=1, help_text='in °C', max_digits=3, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='followup',
            name='tiredness_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had persistent tiredness or lack of energy (After)? '),
        ),
        migrations.AddField(
            model_name='followup',
            name='tiredness_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had persistent tiredness or lack of energy (Before)? '),
        ),
        migrations.AddField(
            model_name='followup',
            name='walk_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient been able to walk on their own (After)?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='walk_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient been able to walk on their own (Before)?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='weight',
            field=models.DecimalField(decimal_places=1, help_text='in Kg', max_digits=3, null=True, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='followup',
            name='wheezing_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient been wheezing (After)? '),
        ),
        migrations.AddField(
            model_name='followup',
            name='wheezing_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient been wheezing (Before)? '),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='CBC_done',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='(WBC count, platelets and HB)', max_length=6, null=True, verbose_name='Has the patient done a CBC?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='CBC_no_results',
            field=models.TextField(blank=True, null=True, verbose_name='If you did not get a copy of the CBC results, Specify the reasons why?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='CBC_results',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=6, null=True, verbose_name='If yes,Did you get a copy of the CBC results?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='CT_scan_done',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='(after 6th cycle which is between 4-6 months, or after 4 cycles depending on age)', max_length=6, null=True, verbose_name='Has the CT scan been done?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='CT_scan_no_results',
            field=models.TextField(blank=True, null=True, verbose_name='If you did not get a copy of the CT scan results and CD, Specify the reasons why?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='CT_scan_results',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=6, null=True, verbose_name='If yes,Did you get a copy of the CT scan results and CD?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='anorexia_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had anorexia (After)?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='anorexia_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had anorexia (Before)?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='breathlessness_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had persistent breathlessness (After)'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='breathlessness_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had persistent breathlessness (Before)'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='chest_infections_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had chest infections that keep coming back such as bronchitis, pneumonia (After)? '),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='chest_infections_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had chest infections that keep coming back such as bronchitis, pneumonia (Before)? '),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='chest_pain_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had chest pain that is often worsen when breathing or coughing (After)?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='chest_pain_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had chest pain that is often worsen when breathing or coughing (Before)?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='cough_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name="Has the patient had a cough that doesn't go away (After)"),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='cough_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name="Has the patient had a cough that doesn't go away (Before)"),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='cough_get_worse_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='as the patient had a long-standing cough that gets worse (After)'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='cough_get_worse_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='as the patient had a long-standing cough that gets worse (Before)'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='coughing_blood_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient been coughing up blood or rust-colored sputum (spit or phlegm) (After)? '),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='coughing_blood_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient been coughing up blood or rust-colored sputum (spit or phlegm) (Before)? '),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='daily_activities_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient been able to do activities of daily living (After)?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='daily_activities_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient been able to do activities of daily living (Before)?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='dia_blood_pressure',
            field=models.IntegerField(help_text='in mmHg', null=True, verbose_name='Blood pressure: diastolic'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='hospitalized_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Is patient hospitalized (After)?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='hospitalized_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Is patient hospitalized (Before)?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='liver_renal_test_done',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], help_text='(mainly to assess for toxicity)', max_length=6, null=True, verbose_name='Has the patient done Liver Function Tests, Renal function tests?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='liver_renal_test_no_results',
            field=models.TextField(blank=True, null=True, verbose_name='If you did not get a copy of the Liver Function and Renal function tests results, Specify the reasons why?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='liver_renal_test_results',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('N/A', 'Not applicable')], max_length=6, null=True, verbose_name='If yes,Did you get a copy of the Liver Function and Renal function tests results?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='pain_assess_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had pain (assess on a scale of 1-10) (After)'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='pain_assess_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had pain (assess on a scale of 1-10) (Before)'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='pulse',
            field=models.IntegerField(help_text='beats/min', null=True, verbose_name='Pulse'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='respiratory_rate',
            field=models.IntegerField(help_text='in breaths/min', null=True, verbose_name='Respiratory rate'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='shortness_breath_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had shortness of breath (After)'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='shortness_breath_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had shortness of breath (Before)'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='sys_blood_pressure',
            field=models.IntegerField(help_text='in mmHg', null=True, verbose_name='Blood pressure: systolic'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='temperature',
            field=models.DecimalField(decimal_places=1, help_text='in °C', max_digits=3, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='tiredness_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had persistent tiredness or lack of energy (After)? '),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='tiredness_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient had persistent tiredness or lack of energy (Before)? '),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='walk_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient been able to walk on their own (After)?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='walk_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient been able to walk on their own (Before)?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='weight',
            field=models.DecimalField(decimal_places=1, help_text='in Kg', max_digits=3, null=True, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='wheezing_after',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient been wheezing (After)? '),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='wheezing_before',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6, null=True, verbose_name='Has the patient been wheezing (Before)? '),
        ),
        migrations.AlterField(
            model_name='followup',
            name='test_ordered',
            field=models.CharField(blank=True, choices=[('chest_xray', 'Yes, chest X-ray'), ('ct_scan', 'Yes, CT scan'), ('ultrasound_scan', 'Yes, Ultrasound scan'), ('blood_cbc', 'Yes, Blood CBC'), ('chemistry_tests', 'Yes, Chemistry tests'), ('none', 'None'), ('OTHER', 'Other')], max_length=45, verbose_name='Have any test been ordered at this visit'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='test_ordered_result',
            field=models.TextField(blank=True, help_text='(Scan and upload all the results)', null=True, verbose_name='If yes, provide the results'),
        ),
        migrations.AlterField(
            model_name='historicalfollowup',
            name='test_ordered',
            field=models.CharField(blank=True, choices=[('chest_xray', 'Yes, chest X-ray'), ('ct_scan', 'Yes, CT scan'), ('ultrasound_scan', 'Yes, Ultrasound scan'), ('blood_cbc', 'Yes, Blood CBC'), ('chemistry_tests', 'Yes, Chemistry tests'), ('none', 'None'), ('OTHER', 'Other')], max_length=45, verbose_name='Have any test been ordered at this visit'),
        ),
        migrations.AlterField(
            model_name='historicalfollowup',
            name='test_ordered_result',
            field=models.TextField(blank=True, help_text='(Scan and upload all the results)', null=True, verbose_name='If yes, provide the results'),
        ),
    ]
