# Generated by Django 3.1.7 on 2023-02-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0043_auto_20230129_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='viral_load_cd4_off',
            field=models.IntegerField(blank=True, null=True, verbose_name='If positive, was the blood sample for viral load and CD4 taken off?'),
        ),
        migrations.AlterField(
            model_name='historicalfollowup',
            name='viral_load_cd4_off',
            field=models.IntegerField(blank=True, null=True, verbose_name='If positive, was the blood sample for viral load and CD4 taken off?'),
        ),
    ]
