# Generated by Django 3.1.7 on 2023-03-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0044_auto_20230201_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsocioeconomiccharacteristic',
            name='material_build_walls',
            field=models.CharField(choices=[('soil_sand_mud', 'There is no wall'), ('cement_concrete_tiles', 'Grass'), ('canes_palms', 'Canes/ Palm'), ('trees_mud', 'Trees and mud'), ('stone_mud', 'Stones and mud'), ('wood_timber', 'Wood/timber'), ('cement_concrete_bricks', 'Cement/ concrete blocks/ burnt blocks/bricks.'), ('OTHER', 'Others')], max_length=45, verbose_name='Which materials were used to build the walls of your house?'),
        ),
        migrations.AlterField(
            model_name='socioeconomiccharacteristic',
            name='material_build_walls',
            field=models.CharField(choices=[('soil_sand_mud', 'There is no wall'), ('cement_concrete_tiles', 'Grass'), ('canes_palms', 'Canes/ Palm'), ('trees_mud', 'Trees and mud'), ('stone_mud', 'Stones and mud'), ('wood_timber', 'Wood/timber'), ('cement_concrete_bricks', 'Cement/ concrete blocks/ burnt blocks/bricks.'), ('OTHER', 'Others')], max_length=45, verbose_name='Which materials were used to build the walls of your house?'),
        ),
    ]
