# Generated by Django 3.1.7 on 2023-05-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0046_auto_20230326_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpostairquality',
            name='cooking_fuel_used',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('kerosene', 'Kerosene'), ('charcoal', 'Charcoal'), ('coal', 'Coal'), ('gas ', 'Gas '), ('agricultural_crop', 'Agricultural crop'), ('wood', 'Wood'), ('gobar_gas ', 'Gobar gas '), ('electricity', 'Electricity'), ('straw_shrubs_grass ', 'Straw/shrubs/grass '), ('agricultural_crop', 'Agricultural crop'), ('animal_dung', 'Animal dung'), ('OTHER', 'Other')], max_length=45, verbose_name='During the air monitoring: What was the primary fuel used for cooking?'),
        ),
        migrations.AlterField(
            model_name='historicalpreairquality',
            name='cooking_fuel',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('kerosene', 'Kerosene'), ('charcoal', 'Charcoal'), ('coal', 'Coal'), ('gas ', 'Gas '), ('agricultural_crop', 'Agricultural crop'), ('wood', 'Wood'), ('gobar_gas ', 'Gobar gas '), ('electricity', 'Electricity'), ('straw_shrubs_grass ', 'Straw/shrubs/grass '), ('agricultural_crop', 'Agricultural crop'), ('animal_dung', 'Animal dung'), ('OTHER', 'Other')], max_length=45, verbose_name='What is the primary fuel currently used for cooking?'),
        ),
        migrations.AlterField(
            model_name='historicalpreairquality',
            name='previously_cooking_fuel',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('kerosene', 'Kerosene'), ('charcoal', 'Charcoal'), ('coal', 'Coal'), ('gas ', 'Gas '), ('agricultural_crop', 'Agricultural crop'), ('wood', 'Wood'), ('gobar_gas ', 'Gobar gas '), ('electricity', 'Electricity'), ('straw_shrubs_grass ', 'Straw/shrubs/grass '), ('agricultural_crop', 'Agricultural crop'), ('animal_dung', 'Animal dung'), ('OTHER', 'Other')], default='N/A', max_length=45, verbose_name='If yes, what was the previous primary fuel used for cooking?'),
        ),
        migrations.AlterField(
            model_name='postairquality',
            name='cooking_fuel_used',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('kerosene', 'Kerosene'), ('charcoal', 'Charcoal'), ('coal', 'Coal'), ('gas ', 'Gas '), ('agricultural_crop', 'Agricultural crop'), ('wood', 'Wood'), ('gobar_gas ', 'Gobar gas '), ('electricity', 'Electricity'), ('straw_shrubs_grass ', 'Straw/shrubs/grass '), ('agricultural_crop', 'Agricultural crop'), ('animal_dung', 'Animal dung'), ('OTHER', 'Other')], max_length=45, verbose_name='During the air monitoring: What was the primary fuel used for cooking?'),
        ),
        migrations.AlterField(
            model_name='preairquality',
            name='cooking_fuel',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('kerosene', 'Kerosene'), ('charcoal', 'Charcoal'), ('coal', 'Coal'), ('gas ', 'Gas '), ('agricultural_crop', 'Agricultural crop'), ('wood', 'Wood'), ('gobar_gas ', 'Gobar gas '), ('electricity', 'Electricity'), ('straw_shrubs_grass ', 'Straw/shrubs/grass '), ('agricultural_crop', 'Agricultural crop'), ('animal_dung', 'Animal dung'), ('OTHER', 'Other')], max_length=45, verbose_name='What is the primary fuel currently used for cooking?'),
        ),
        migrations.AlterField(
            model_name='preairquality',
            name='previously_cooking_fuel',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('kerosene', 'Kerosene'), ('charcoal', 'Charcoal'), ('coal', 'Coal'), ('gas ', 'Gas '), ('agricultural_crop', 'Agricultural crop'), ('wood', 'Wood'), ('gobar_gas ', 'Gobar gas '), ('electricity', 'Electricity'), ('straw_shrubs_grass ', 'Straw/shrubs/grass '), ('agricultural_crop', 'Agricultural crop'), ('animal_dung', 'Animal dung'), ('OTHER', 'Other')], default='N/A', max_length=45, verbose_name='If yes, what was the previous primary fuel used for cooking?'),
        ),
    ]
