# Generated by Django 3.1.7 on 2023-05-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0047_auto_20230531_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpostairquality',
            name='other_cooking_fuel_duration',
            field=models.IntegerField(help_text='Enter as minutes Eg 1hr = 60min', verbose_name='For how many hours were the other fuels used for cooking?'),
        ),
        migrations.AlterField(
            model_name='historicalpostairquality',
            name='primary_fuel_heating_duration',
            field=models.IntegerField(help_text='Enter as minutes Eg 1hr = 60min', verbose_name='For how many hours was the primary fuel used for heating?'),
        ),
        migrations.AlterField(
            model_name='postairquality',
            name='other_cooking_fuel_duration',
            field=models.IntegerField(help_text='Enter as minutes Eg 1hr = 60min', verbose_name='For how many hours were the other fuels used for cooking?'),
        ),
        migrations.AlterField(
            model_name='postairquality',
            name='primary_fuel_heating_duration',
            field=models.IntegerField(help_text='Enter as minutes Eg 1hr = 60min', verbose_name='For how many hours was the primary fuel used for heating?'),
        ),
    ]
