# Generated by Django 3.1.7 on 2023-07-02 10:56

from django.db import migrations, models
import edcs_model.models.fields.other_charfield


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_lists', '0010_auto_20230531_1738'),
        ('edcs_subject', '0048_auto_20230531_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcoholtobaccouse',
            name='no_cigarettes_smoked',
            field=models.IntegerField(blank=True, null=True, verbose_name='On average, how many Cigarettes do you/did you smoke?'),
        ),
        migrations.AddField(
            model_name='alcoholtobaccouse',
            name='no_cigars_smoked',
            field=models.IntegerField(blank=True, null=True, verbose_name='On average, how many Cigars do you/did you smoke?'),
        ),
        migrations.AddField(
            model_name='alcoholtobaccouse',
            name='no_pipe_smoked',
            field=models.IntegerField(blank=True, null=True, verbose_name='On average, how many Pipes do you/did you smoke?'),
        ),
        migrations.AddField(
            model_name='alcoholtobaccouse',
            name='no_shisha_smoked',
            field=models.IntegerField(blank=True, null=True, verbose_name='On average, how many Shisha do you/did you smoke?'),
        ),
        migrations.AddField(
            model_name='alcoholtobaccouse',
            name='smoking_frequency_cigarettes',
            field=models.CharField(choices=[('daily', 'Daily'), ('every_other_day', 'Every other day'), ('weekly', 'Weekly (Not daily)'), ('monthly', 'Monthly(Not weekly)'), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='How frequently do you smoke cigarettes?'),
        ),
        migrations.AddField(
            model_name='alcoholtobaccouse',
            name='smoking_frequency_cigars',
            field=models.CharField(choices=[('daily', 'Daily'), ('every_other_day', 'Every other day'), ('weekly', 'Weekly (Not daily)'), ('monthly', 'Monthly(Not weekly)'), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='How frequently do you smoke cigars?'),
        ),
        migrations.AddField(
            model_name='alcoholtobaccouse',
            name='smoking_frequency_other_cigarettes',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='alcoholtobaccouse',
            name='smoking_frequency_other_cigars',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='alcoholtobaccouse',
            name='smoking_frequency_other_pipes',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='alcoholtobaccouse',
            name='smoking_frequency_other_shisha',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='alcoholtobaccouse',
            name='smoking_frequency_pipes',
            field=models.CharField(choices=[('daily', 'Daily'), ('every_other_day', 'Every other day'), ('weekly', 'Weekly (Not daily)'), ('monthly', 'Monthly(Not weekly)'), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='How frequently do you smoke pipes?'),
        ),
        migrations.AddField(
            model_name='alcoholtobaccouse',
            name='smoking_frequency_shisha',
            field=models.CharField(choices=[('daily', 'Daily'), ('every_other_day', 'Every other day'), ('weekly', 'Weekly (Not daily)'), ('monthly', 'Monthly(Not weekly)'), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='How frequently do you smoke shisha?'),
        ),
        migrations.AddField(
            model_name='historicalalcoholtobaccouse',
            name='no_cigarettes_smoked',
            field=models.IntegerField(blank=True, null=True, verbose_name='On average, how many Cigarettes do you/did you smoke?'),
        ),
        migrations.AddField(
            model_name='historicalalcoholtobaccouse',
            name='no_cigars_smoked',
            field=models.IntegerField(blank=True, null=True, verbose_name='On average, how many Cigars do you/did you smoke?'),
        ),
        migrations.AddField(
            model_name='historicalalcoholtobaccouse',
            name='no_pipe_smoked',
            field=models.IntegerField(blank=True, null=True, verbose_name='On average, how many Pipes do you/did you smoke?'),
        ),
        migrations.AddField(
            model_name='historicalalcoholtobaccouse',
            name='no_shisha_smoked',
            field=models.IntegerField(blank=True, null=True, verbose_name='On average, how many Shisha do you/did you smoke?'),
        ),
        migrations.AddField(
            model_name='historicalalcoholtobaccouse',
            name='smoking_frequency_cigarettes',
            field=models.CharField(choices=[('daily', 'Daily'), ('every_other_day', 'Every other day'), ('weekly', 'Weekly (Not daily)'), ('monthly', 'Monthly(Not weekly)'), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='How frequently do you smoke cigarettes?'),
        ),
        migrations.AddField(
            model_name='historicalalcoholtobaccouse',
            name='smoking_frequency_cigars',
            field=models.CharField(choices=[('daily', 'Daily'), ('every_other_day', 'Every other day'), ('weekly', 'Weekly (Not daily)'), ('monthly', 'Monthly(Not weekly)'), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='How frequently do you smoke cigars?'),
        ),
        migrations.AddField(
            model_name='historicalalcoholtobaccouse',
            name='smoking_frequency_other_cigarettes',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='historicalalcoholtobaccouse',
            name='smoking_frequency_other_cigars',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='historicalalcoholtobaccouse',
            name='smoking_frequency_other_pipes',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='historicalalcoholtobaccouse',
            name='smoking_frequency_other_shisha',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, max_length=35, null=True, verbose_name='If other, please specify ...'),
        ),
        migrations.AddField(
            model_name='historicalalcoholtobaccouse',
            name='smoking_frequency_pipes',
            field=models.CharField(choices=[('daily', 'Daily'), ('every_other_day', 'Every other day'), ('weekly', 'Weekly (Not daily)'), ('monthly', 'Monthly(Not weekly)'), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='How frequently do you smoke pipes?'),
        ),
        migrations.AddField(
            model_name='historicalalcoholtobaccouse',
            name='smoking_frequency_shisha',
            field=models.CharField(choices=[('daily', 'Daily'), ('every_other_day', 'Every other day'), ('weekly', 'Weekly (Not daily)'), ('monthly', 'Monthly(Not weekly)'), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, verbose_name='How frequently do you smoke shisha?'),
        ),
        migrations.AlterField(
            model_name='alcoholtobaccouse',
            name='smoking_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('every_other_day', 'Every other day'), ('weekly', 'Weekly (Not daily)'), ('monthly', 'Monthly(Not weekly)'), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, null=True, verbose_name='How frequently do you smoke these products?'),
        ),
        migrations.AlterField(
            model_name='historicalalcoholtobaccouse',
            name='smoking_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('every_other_day', 'Every other day'), ('weekly', 'Weekly (Not daily)'), ('monthly', 'Monthly(Not weekly)'), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, null=True, verbose_name='How frequently do you smoke these products?'),
        ),
        migrations.AlterField(
            model_name='postairquality',
            name='solid_fuel',
            field=models.ManyToManyField(to='edcs_lists.SolidFuelNew', verbose_name='If you used solid fuel (charcoal, wood, coal, agriculture/crop, animal dung or shrub/grass) as primary fuel or other fuel for cooking, what type of stove did you use these fuels in?'),
        ),
    ]
