# Generated by Django 3.1.7 on 2024-03-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_lists', '0011_auto_20240305_1654'),
        ('edcs_subject', '0051_auto_20231109_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='labpartc',
            name='histochemistry_new',
            field=models.ManyToManyField(related_name='histochemistry', to='edcs_lists.Immunohistochemistry', verbose_name='Histochemistry'),
        ),
        migrations.AddField(
            model_name='labpartc',
            name='immunohistochemistry_new',
            field=models.ManyToManyField(related_name='immunohistochemistry', to='edcs_lists.Immunohistochemistry', verbose_name='Immunohistochemistry'),
        ),
        migrations.AlterField(
            model_name='historicallabpartc',
            name='histochemistry',
            field=models.CharField(blank=True, choices=[('POS_TTF1', 'Positive- TTF1'), ('POS_P40', 'Positive- P40'), ('POS_P63', 'Positive- P63'), ('POS_PANCYTOKERATINE', 'Positive- PANCYTOKERATINE'), ('POS_CK20', 'Positive- CK20'), ('POS_CK7', 'Positive- CK7'), ('POS_CK5_6', 'Positive- CK5/6'), ('NEG', 'Negative'), ('not_done', 'Note done')], max_length=45, null=True, verbose_name='Histochemistry'),
        ),
        migrations.AlterField(
            model_name='historicallabpartc',
            name='immunohistochemistry',
            field=models.CharField(blank=True, choices=[('POS_TTF1', 'Positive- TTF1'), ('POS_P40', 'Positive- P40'), ('POS_P63', 'Positive- P63'), ('POS_PANCYTOKERATINE', 'Positive- PANCYTOKERATINE'), ('POS_CK20', 'Positive- CK20'), ('POS_CK7', 'Positive- CK7'), ('POS_CK5_6', 'Positive- CK5/6'), ('NEG', 'Negative'), ('not_done', 'Note done')], max_length=45, null=True, verbose_name='Immunohistochemistry'),
        ),
        migrations.AlterField(
            model_name='labpartc',
            name='histochemistry',
            field=models.CharField(blank=True, choices=[('POS_TTF1', 'Positive- TTF1'), ('POS_P40', 'Positive- P40'), ('POS_P63', 'Positive- P63'), ('POS_PANCYTOKERATINE', 'Positive- PANCYTOKERATINE'), ('POS_CK20', 'Positive- CK20'), ('POS_CK7', 'Positive- CK7'), ('POS_CK5_6', 'Positive- CK5/6'), ('NEG', 'Negative'), ('not_done', 'Note done')], max_length=45, null=True, verbose_name='Histochemistry'),
        ),
        migrations.AlterField(
            model_name='labpartc',
            name='immunohistochemistry',
            field=models.CharField(blank=True, choices=[('POS_TTF1', 'Positive- TTF1'), ('POS_P40', 'Positive- P40'), ('POS_P63', 'Positive- P63'), ('POS_PANCYTOKERATINE', 'Positive- PANCYTOKERATINE'), ('POS_CK20', 'Positive- CK20'), ('POS_CK7', 'Positive- CK7'), ('POS_CK5_6', 'Positive- CK5/6'), ('NEG', 'Negative'), ('not_done', 'Note done')], max_length=45, null=True, verbose_name='Immunohistochemistry'),
        ),
    ]
