# Generated by Django 3.1.7 on 2024-03-05 17:48

from django.db import migrations
import edcs_model.models.fields.other_charfield


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0052_auto_20240305_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalreview',
            name='tb_dx',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, choices=[('yes_clinically', 'Yes clinically'), ('Yes_bacteriologically', 'Yes bacteriologically confirmed'), ('No', 'No')], max_length=65, null=True, verbose_name='Have you ever been diagnosed with TB?'),
        ),
        migrations.AddField(
            model_name='historicalclinicalreview',
            name='tb_dx',
            field=edcs_model.models.fields.other_charfield.OtherCharField(blank=True, choices=[('yes_clinically', 'Yes clinically'), ('Yes_bacteriologically', 'Yes bacteriologically confirmed'), ('No', 'No')], max_length=65, null=True, verbose_name='Have you ever been diagnosed with TB?'),
        ),
    ]
