# Generated by Django 3.1.7 on 2024-04-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0054_auto_20240305_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='condition_interfered_family',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Has your physical condition or medical treatment interfered with your family life?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='condition_interfered_financial',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Has your physical condition or medical treatment caused you financial difficulties?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='condition_interfered_social',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Has your physical condition or medical treatment interfered with your social activities?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='constipated',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Have you been constipated?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='depressed',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Did you feel depressed'),
        ),
        migrations.AddField(
            model_name='followup',
            name='diarrhea',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Have you had diarrhea?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='difficulty_concentrating',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Have you had difficulty in concentrating on things, like reading a newspaper or watching television?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='difficulty_remembering',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Have you had difficulty remembering things?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='feel_irritable',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Did you feel irritable?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='feel_tense',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Did you feel tense?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='felt_nauseated',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Have you felt nauseated?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='felt_weak',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Have you felt weak?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='had_pain',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Have you had pain?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='lacked_appetite',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Have you lacked appetite?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='limited_daily_activities',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Were you limited in doing either your work or other daily activities?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='limited_leisure_activities',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Were you limited in pursuing your hobbies or other leisure time activities?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='long_walk',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Do you have any trouble taking a long walk?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='need_help',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Do you need help with eating, dressing, washing yourself or using the toilet?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='need_rest',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Did you need to rest?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='other_presenting_symptoms',
            field=models.TextField(blank=True, null=True, verbose_name='Any other presenting symptoms please specify?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='pain_interfere_activities',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Did pain interfere with your daily activities?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='rate_overall_health',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], help_text='1 be very poor and 7 be excellent', max_length=15, null=True, verbose_name='How would you rate your overall health during the past week?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='rate_overall_quality_life',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], help_text='1 be very poor and 7 be excellent', max_length=15, null=True, verbose_name='How would you rate your overall quality of life during the past week?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='short_breath',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Were you short of breath?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='short_walk',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Do you have any trouble taking a short walk outside of the house?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='stay_bed_chair',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Do you need to stay in bed or a chair during the day?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='strenuous_activities',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Do you have any trouble doing strenuous activities,like carrying a heavy shopping bag or a suitcase?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='tired',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Were you tired?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='trouble_sleeping',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Have you had trouble sleeping?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='vomited',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Have you vomited?'),
        ),
        migrations.AddField(
            model_name='followup',
            name='worry',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Did you worry'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='condition_interfered_family',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Has your physical condition or medical treatment interfered with your family life?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='condition_interfered_financial',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Has your physical condition or medical treatment caused you financial difficulties?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='condition_interfered_social',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Has your physical condition or medical treatment interfered with your social activities?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='constipated',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Have you been constipated?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='depressed',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Did you feel depressed'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='diarrhea',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Have you had diarrhea?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='difficulty_concentrating',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Have you had difficulty in concentrating on things, like reading a newspaper or watching television?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='difficulty_remembering',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Have you had difficulty remembering things?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='feel_irritable',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Did you feel irritable?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='feel_tense',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Did you feel tense?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='felt_nauseated',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Have you felt nauseated?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='felt_weak',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Have you felt weak?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='had_pain',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Have you had pain?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='lacked_appetite',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Have you lacked appetite?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='limited_daily_activities',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Were you limited in doing either your work or other daily activities?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='limited_leisure_activities',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Were you limited in pursuing your hobbies or other leisure time activities?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='long_walk',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Do you have any trouble taking a long walk?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='need_help',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Do you need help with eating, dressing, washing yourself or using the toilet?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='need_rest',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Did you need to rest?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='other_presenting_symptoms',
            field=models.TextField(blank=True, null=True, verbose_name='Any other presenting symptoms please specify?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='pain_interfere_activities',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Did pain interfere with your daily activities?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='rate_overall_health',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], help_text='1 be very poor and 7 be excellent', max_length=15, null=True, verbose_name='How would you rate your overall health during the past week?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='rate_overall_quality_life',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], help_text='1 be very poor and 7 be excellent', max_length=15, null=True, verbose_name='How would you rate your overall quality of life during the past week?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='short_breath',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Were you short of breath?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='short_walk',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Do you have any trouble taking a short walk outside of the house?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='stay_bed_chair',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Do you need to stay in bed or a chair during the day?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='strenuous_activities',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Do you have any trouble doing strenuous activities,like carrying a heavy shopping bag or a suitcase?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='tired',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Were you tired?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='trouble_sleeping',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Have you had trouble sleeping?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='vomited',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Have you vomited?'),
        ),
        migrations.AddField(
            model_name='historicalfollowup',
            name='worry',
            field=models.CharField(choices=[('not_at_all', 'Not at All'), ('little', 'A Little'), ('quite_bit', 'Quite a Bit'), ('very_much', 'Very Much')], max_length=15, null=True, verbose_name='Did you worry'),
        ),
    ]
