# Generated by Django 3.1.7 on 2024-04-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0055_auto_20240410_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='rate_overall_health',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], help_text='1 be very poor and 7 be excellent', max_length=15, null=True, verbose_name='How would you rate your overall health during the past week?'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='rate_overall_quality_life',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], help_text='1 be very poor and 7 be excellent', max_length=15, null=True, verbose_name='How would you rate your overall quality of life during the past week?'),
        ),
        migrations.AlterField(
            model_name='historicalfollowup',
            name='rate_overall_health',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], help_text='1 be very poor and 7 be excellent', max_length=15, null=True, verbose_name='How would you rate your overall health during the past week?'),
        ),
        migrations.AlterField(
            model_name='historicalfollowup',
            name='rate_overall_quality_life',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], help_text='1 be very poor and 7 be excellent', max_length=15, null=True, verbose_name='How would you rate your overall quality of life during the past week?'),
        ),
    ]
