# Generated by Django 3.1.7 on 2024-06-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_lists', '0012_auto_20240618_1739'),
        ('edcs_subject', '0057_genotypiccancerprofile_historicalgenotypiccancerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='genotypiccancerprofile',
            name='amino_acid_change',
            field=models.TextField(null=True, verbose_name='Amino Acid Change'),
        ),
        migrations.AddField(
            model_name='genotypiccancerprofile',
            name='genotype',
            field=models.TextField(null=True, verbose_name='Genotype'),
        ),
        migrations.AddField(
            model_name='genotypiccancerprofile',
            name='oncomine_variant',
            field=models.ManyToManyField(null=True, to='edcs_lists.OncomineVariantClass', verbose_name='Oncomine Variant Class'),
        ),
        migrations.AddField(
            model_name='historicalgenotypiccancerprofile',
            name='amino_acid_change',
            field=models.TextField(null=True, verbose_name='Amino Acid Change'),
        ),
        migrations.AddField(
            model_name='historicalgenotypiccancerprofile',
            name='genotype',
            field=models.TextField(null=True, verbose_name='Genotype'),
        ),
        migrations.AlterField(
            model_name='genotypiccancerprofile',
            name='allele_frequency',
            field=models.IntegerField(blank=True, null=True, verbose_name='Allele Frequency'),
        ),
        migrations.AlterField(
            model_name='genotypiccancerprofile',
            name='cancer_type',
            field=models.CharField(max_length=45, null=True, verbose_name='Cancer Type'),
        ),
        migrations.AlterField(
            model_name='genotypiccancerprofile',
            name='coverage',
            field=models.IntegerField(null=True, verbose_name='Coverage'),
        ),
        migrations.AlterField(
            model_name='genotypiccancerprofile',
            name='date_received',
            field=models.DateTimeField(null=True, verbose_name='Date Received'),
        ),
        migrations.AlterField(
            model_name='genotypiccancerprofile',
            name='variant_class',
            field=models.CharField(max_length=45, null=True, verbose_name='Variant Class'),
        ),
        migrations.AlterField(
            model_name='historicalgenotypiccancerprofile',
            name='allele_frequency',
            field=models.IntegerField(blank=True, null=True, verbose_name='Allele Frequency'),
        ),
        migrations.AlterField(
            model_name='historicalgenotypiccancerprofile',
            name='cancer_type',
            field=models.CharField(max_length=45, null=True, verbose_name='Cancer Type'),
        ),
        migrations.AlterField(
            model_name='historicalgenotypiccancerprofile',
            name='coverage',
            field=models.IntegerField(null=True, verbose_name='Coverage'),
        ),
        migrations.AlterField(
            model_name='historicalgenotypiccancerprofile',
            name='date_received',
            field=models.DateTimeField(null=True, verbose_name='Date Received'),
        ),
        migrations.AlterField(
            model_name='historicalgenotypiccancerprofile',
            name='variant_class',
            field=models.CharField(max_length=45, null=True, verbose_name='Variant Class'),
        ),
    ]
