# Generated by Django 3.1.7 on 2024-06-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0058_auto_20240618_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genotypiccancerprofile',
            name='allele_frequency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Allele Frequency'),
        ),
        migrations.AlterField(
            model_name='historicalgenotypiccancerprofile',
            name='allele_frequency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Allele Frequency'),
        ),
    ]
