# Generated by Django 3.1.7 on 2024-07-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0059_auto_20240620_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='genotypiccancerprofile',
            name='assay_status',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('amplified_dna_rna', 'Amplified DNA & RNA'), ('failed_dna_rna', 'Failed DNA & RNA'), ('amplified_dna_only', 'Amplified DNA only'), ('amplified_rna_only', 'Amplified RNA only')], max_length=45, null=True, verbose_name='Assay Status'),
        ),
        migrations.AddField(
            model_name='genotypiccancerprofile',
            name='gene',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Gene'),
        ),
        migrations.AddField(
            model_name='historicalgenotypiccancerprofile',
            name='assay_status',
            field=models.CharField(choices=[('N/A', 'Not applicable'), ('amplified_dna_rna', 'Amplified DNA & RNA'), ('failed_dna_rna', 'Failed DNA & RNA'), ('amplified_dna_only', 'Amplified DNA only'), ('amplified_rna_only', 'Amplified RNA only')], max_length=45, null=True, verbose_name='Assay Status'),
        ),
        migrations.AddField(
            model_name='historicalgenotypiccancerprofile',
            name='gene',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Gene'),
        ),
        migrations.AlterField(
            model_name='genotypiccancerprofile',
            name='amino_acid_change',
            field=models.TextField(blank=True, null=True, verbose_name='Amino Acid Change'),
        ),
        migrations.AlterField(
            model_name='genotypiccancerprofile',
            name='cancer_type',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Cancer Type'),
        ),
        migrations.AlterField(
            model_name='genotypiccancerprofile',
            name='coverage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Coverage'),
        ),
        migrations.AlterField(
            model_name='genotypiccancerprofile',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Received'),
        ),
        migrations.AlterField(
            model_name='genotypiccancerprofile',
            name='genomic_alteration',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Genomic Alteration'),
        ),
        migrations.AlterField(
            model_name='genotypiccancerprofile',
            name='genotype',
            field=models.TextField(blank=True, null=True, verbose_name='Genotype'),
        ),
        migrations.AlterField(
            model_name='genotypiccancerprofile',
            name='sample_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sample Type'),
        ),
        migrations.AlterField(
            model_name='genotypiccancerprofile',
            name='variant_class',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Variant Class'),
        ),
        migrations.AlterField(
            model_name='historicalgenotypiccancerprofile',
            name='amino_acid_change',
            field=models.TextField(blank=True, null=True, verbose_name='Amino Acid Change'),
        ),
        migrations.AlterField(
            model_name='historicalgenotypiccancerprofile',
            name='cancer_type',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Cancer Type'),
        ),
        migrations.AlterField(
            model_name='historicalgenotypiccancerprofile',
            name='coverage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Coverage'),
        ),
        migrations.AlterField(
            model_name='historicalgenotypiccancerprofile',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Received'),
        ),
        migrations.AlterField(
            model_name='historicalgenotypiccancerprofile',
            name='genomic_alteration',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Genomic Alteration'),
        ),
        migrations.AlterField(
            model_name='historicalgenotypiccancerprofile',
            name='genotype',
            field=models.TextField(blank=True, null=True, verbose_name='Genotype'),
        ),
        migrations.AlterField(
            model_name='historicalgenotypiccancerprofile',
            name='sample_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sample Type'),
        ),
        migrations.AlterField(
            model_name='historicalgenotypiccancerprofile',
            name='variant_class',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Variant Class'),
        ),
    ]
