# Generated by Django 3.1.7 on 2024-08-04 19:04

import _socket
from django.db import migrations, models
import django.db.models.deletion
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_audit_fields.models.audit_model_mixin
import django_revision.revision_field
import edcs_utils.date


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_lists', '0012_auto_20240618_1739'),
        ('edcs_subject', '0060_auto_20240708_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genotypic',
            fields=[
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('created', models.DateTimeField(blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow)),
                ('modified', models.DateTimeField(blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow)),
                ('user_created', django_audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', django_audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', django_audit_fields.fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', django_audit_fields.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('report_datetime', models.DateTimeField(default=edcs_utils.date.get_utcnow, help_text='Date and time of report.', verbose_name='Report Date and Time')),
                ('assay_status', models.CharField(choices=[('N/A', 'Not applicable'), ('amplified_dna_rna', 'Amplified DNA & RNA'), ('failed_dna_rna', 'Failed DNA & RNA'), ('amplified_dna_only', 'Amplified DNA only'), ('amplified_rna_only', 'Amplified RNA only')], max_length=45, null=True, verbose_name='Assay Status')),
                ('gene', models.CharField(blank=True, max_length=45, null=True, verbose_name='Gene')),
                ('genotype', models.TextField(blank=True, null=True, verbose_name='Genotype')),
                ('amino_acid_change', models.TextField(blank=True, null=True, verbose_name='Amino Acid Change')),
                ('coverage', models.IntegerField(blank=True, null=True, verbose_name='Coverage')),
                ('allele_frequency', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Allele Frequency')),
                ('sample_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sample Type')),
                ('date_received', models.DateTimeField(blank=True, null=True, verbose_name='Date Received')),
                ('cancer_type', models.CharField(blank=True, max_length=45, null=True, verbose_name='Cancer Type')),
                ('genomic_alteration', models.CharField(blank=True, max_length=45, null=True, verbose_name='Genomic Alteration')),
                ('variant_class', models.CharField(blank=True, max_length=45, null=True, verbose_name='Variant Class')),
                ('biomarker_this_cancer', models.TextField(blank=True, help_text='In this cancer type', null=True, verbose_name='Biomarker-based Relevant Therapies')),
                ('biomarker_other_cancer', models.TextField(blank=True, help_text='In other cancer type', null=True, verbose_name='Biomarker-based Relevant Therapies')),
                ('oncomine_variant', models.ManyToManyField(null=True, to='edcs_lists.OncomineVariantClass', verbose_name='Oncomine Variant Class')),
                ('subject_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genotypic', to='edcs_subject.subjectvisit', verbose_name='Subject Visit')),
            ],
            options={
                'verbose_name': 'Genotypic Cancer Profile',
                'verbose_name_plural': 'Genotypic Cancer Profile',
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import'),
            },
        ),
    ]
