# Generated by Django 3.1.7 on 2024-08-08 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0061_genotypic'),
    ]

    operations = [
        migrations.AddField(
            model_name='genotypic',
            name='subject_identifier',
            field=models.CharField(blank=True, max_length=45, verbose_name='Subject Identifier'),
        ),
        migrations.AlterField(
            model_name='genotypic',
            name='subject_visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genotypic', to='edcs_subject.subjectvisit', verbose_name='Subject Visit'),
        ),
    ]
