# Generated by Django 3.1.7 on 2024-08-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0062_auto_20240808_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genotypic',
            name='subject_identifier',
            field=models.CharField(max_length=45, verbose_name='Subject Identifier'),
        ),
    ]
