# Generated by Django 3.1.7 on 2024-08-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0063_auto_20240808_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genotypic',
            name='subject_identifier',
            field=models.CharField(editable=False, max_length=45, verbose_name='Subject Identifier'),
        ),
    ]
