# Generated by Django 3.1.7 on 2024-08-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0066_auto_20240808_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genotypic',
            name='subject_identifier',
            field=models.CharField(max_length=45, verbose_name='Subject Identifier'),
        ),
    ]
