# Generated by Django 3.1.7 on 2025-08-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_lists', '0013_auto_20250812_2053'),
        ('edcs_subject', '0067_auto_20240808_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='lungcancertreatment',
            name='treatment_new',
            field=models.ManyToManyField(to='edcs_lists.LungCancerTreatmentClass', verbose_name='Type of treatment?'),
        ),
        migrations.AlterField(
            model_name='historicallungcancertreatment',
            name='treatment',
            field=models.CharField(choices=[('chemotherapy', 'Chemotherapy'), ('radiation', 'Radiation'), ('surgical_resection', 'Surgical resection'), ('immunotherapy', 'Immunotherapy'), ('tyrosine_kinase_inhibitor', 'Tyrosine kinase inhibitor '), ('1_2above', '1 & 2 above'), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, null=True, verbose_name='Type of treatment?'),
        ),
        migrations.AlterField(
            model_name='lungcancertreatment',
            name='treatment',
            field=models.CharField(choices=[('chemotherapy', 'Chemotherapy'), ('radiation', 'Radiation'), ('surgical_resection', 'Surgical resection'), ('immunotherapy', 'Immunotherapy'), ('tyrosine_kinase_inhibitor', 'Tyrosine kinase inhibitor '), ('1_2above', '1 & 2 above'), ('OTHER', 'Others'), ('N/A', 'Not applicable')], default='N/A', max_length=45, null=True, verbose_name='Type of treatment?'),
        ),
    ]
