# Generated by Django 3.1.7 on 2025-08-13 05:55

import _socket
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_audit_fields.models.audit_model_mixin
import django_revision.revision_field
import simple_history.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edcs_subject', '0069_auto_20250813_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemotherapyDrugs',
            fields=[
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('created', models.DateTimeField(blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow)),
                ('modified', models.DateTimeField(blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow)),
                ('user_created', django_audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', django_audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', django_audit_fields.fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', django_audit_fields.fields.uuid_auto_field.UUIDAutoField(blank=True, editable=False, help_text='System auto field. UUID primary key.', primary_key=True, serialize=False)),
                ('chemotherapy_drug', models.CharField(choices=[('carboplatin', 'Carboplatin'), ('paclitaxel', 'Paclitaxel'), ('cisplatin', 'Cisplatin'), ('pemetrexed', 'Pemetrexed'), ('bevacizumab', 'Bevacizumab'), ('erlotinib', 'Erlotinib'), ('etoposide', 'Etoposide'), ('vincristine', 'Vincristine'), ('osimetinib', 'Osimetinib'), ('crizotinib', 'Crizotinib')], max_length=45, verbose_name='Chemotherapy Drug')),
                ('number_of_cycles', models.IntegerField(verbose_name='Number of cycles')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('lung_cancer_treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemotherapy_drugs', to='edcs_subject.lungcancertreatment')),
            ],
            options={
                'verbose_name': 'Chemotherapy Drug',
                'verbose_name_plural': 'Chemotherapy Drugs',
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
                'default_permissions': ('add', 'change', 'delete', 'view', 'export', 'import'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalChemotherapyDrugs',
            fields=[
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('created', models.DateTimeField(blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow)),
                ('modified', models.DateTimeField(blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow)),
                ('user_created', django_audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user created')),
                ('user_modified', django_audit_fields.fields.userfield.UserField(blank=True, help_text='Updated by admin.save_model', max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(blank=True, default=_socket.gethostname, help_text='System field. (modified on create only)', max_length=60)),
                ('hostname_modified', django_audit_fields.fields.hostname_modification_field.HostnameModificationField(blank=True, help_text='System field. (modified on every save)', max_length=50)),
                ('device_created', models.CharField(blank=True, max_length=10)),
                ('device_modified', models.CharField(blank=True, max_length=10)),
                ('id', django_audit_fields.fields.uuid_auto_field.UUIDAutoField(blank=True, db_index=True, editable=False, help_text='System auto field. UUID primary key.')),
                ('chemotherapy_drug', models.CharField(choices=[('carboplatin', 'Carboplatin'), ('paclitaxel', 'Paclitaxel'), ('cisplatin', 'Cisplatin'), ('pemetrexed', 'Pemetrexed'), ('bevacizumab', 'Bevacizumab'), ('erlotinib', 'Erlotinib'), ('etoposide', 'Etoposide'), ('vincristine', 'Vincristine'), ('osimetinib', 'Osimetinib'), ('crizotinib', 'Crizotinib')], max_length=45, verbose_name='Chemotherapy Drug')),
                ('number_of_cycles', models.IntegerField(verbose_name='Number of cycles')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lung_cancer_treatment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='edcs_subject.lungcancertreatment')),
            ],
            options={
                'verbose_name': 'historical Chemotherapy Drug',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='historicalchemotherapydrug',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalchemotherapydrug',
            name='lung_cancer_treatment',
        ),
        migrations.RemoveField(
            model_name='historicalchemotherapydrug',
            name='site',
        ),
        migrations.RemoveField(
            model_name='historicalchemotherapydrug',
            name='subject_visit',
        ),
        migrations.DeleteModel(
            name='ChemotherapyDrug',
        ),
        migrations.DeleteModel(
            name='HistoricalChemotherapyDrug',
        ),
    ]
