# Generated by Django 3.1.7 on 2025-08-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0070_auto_20250813_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallungcancertreatment',
            name='other_intervention',
            field=models.CharField(default='', max_length=45, verbose_name='Other intervention given to lung cancer patients?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lungcancertreatment',
            name='other_intervention',
            field=models.CharField(default='', max_length=45, verbose_name='Other intervention given to lung cancer patients?'),
            preserve_default=False,
        ),
    ]
