# Generated by Django 3.1.7 on 2025-08-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_lists', '0014_auto_20250813_0814'),
        ('edcs_subject', '0071_auto_20250813_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='lungcancertreatment',
            name='other_interventions',
            field=models.ManyToManyField(to='edcs_lists.OtherInterventionClass', verbose_name='Other intervention given to lung cancer patients?'),
        ),
        migrations.AlterField(
            model_name='historicallungcancertreatment',
            name='other_intervention',
            field=models.CharField(max_length=45, null=True, verbose_name='Other intervention given to lung cancer patients?'),
        ),
        migrations.AlterField(
            model_name='lungcancertreatment',
            name='other_intervention',
            field=models.CharField(max_length=45, null=True, verbose_name='Other intervention given to lung cancer patients?'),
        ),
    ]
