# Generated by Django 3.1.7 on 2025-08-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0072_auto_20250813_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemotherapydrugs',
            name='chemotherapy_drug',
            field=models.CharField(choices=[('carboplatin', 'Carboplatin'), ('paclitaxel', 'Paclitaxel'), ('cisplatin', 'Cisplatin'), ('pemetrexed', 'Pemetrexed'), ('bevacizumab', 'Bevacizumab'), ('etoposide', 'Etoposide'), ('vincristine', 'Vincristine'), ('pembrolizumab', 'Pembrolizumab (Keytruda)'), ('nivolumab', 'Nivolumab (Opdivo)'), ('atezolizumab', 'Atezolizumab (Tecentriq)'), ('durvalumab', 'Durvalumab (Imfinzi)'), ('ipilimumab', 'Ipilimumab (Yervoy)'), ('osimetinib', 'Osimertinib (Tagrisso)'), ('erlotinib', 'Erlotinib (Tarceva)'), ('erlotinib', 'Erlotinib (Tarceva)'), ('gefitinib', 'Gefitinib (Iressa)'), ('afatinib', 'Afatinib (Gilotrif)'), ('alectinib', 'Alectinib (Alecensa)'), ('crizotinib', 'Crizotinib (Xalkori)'), ('entrectinib', 'Entrectinib (Rozlytrek)')], max_length=45, verbose_name='Chemotherapy Drug'),
        ),
        migrations.AlterField(
            model_name='historicalchemotherapydrugs',
            name='chemotherapy_drug',
            field=models.CharField(choices=[('carboplatin', 'Carboplatin'), ('paclitaxel', 'Paclitaxel'), ('cisplatin', 'Cisplatin'), ('pemetrexed', 'Pemetrexed'), ('bevacizumab', 'Bevacizumab'), ('etoposide', 'Etoposide'), ('vincristine', 'Vincristine'), ('pembrolizumab', 'Pembrolizumab (Keytruda)'), ('nivolumab', 'Nivolumab (Opdivo)'), ('atezolizumab', 'Atezolizumab (Tecentriq)'), ('durvalumab', 'Durvalumab (Imfinzi)'), ('ipilimumab', 'Ipilimumab (Yervoy)'), ('osimetinib', 'Osimertinib (Tagrisso)'), ('erlotinib', 'Erlotinib (Tarceva)'), ('erlotinib', 'Erlotinib (Tarceva)'), ('gefitinib', 'Gefitinib (Iressa)'), ('afatinib', 'Afatinib (Gilotrif)'), ('alectinib', 'Alectinib (Alecensa)'), ('crizotinib', 'Crizotinib (Xalkori)'), ('entrectinib', 'Entrectinib (Rozlytrek)')], max_length=45, verbose_name='Chemotherapy Drug'),
        ),
    ]
