# Generated by Django 3.1.7 on 2025-08-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_lists', '0015_auto_20250814_0418'),
        ('edcs_subject', '0073_auto_20250814_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lungcancertreatment',
            name='other_interventions',
            field=models.ManyToManyField(to='edcs_lists.OtherInterventionsClass', verbose_name='Other intervention given to lung cancer patients?'),
        ),
    ]
