# Generated by Django 3.1.7 on 2023-05-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_export', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadownload',
            name='username',
            field=models.CharField(default='frdrck', max_length=25, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
