# Generated by Django 3.1.7 on 2023-05-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_export', '0002_datadownload_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadownload',
            name='email',
            field=models.CharField(default='frdrck', max_length=85, verbose_name='Email Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datadownload',
            name='first_name',
            field=models.CharField(default='frdrck', max_length=45, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datadownload',
            name='last_name',
            field=models.CharField(default='frdrck', max_length=45, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
