clinic_super = [
    "edcs_subject.delete_airpollutionfollowUp",
    "edcs_subject.delete_alcoholtobaccouse",
    "edcs_subject.delete_cancerhistory",
    "edcs_subject.delete_contraceptiveusereproductivehistory",
    "edcs_subject.delete_cookingfuel",
    "edcs_subject.delete_covidinfectionhistory",
    "edcs_subject.delete_demographiccharacteristic",
    "edcs_subject.delete_effectairpollution",
    "edcs_subject.delete_hivlabinvestigation",
    "edcs_subject.delete_homelocatorform",
    "edcs_subject.delete_housekitchensurrounding",
    "edcs_subject.delete_lungcancerlabinvestigation",
    "edcs_subject.delete_signsymptomlungcancer",
    "edcs_subject.delete_lungcancertreatment",
    "edcs_subject.delete_occupationalhistory",
    "edcs_subject.delete_subjectvisit",
]
