# Generated by Django 3.1.7 on 2025-08-14 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_lists', '0015_auto_20250814_0418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherInterventionClass',
        ),
    ]
