# Generated by Django 3.1.7 on 2025-08-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_subject', '0074_auto_20250814_0418'),
        ('edcs_lists', '0017_auto_20250814_0448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Immunohistochemistrylab',
            new_name='Immunohistochemistry',
        ),
        migrations.RemoveIndex(
            model_name='immunohistochemistry',
            name='edcs_lists__id_a029b4_idx',
        ),
        migrations.AddIndex(
            model_name='immunohistochemistry',
            index=models.Index(fields=['id', 'display_name', 'display_index'], name='edcs_lists__id_547000_idx'),
        ),
    ]
