from edcs_constants.constants import (
    NEG,
    NEVER,
    NONE,
    NONE_OF_ABOVE,
    NOT_APPLICABLE,
    NOT_DONE,
    OTHER,
    YES_CURRENT_CHEW,
    YES_CURRENT_SMOKER,
    YES_PAST_CHEW,
    YES_PAST_SMOKER,
)
from edcs_subject.constants import (
    NEG_ALK,
    NEG_CALRETININ,
    NEG_CD56,
    NEG_CHROMOGRANIN_A,
    NEG_CK5_6,
    NEG_CK7,
    NEG_CK20,
    NEG_EGFR,
    NEG_HER2,
    NEG_NAPSIN_A,
    NEG_P40,
    NEG_P63,
    NEG_PANCYTOKERATINE,
    NEG_PDL1,
    NEG_ROS1,
    NEG_SYNAPTOPHYSIN,
    NEG_TTF1,
    NEG_VIMENTIN,
    POS_ALK,
    POS_CALRETININ,
    POS_CD56,
    POS_CHROMOGRANIN_A,
    POS_CK5_6,
    POS_CK7,
    POS_CK20,
    POS_EGFR,
    POS_HER2,
    POS_NAPSIN_A,
    POS_P40,
    POS_P63,
    POS_PANCYTOKERATINE,
    POS_PDL1,
    POS_ROS1,
    POS_SYNAPTOPHYSIN,
    POS_TTF1,
    POS_VIMENTIN,
    NEG_Ki67_50_60,
    POS_Ki67_50_60,
)

list_data = {
    "edcs_lists.covidsymptoms": [
        ("headache", "Headache"),
        ("fever", "Fever"),
        ("muscle_ache", "Muscle ache"),
        ("weakness_tiredness", "Weakness/tiredness "),
        ("nausea_vomiting", "Nausea/vomiting"),
        ("abdominal_pain", "Abdominal pain"),
        ("diarrhea", "Diarrhea"),
        ("sore_throat", "Sore throat"),
        ("cough", "Cough"),
        ("shortness_of_breath", "Shortness of breath"),
        ("loss_taste", "Loss of taste"),
        ("no_loss_smell", "No Loss of smell"),
    ],
    "edcs_lists.familymembers": [
        ("mother", "Mother"),
        ("father", "Father"),
        ("sister", "Sister"),
        ("brother", "Brother"),
        ("maternal_aunt", "Maternal Aunt"),
        ("maternal_uncle", "Maternal Uncle"),
        ("paternal_aunt", "Paternal Aunt"),
        ("paternal_uncle", "Paternal Uncle"),
        ("maternal_grandmother", "Maternal Grandmother"),
        ("maternal_grandfather", "Maternal Grandfather"),
        ("paternal_grandmother", "Paternal Grandmother"),
        ("paternal_grandfather", "Paternal Grandfather"),
        (OTHER, "Other"),
    ],
    "edcs_lists.lungcancersymptoms": [
        ("cough_3_week", "A cough that doesn't go away after 2 or 3 weeks"),
        ("long_standing_cough", "A long-standing cough that gets worse"),
        ("coughing_blood", "Coughing up blood or rust-colored sputum (spit or phlegm)"),
        (
            "chest_infections",
            " Chest infections that keep coming back such as bronchitis, pneumonia etc",
        ),
        (
            "chest_pain_coughing",
            " Chest pain that is often worsen when breathing or coughing",
        ),
        ("persistent_breathlessness", "Persistent breathlessness"),
        ("tiredness_lack_energy", "Persistent tiredness or lack of energy"),
        ("wheezing", " Wheezing"),
        ("shortness_of_breath", "Shortness of breath"),
        ("unexplained_weight_loss", "Unexplained weight loss"),
        (OTHER, "Other"),
    ],
    "edcs_lists.smokingtobaccoproducts": [
        (YES_CURRENT_SMOKER, "Yes, Current smoker"),
        (YES_PAST_SMOKER, "Yes, past smoker"),
        (YES_CURRENT_CHEW, "Yes, current chew tobacco"),
        (YES_PAST_CHEW, "Yes, past chew tobacco"),
        (NEVER, "Never"),
    ],
    "edcs_lists.tobaccoproducts": [
        (NOT_APPLICABLE, "Not applicable"),
        ("yes_cigarettes", "Yes, Cigarettes"),
        ("yes_cigars", "Yes, Cigars"),
        ("yes_shisha", "Yes, Shisha"),
        ("yes_pipes", "Yes, pipes"),
        (OTHER, "Other"),
    ],
    "edcs_lists.contraceptives": [
        (NOT_APPLICABLE, "Not applicable"),
        ("oral_contraceptives.", "Oral contraceptives."),
        ("injectables", "Injectables"),
        ("implants", "Implants"),
        ("intra_uterine_device", "Intra Uterine Device"),
        ("patch", "Patch"),
        ("rings", "Rings"),
        ("traditional_contraceptives", "Traditional contraceptives"),
        (OTHER, "Other"),
    ],
    "edcs_lists.covidvaccine": [
        (NOT_APPLICABLE, "Not applicable"),
        ("dont_know_type", "Don’t know type"),
        ("pfizer_biontech_moderna", "Pfizer/BioNTech Moderna"),
        ("oxford_astraZeneca", "Oxford/AstraZeneca"),
        ("janssen_johnson_Johnson", "Janssen\Johnson&Johnson"),
        ("novavax", "Novavax"),
        ("sinovac", "Sinovac"),
        ("sputnik", "Sputnik"),
        ("valneva", "Valneva"),
        ("sinopharm", "Sinopharm"),
        (OTHER, "Other"),
    ],
    "edcs_lists.hivsubtype": [
        (NOT_APPLICABLE, "Not applicable"),
        ("A", "A"),
        ("B", "B"),
        ("C", "C"),
        ("D", "D"),
        ("E", "E"),
        ("F", "F"),
        ("G", "G"),
        ("H", "H"),
        ("K", "K"),
    ],
    "edcs_lists.cookingdone": [
        ("inside_house", "Inside the house"),
        ("outside_house", "Outside the house"),
    ],
    "edcs_lists.cookingarea": [
        (NOT_APPLICABLE, "Not applicable"),
        ("window_outside", "Window outside"),
        ("chimney", "Chimney"),
        ("exhaust", "Exhaust"),
        ("partial_open_outside", "Partially open to the outside"),
        ("none", "None"),
    ],
    "edcs_lists.airmonitorproblem": [
        (NOT_APPLICABLE, "Not applicable"),
        ("window_outside", "Window outside"),
        ("chimney", "Chimney"),
        ("exhaust", "Exhaust"),
        ("partial_open_outside", "Partially open to the outside"),
        ("none", "None"),
    ],
    "edcs_lists.cookingfuel": [
        ("kerosene", "Kerosene"),
        ("charcoal", "Charcoal"),
        ("coal", "Coal"),
        ("gas ", "Gas "),
        ("agricultural_crop", "Agricultural crop"),
        ("wood", "Wood"),
        ("gobar_gas ", "Gobar gas "),
        ("electricity", "Electricity"),
        ("straw_shrubs_grass ", "Straw/shrubs/grass "),
        ("agricultural_crop", "Agricultural crop"),
        ("animal_dung", "Animal dung"),
        (OTHER, "Other"),
    ],
    "edcs_lists.othercookingfuel": [
        ("no_other_fuel", "No other fuel except primary fuel used for cooking"),
        ("kerosene", "Kerosene"),
        ("charcoal", "Charcoal"),
        ("coal", "Coal"),
        ("gas ", "Gas "),
        ("agricultural_crop", "Agricultural crop"),
        ("wood", "Wood"),
        ("gobar_gas ", "Gobar gas "),
        ("electricity", "Electricity"),
        ("straw_shrubs_grass ", "Straw/shrubs/grass "),
        ("agricultural_crop", "Agricultural crop"),
        ("animal_dung", "Animal dung"),
        (OTHER, "Other"),
    ],
    "edcs_lists.solidfuel": [
        ("no_other_fuel", "No other fuel except primary fuel used for cooking"),
        ("kerosene", "Kerosene"),
        ("charcoal", "Charcoal"),
        ("coal", "Coal"),
        ("gas ", "Gas "),
        ("agricultural_crop", "Agricultural crop"),
        ("wood", "Wood"),
        ("gobar_gas ", "Gobar gas "),
        ("electricity", "Electricity"),
        ("straw_shrubs_grass ", "Straw/shrubs/grass "),
        ("agricultural_crop", "Agricultural crop"),
        ("animal_dung", "Animal dung"),
        (OTHER, "Other"),
    ],
    "edcs_lists.solidfuelnew": [
        (NOT_APPLICABLE, "Not applicable; solid fuel was not used for cooking"),
        ("open_fire", "Open fire"),
        ("mud_stove", "Mud stove"),
        ("stove_chimney", "Stove with chimney"),
        ("stove_exhaust_hood", "Stove with exhaust hood "),
        ("stove_builtin_fan", "Stove with built-in fan"),
        ("charcoal_stove", "Charcoal stove"),
    ],
    "edcs_lists.somaticmutations": [
        (NOT_APPLICABLE, "Not applicable"),
        ("EGFR", "EGFR"),
        ("KRAS", "KRAS"),
        ("ALK", "ALK"),
        ("HER2", "HER2"),
        ("ROS1", "ROS1"),
        ("MET", "MET"),
        ("BRAF", "BRAF"),
        ("ERBB2", "ERBB2"),
        ("RET", "RET"),
        ("TP53", "TP53"),
        ("CDKN2A", "CDKN2A"),
        ("RAF1", "RAF1"),
        ("MAP2K1", "MAP2K1"),
        ("SMAD4", "SMAD4"),
        ("NRAS", "NRAS"),
        ("AR", "AR"),
        ("FGFR3", "FGFR3"),
        ("PDGFRA", "PDGFRA"),
        ("B2M", "B2M"),
        ("FBXW7", "FBXW7"),
        ("KEAPI", "KEAPI"),
        ("POLE", "POLE"),
        ("PTEN", "PTEN"),
        ("U2AFI", "U2AFI"),
        ("AKT", "AKT"),
        ("ODR2", "ODR2"),
        ("ERBB3", "ERBB3"),
        ("IDH2", "IDH2"),
        ("FGFR4", "FGFR4"),
        ("NMYC", "NMYC"),
        ("ERG", "ERG"),
        ("MTOR", "MTOR"),
        ("FGFR1", "FGFR1"),
        ("APC", "APC"),
        ("CCND1", "CCND1"),
        ("MYC", "MYC"),
        ("CDK4", "CDK4"),
        ("CTNNBI", "CTNNBI"),
        ("RICTOR", "RICTOR"),
        ("CDKN2A", "CDKN2A"),
        ("HRAS", "HRAS"),
        ("KIT", "KIT"),
        ("SMO", "SMO"),
        ("AXL", "AXL"),
        ("FGFR2", "FGFR2"),
    ],
    "edcs_lists.cancerinvestigation": [
        (NOT_APPLICABLE, "Not applicable"),
        ("blood_tests", "Blood tests"),
        ("chest_xray", "Chest X-ray"),
        ("ct_scan", "CT scan"),
        ("lung_cancer_biopsy", "Lung cancer biopsy"),
        ("sputum_tb_dx", "Sputum for TB diagnosis"),
        (OTHER, "Others"),
        (NONE_OF_ABOVE, "None of the above"),
    ],
    "edcs_lists.industries": [
        (NOT_APPLICABLE, "Not applicable"),
        ("textile_industry", "Textile industry"),
        ("chemical_production_industry", "Chemical production industry"),
        ("food_processing_industry", "Food processing industry"),
        ("drug_industry", "Drug industry"),
        ("milling_industry", "Milling industry"),
        ("construction_industry", "Construction industry"),
        ("gas_fuel_stations", "Gas / fuel stations"),
        ("cement_industry", "Cement industry"),
        (OTHER, "Other"),
    ],
    "edcs_lists.followuptest": [
        (NOT_APPLICABLE, "Not applicable"),
        ("chest_xray", "Yes, chest X-ray"),
        ("ct_scan", "Yes, CT scan"),
        ("ultrasound_scan", "Yes, Ultrasound scan"),
        ("blood_cbc", "Yes, Blood CBC"),
        ("chemistry_tests", "Yes, Chemistry tests"),
        (NONE, "None"),
        (OTHER, "Other"),
    ],
    "edcs_lists.immunohistochemistrylab": [
        (POS_TTF1, "Positive- TTF1"),
        (NEG_TTF1, "Negative- TTF1"),
        (POS_P40, "Positive- P40"),
        (NEG_P40, "Negative- P40"),
        (POS_P63, "Positive- P63"),
        (NEG_P63, "Negative- P63"),
        (POS_PANCYTOKERATINE, "Positive- PANCYTOKERATINE"),
        (NEG_PANCYTOKERATINE, "Negative- PANCYTOKERATINE"),
        (POS_CK20, "Positive- CK20"),
        (NEG_CK20, "Negative- CK20"),
        (POS_CK7, "Positive- CK7"),
        (NEG_CK7, "Negative- CK7"),
        (POS_CK5_6, "Positive- CK5/6"),
        (NEG_CK5_6, "Negative- CK5/6"),
        (POS_VIMENTIN, "Positive- Vimentin"),
        (NEG_VIMENTIN, "Negative- Vimentin"),
        (POS_PDL1, "Positive- PDL1"),
        (NEG_PDL1, "Negative- PDL1"),
        (POS_EGFR, "Positive- EGFR"),
        (NEG_EGFR, "Negative- EGFR"),
        (POS_SYNAPTOPHYSIN, "Positive- Synaptophysin"),
        (NEG_SYNAPTOPHYSIN, "Negative- Synaptophysin"),
        (POS_HER2, "Positive- HER2"),
        (NEG_HER2, "Negative- HER2"),
        (POS_CHROMOGRANIN_A, "Positive- Chromogranin A"),
        (NEG_CHROMOGRANIN_A, "Negative- Chromogranin A"),
        (POS_Ki67_50_60, "Positive- Ki67 (50-60%)"),
        (NEG_Ki67_50_60, "Negative- Ki67 (50-60%)"),
        (POS_CALRETININ, "Positive- Calretinin"),
        (NEG_CALRETININ, "Negative- Calretinin"),
        (POS_NAPSIN_A, "Positive- Napsin A"),
        (NEG_NAPSIN_A, "Negative- Napsin A"),
        (POS_ROS1, "Positive- ROS1"),
        (NEG_ROS1, "Negative- ROS1"),
        (POS_ALK, "Positive- ALK"),
        (NEG_ALK, "Negative- ALK"),
        (POS_CD56, "Positive- CD56"),
        (NEG_CD56, "Negative- CD56"),
        (NOT_DONE, "Note done"),
    ],
    "edcs_lists.oncominevariantclass": [
        (NOT_APPLICABLE, "Not applicable"),
        (NONE, "None"),
        ("amplification", "Amplification"),
        ("Fusion", "Fusion"),
        ("nontargetedfusion", "NonTargetedFusion"),
        ("rnaexonvariant", "RNAExonVariant"),
        ("hotspot", "Hotspot"),
        ("egfrexon19Deletion", "EGFRExon19Deletion"),
        ("egfrexon20Insertion", "EGFRExon20Insertion"),
        ("erbb2exon20insertion", "ERBB2Exon20Insertion"),
        ("kitexon11deletion", "KITExon11Deletion"),
        ("kitexon11insertion", "KITExon11Insertion"),
        ("metexon14skipping", "METExon14Skipping"),
        ("pdgfraexon18deletion", "PDGFRAExon18Deletion"),
    ],
    "edcs_lists.lungcancertreatmentclass": [
        (NOT_APPLICABLE, "Not applicable"),
        ("chemotherapy", "Chemotherapy"),
        ("radiation", "Radiation"),
        ("surgical", "Surgical resection"),
        ("immunotherapy", "Immunotherapy"),
        ("tyrosine_kinase", "Tyrosine kinase inhibitor"),
        (OTHER, "Others"),
    ],
    "edcs_lists.otherinterventionsclass": [
        ("oxygen_therapy", "Oxygen therapy"),
        ("blood_transfusion", "Blood transfusion"),
        ("thoracocentesis", "Thoracocentesis"),
        ("antibiotics", "Antibiotics eg Ceftriaxone/Sulbactam"),
        ("ppis", "PPIs eg Rabeprazole"),
        ("antifungals", "Antifungals eg Fluconazole"),
        ("anticoagulants", "Anticoagulants eg Rivaroxaban"),
        ("iv_fluids", "IV fluids eg RL , NS"),
        ("opioid_analgesic", "Opioid analgesic eg morphine"),
        ("corticosteroid", "Corticosteroid eg Bexamethasone"),
        ("antihistamines", "Antihistamines eg promethazine"),
        ("anti_emetics", "Anti emetics eg Metoclopramide"),
        ("anticonvulsant_analgesic", "Anticonvulsant analgesic eg pregabalin"),
        ("bisphosphonates", "Bisphosphonates eg Zoledronic acid"),
        ("expectorants", "Expectorants"),
        ("multivitamins", "Multivitamins"),
        ("tricyclic_antidepressant", "Tricyclic antidepressant eg amitriptyline"),
    ],
}

# preload_data = PreloadData(list_data=list_data)
