# Generated by Django 3.1.7 on 2022-01-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_consent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsubjectconsent',
            name='clinic_type',
        ),
        migrations.RemoveField(
            model_name='subjectconsent',
            name='clinic_type',
        ),
    ]
