# Generated by Django 3.1.7 on 2022-02-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_consent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubjectconsent',
            name='clinic_type',
            field=models.CharField(choices=[('lung_cancer', 'Lung cancer clinic/institute'), ('pathology', 'Pathology'), ('other_clinic', 'Other ward/clinic other than cancer')], max_length=45, null=True, verbose_name='From which type of clinic was the patient selected?'),
        ),
        migrations.AddField(
            model_name='historicalsubjectconsent',
            name='patient_category',
            field=models.CharField(choices=[('lung_cancer_suspect', 'Lung cancer suspect'), ('other_cancers', 'Other cancers'), ('cancer_free', 'Cancer free')], max_length=45, null=True, verbose_name='Patient Category?'),
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='clinic_type',
            field=models.CharField(choices=[('lung_cancer', 'Lung cancer clinic/institute'), ('pathology', 'Pathology'), ('other_clinic', 'Other ward/clinic other than cancer')], max_length=45, null=True, verbose_name='From which type of clinic was the patient selected?'),
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='patient_category',
            field=models.CharField(choices=[('lung_cancer_suspect', 'Lung cancer suspect'), ('other_cancers', 'Other cancers'), ('cancer_free', 'Cancer free')], max_length=45, null=True, verbose_name='Patient Category?'),
        ),
    ]
