# Generated by Django 3.1.7 on 2022-05-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edcs_consent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubjectconsent',
            name='nationality',
            field=models.CharField(choices=[('tanzanian', 'Tanzanian'), ('ugandan', 'Ugandan'), ('OTHER', 'Other')], default='null', max_length=60, verbose_name='Nationality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjectconsent',
            name='nationality',
            field=models.CharField(choices=[('tanzanian', 'Tanzanian'), ('ugandan', 'Ugandan'), ('OTHER', 'Other')], default='null', max_length=60, verbose_name='Nationality'),
            preserve_default=False,
        ),
    ]
